// react-ui/src/collectionTools/ExerciseOverview.tsx
import React from 'react';
import {ExerciseOverviewQuery, PartFragment, useExerciseOverviewQuery} from '../graphql';
import {ExerciseIProps} from '../ToolBase';
import {Link, Redirect, useRouteMatch} from 'react-router-dom';
import {BreadCrumbPart, BreadCrumbs} from '../helpers/BreadCrumbs';
import {WithQuery} from '../WithQuery';
import {useSelector} from 'react-redux';
import {currentUserSelector} from '../store/store';
import {useTranslation} from 'react-i18next';

export function ExerciseOverview({toolId, collectionId, exerciseId}: ExerciseIProps): JSX.Element {

  const {t} = useTranslation('common');
  const {url} = useRouteMatch();
  const currentUser = useSelector(currentUserSelector);

  const exerciseOverviewQuery = useExerciseOverviewQuery({variables: {toolId, collectionId, exerciseId}});

  function render({tool}: ExerciseOverviewQuery): JSX.Element {

    if (!tool) {
      return <Redirect to={''}/>;
    }

    const collection = tool.collection;

    if (!collection) {
      return <Redirect to={''}/>;
    }

    const exercise = collection.exercise;

    if (!exercise) {
      return <Redirect to={''}/>;
    }

    const entryParts: PartFragment[] = exercise.parts.filter((p) => p.isEntryPart);

    console.info(JSON.stringify(exercise.parts));
    console.info(JSON.stringify(entryParts));

    const breadCrumbs: BreadCrumbPart[] = [
      {routerLinkPart: '/', title: 'Tools'},
      {routerLinkPart: `tools/${toolId}`, title: tool.name},
      {routerLinkPart: 'collections', title: 'Sammlungen'},
      {routerLinkPart: collection.collectionId.toString(), title: collection.title},
      {routerLinkPart: 'exercises', title: 'Aufgaben'},
      {routerLinkPart: exercise.exerciseId.toString(), title: exercise.exerciseId.toString()}
    ];

    return (
      <div className="container">

        <h1 className="title is-3 has-text-centered">Aufgabe &quot;{exercise.title}&quot;</h1>

        <div className="my-3">
          <BreadCrumbs parts={breadCrumbs}/>
        </div>

        <div className="notification is-light-grey" dangerouslySetInnerHTML={{__html: exercise.text}}/>

        {currentUser
          ? <div className="columns">
            {entryParts.map((part) =>
              <div className="column" key={part.id}>
                <Link className="button is-link is-fullwidth" to={`${url}/parts/${part.id}`}>{part.name}</Link>
              </div>)}
          </div>
          : <div className="notification is-primary has-text-centered">{t('pleaseLogin')}</div>
        }

      </div>
    );

  }

  return <WithQuery query={exerciseOverviewQuery} render={render}/>;
}

// client/src/app/tools/collection-tools/exercise-overview/exercise-overview.component.ts
import {Component, OnInit} from '@angular/core';
import {Exercise, Tool} from '../../../_interfaces/tool';
import {ActivatedRoute, Router} from '@angular/router';
import {collectionTools} from '../collection-tools-list';
import {ApiService} from '../_services/api.service';

@Component({templateUrl: './exercise-overview.component.html'})
export class ExerciseOverviewComponent implements OnInit {

  tool: Tool;
  collectionId: number;
  exercise: Exercise;

  constructor(private route: ActivatedRoute, private router: Router, private apiService: ApiService) {
    const toolId = this.route.snapshot.paramMap.get('toolId');
    this.collectionId = parseInt(this.route.snapshot.paramMap.get('collId'), 10);


    this.tool = collectionTools.find((t) => t.id === toolId);

    if (!this.tool) {
      this.router.navigate(['../..']);
    }
  }

  ngOnInit() {
    const exerciseId = parseInt(this.route.snapshot.paramMap.get('exId'), 10);

    this.apiService.getExercise(this.tool.id, this.collectionId, exerciseId)
      .subscribe((exercise) => {
        console.info(JSON.stringify(exercise, null, 2));

        this.exercise = exercise;
      });
  }

}

<div class="container">
  <h1 class="title is-3 has-text-centered">Aufgabe &quot;{{exercise?.title}}&quot;</h1>

  <div class="buttons">
    <a class="button is-primary is-fullwidth" [routerLink]="['../..']">Zurück zur Sammlung</a>
  </div>

  <br>

  <div class="notification">
    {{exercise?.text}}
  </div>

  <ng-container *ngFor="let part of tool.parts">
    <div class="column" *ngIf="!part.disabled && tool.exerciseHasPart(exercise, part)">
      <a class="button is-link is-fullwidth"
         [routerLink]="['/tools', tool.id, 'collections', exercise.collId, 'exercises', exercise.id, 'parts', part.id]">
        {{part.name}}
      </a>
    </div>
  </ng-container>

</div>
