// react-ui/src/randomTools/NaryTwoConversion.tsx
import React, {useState} from 'react';
import {NaryNumberReadOnlyInputComponent, NaryReadOnlyNumberInput} from './NaryNumberReadOnlyInput';
import {DECIMAL_SYSTEM, NaryIState} from './nary';
import {RandomSolveButtons} from './RandomSolveButtons';
import {useTranslation} from 'react-i18next';
import {randomInt} from './boolModel/bool-formula';
import {NaryLimits} from './NaryLimits';
import {NaryNumberInput} from './NaryNumberInput';

interface IState extends NaryIState {
  toConvertInput: NaryReadOnlyNumberInput;
  withIntermediateSteps: boolean;
  binaryAbsoluteString: string;
  binaryAbsoluteCorrect: boolean;
  invertedAbsoluteString: string;
  invertedAbsoluteCorrect: boolean;
}

function generateExercise(max = 128, withIntermediateSteps = false): IState {
  return {
    max,
    toConvertInput: {
      decimalNumber: randomInt(1, max), maxValueForDigits: max, numberingSystem: DECIMAL_SYSTEM
    },
    checked: false,
    withIntermediateSteps,
    binaryAbsoluteString: '',
    binaryAbsoluteCorrect: false,
    invertedAbsoluteString: '',
    invertedAbsoluteCorrect: false,
    solutionString: '',
    correct: false
  };
}


export function NaryTwoConversion(): JSX.Element {

  const {t} = useTranslation('common');
  const [state, setState] = useState<IState>(generateExercise);

  function correct(): void {
    const toConvert = state.toConvertInput.decimalNumber;

    const binaryAbsoluteCorrect = toConvert === parseInt(state.binaryAbsoluteString.replace(/\s+/, ''), 2);

    const invertedAbsoluteCorrect = toConvert === parseInt(state.invertedAbsoluteString
      .replace(/\s+/, '')
      .replace(/[01]/g, (x) => x === '0' ? '1' : '0'), 2);

    const positiveSolution = parseInt(state.solutionString.replace(/\s+/, ''), 2);

    const awaitedBinaryAbsolute = toConvert.toString(2);
    const awaitedInvertedAbsolute = awaitedBinaryAbsolute
      .padStart(8, '0')
      .replace(/[01]/g, (x) => x === '0' ? '1' : '0');
    const awaitedPositiveSolution = parseInt(awaitedInvertedAbsolute, 2) + 1;

    const correct = positiveSolution === awaitedPositiveSolution;

    setState((state) => ({...state, checked: true, binaryAbsoluteCorrect, invertedAbsoluteCorrect, correct}));
  }

  return (
    <div className="container">
      <h1 className="title is-3 has-text-centered">{t('naryTwoConversion')}</h1>

      <NaryLimits max={state.max} update={(newValue) => setState(generateExercise(newValue))}/>

      <div className="field">
        <div className="control has-text-centered">
          <label className="checkbox">
            <input type="checkbox" checked={state.withIntermediateSteps}
                   onChange={(event) => setState((state) => ({...state, withIntermediateSteps: event.target.checked}))}/> Mit Zwischenschritten
          </label>
        </div>
      </div>

      <p className="is-italic has-text-info has-text-centered">Geben Sie alle Binärzahlen mit einer Länge von 8 Bit ein!</p>

      <hr/>

      <NaryNumberReadOnlyInputComponent labelContent={t('startNumber')} naryNumberInput={state.toConvertInput}/>

      <br/>

      <NaryNumberInput labelContent={`Binärdarstellung von ${state.toConvertInput.decimalNumber}`} initialValue={state.binaryAbsoluteString}
                       checked={state.checked && state.withIntermediateSteps} correct={state.withIntermediateSteps} radix={2}
                       update={(newValue) => setState((state) => ({...state, binaryAbsoluteString: newValue}))} disabled={!state.withIntermediateSteps}/>

      <br/>

      <NaryNumberInput labelContent="Invertierung aller Bits" initialValue={state.invertedAbsoluteString} checked={state.checked && state.withIntermediateSteps}
                       correct={state.invertedAbsoluteCorrect} radix={2}
                       update={(newValue) => setState((state) => ({...state, invertedAbsoluteString: newValue}))} disabled={!state.withIntermediateSteps}/>

      <hr/>

      <NaryNumberInput labelContent={t('twoComplement')} initialValue={state.solutionString} checked={state.checked} correct={state.correct} radix={2}
                       update={(newValue) => setState((state) => ({...state, solutionString: newValue}))}/>

      <br/>

      <RandomSolveButtons toolId={'nary'} correct={correct}
                          nextExercise={() => setState(({max, withIntermediateSteps}) => generateExercise(max, withIntermediateSteps))}/>

    </div>
  );
}

// ui/src/app/tools/random-tools/nary/nary-two-conversion/nary-two-conversion.component.ts
import {Component, HostListener, OnInit} from '@angular/core';
import {DECIMAL_SYSTEM, NaryComponentBase, NaryReadOnlyNumberInput} from '../nary';
import {NaryTwoConversionToolPart} from '../../random-tools-list';
import {ToolPart} from '../../../../_interfaces/tool';
import {randomInt} from '../../../../helpers';

@Component({templateUrl: './nary-two-conversion.component.html'})
export class NaryTwoConversionComponent extends NaryComponentBase implements OnInit {

  toolPart: ToolPart = NaryTwoConversionToolPart;

  withIntermediateSteps = true;

  toConvertInput: NaryReadOnlyNumberInput = {
    decimalNumber: 0,
    numberingSystem: DECIMAL_SYSTEM,
    fieldId: 'startNumber',
    labelContent: 'Startzahl:',
    maxValueForDigits: this.max
  };

  binaryAbsoluteString = '';
  invertedAbsoluteString = '';
  solutionString = '';

  checked = false;

  binaryAbsoluteCorrect = false;
  invertedAbsoluteCorrect = false;
  solutionCorrect = false;

  completelyCorrect = false;

  constructor() {
    super(128);
  }

  private static swapOnesAndZeros(str: string): string {
    return str
      .replace(/0/g, 'a')
      .replace(/1/g, '0')
      .replace(/a/g, '1');
  }

  ngOnInit(): void {
    this.update();
  }

  update(): void {
    this.toConvertInput.decimalNumber = randomInt(0, this.max);
    this.toConvertInput.maxValueForDigits = this.max;

    this.checked = false;

    this.binaryAbsoluteString = '';
    this.invertedAbsoluteString = '';
    this.solutionString = '';
  }

  checkSolution(): void {
    this.checked = true;

    const absoluteToConvert = Math.abs(this.toConvertInput.decimalNumber);

    const binAbsStr: string = this.binaryAbsoluteString.replace(/\s+/g, '');
    this.binaryAbsoluteCorrect = binAbsStr.length === 8 && parseInt(binAbsStr, 2) === absoluteToConvert;

    const invAbsStr: string = this.invertedAbsoluteString.replace(/\s+/g, '');
    const awaitedInvertedAbs: string = NaryTwoConversionComponent.swapOnesAndZeros(absoluteToConvert.toString(2).padStart(8, '0'));
    this.invertedAbsoluteCorrect = invAbsStr.length === 8 && awaitedInvertedAbs === invAbsStr;

    const solStr: string = this.solutionString.replace(/\s+/g, '');
    const awaitedSolution: string = (parseInt(awaitedInvertedAbs, 2) + 1).toString(2).padStart(8, '0');

    this.solutionCorrect = solStr.length === 8 && awaitedSolution === solStr;
  }

  @HostListener('document:keypress', ['$event'])
  handleKeyboardEvent(event: KeyboardEvent): void {
    if (event.key === 'Enter') {
      if (this.completelyCorrect) {
        this.update();
      } else {
        this.checkSolution();
      }
    }
  }

}

<div class="container">

  <h1 class="title is-3 has-text-centered">{{toolPart.name}}</h1>

  <div class="columns">
    <div class="column is-half-desktop is-offset-one-quarter-desktop">

      <label class="label has-text-centered" for="max">Maximalwert</label>
      <div class="field has-addons">
        <div class="control">
          <button class="button" (click)="doubleMax()" [disabled]="max === maximalMax">* 2</button>
        </div>
        <div class="control is-expanded">
          <input class="input has-text-centered" type="number" id="max" value="{{max}}">
        </div>
        <div class="control">
          <button class="button" (click)="halveMax()" [disabled]="max === minimalMax">/ 2</button>
        </div>
      </div>

      <div class="field">
        <div class="control has-text-centered">
          <label class="checkbox">
            <input type="checkbox" [(ngModel)]="withIntermediateSteps"> Mit Zwischenschritten
          </label>
        </div>
      </div>

      <p class="is-italic has-text-info has-text-centered">Geben Sie alle Binärzahlen mit einer Länge von 8 Bit ein!</p>

      <hr>

      <it4all-nary-number-read-only-input [naryNumberInput]="toConvertInput"></it4all-nary-number-read-only-input>

      <br>

      <div class="field">
        <div class="field has-addons">
          <div class="control">
            <div class="button is-static">
              <label for="binaryAbsolute">Binärdarstellung von {{toConvertInput.decimalNumber}}:</label>
            </div>
          </div>
          <div class="control is-expanded">
            <input type="text" class="input has-text-right" id="binaryAbsolute" [(ngModel)]="binaryAbsoluteString"
                   [class.is-success]="checked && withIntermediateSteps && binaryAbsoluteCorrect"
                   [class.is-danger]="checked && withIntermediateSteps && !binaryAbsoluteCorrect"
                   placeholder="Binärdarstellung von {{toConvertInput.decimalNumber}}" autofocus autocomplete="off">
          </div>
          <div class="control">
            <div class="button is-static">
              <sub>2</sub>
            </div>
          </div>
        </div>
      </div>

      <div class="notification has-text-centered is-danger"
           *ngIf="checked && withIntermediateSteps && !binaryAbsoluteCorrect">
        &#10008; Diese Eingabe ist nicht korrekt.
      </div>
      <div class="notification has-text-centered is-success"
           *ngIf="checked && withIntermediateSteps && binaryAbsoluteCorrect">
        &#10004; Diese Eingabe ist korrekt.
      </div>

      <br>

      <div class="field">
        <div class="field has-addons">
          <div class="control">
            <div class="button is-static">
              <label for="invertedAbsolute">Invertierung aller Bits:</label>
            </div>
          </div>
          <div class="control is-expanded">
            <input type="text" class="input has-text-right" id="invertedAbsolute" [(ngModel)]="invertedAbsoluteString"
                   [class.is-success]="checked && withIntermediateSteps && invertedAbsoluteCorrect"
                   [class.is-danger]="checked && withIntermediateSteps && !invertedAbsoluteCorrect"
                   placeholder="Invertierung aller Bits" autofocus autocomplete="off">
          </div>
          <div class="control">
            <div class="button is-static">
              <sub>2</sub>
            </div>
          </div>
        </div>
      </div>

      <div class="notification has-text-centered is-danger"
           *ngIf="checked && withIntermediateSteps && !invertedAbsoluteCorrect">
        &#10008; Diese Eingabe ist nicht korrekt.
      </div>
      <div class="notification has-text-centered is-success"
           *ngIf="checked && withIntermediateSteps && invertedAbsoluteCorrect">
        &#10004; Diese Eingabe ist korrekt.
      </div>

      <hr>

      <div class="field">
        <div class="field has-addons">
          <div class="control">
            <div class="button is-static">
              <label for="solution">Zweierkomplement:</label>
            </div>
          </div>
          <div class="control is-expanded">
            <input type="text" class="input has-text-right" id="solution" [(ngModel)]="solutionString"
                   [class.is-success]="checked && solutionCorrect" [class.is-danger]="checked && !solutionCorrect"
                   placeholder="Zweierkomplement" autofocus autocomplete="off">
          </div>
          <div class="control">
            <div class="button is-static">
              <sub>2</sub>
            </div>
          </div>
        </div>
      </div>

      <div class="notification has-text-centered is-danger" *ngIf="checked && !solutionCorrect">
        &#10008; Die Lösung ist nicht korrekt.
      </div>
      <div class="notification has-text-centered is-success" *ngIf="checked && solutionCorrect">
        &#10004; Die Lösung ist korrekt.
      </div>

      <br>

      <it4all-random-solve-buttons
        (correctEmitter)="checkSolution()"
        (nextEmitter)="update()">
      </it4all-random-solve-buttons>

    </div>
  </div>
</div>
