// react-ui/src/collectionTools/tools/flask/FlaskExercise.tsx
import React from 'react';
import {
  ExerciseFileFragment,
  FilesSolutionInput,
  FlaskCorrectionMutation,
  FlaskExerciseContentFragment,
  FlaskExercisePart,
  useFlaskCorrectionMutation
} from '../../../graphql';
import {ConcreteExerciseIProps} from '../../Exercise';
import {FilesExercise} from '../FilesExercise';
import {WithQuery} from '../../../WithQuery';
import {SolutionSaved} from '../../../helpers/SolutionSaved';
import {PointsNotification} from '../../../helpers/PointsNotification';
import classNames from 'classnames';

type IProps = ConcreteExerciseIProps<FlaskExerciseContentFragment, FilesSolutionInput>;

export function FlaskExercise({exercise, content, partId, oldSolution}: IProps): JSX.Element {

  const [correctExercise, correctionMutationResult] = useFlaskCorrectionMutation();

  const exerciseDescription = <>
    <div className="mb-3" dangerouslySetInnerHTML={{__html: exercise.text}}/>

    <p>Es werden folgende Testfälle ausgeführt:</p>

    {content.testConfig.tests.map((singleTestConfig) =>
      <div key={singleTestConfig.id}>
        {singleTestConfig.id}. <code>{singleTestConfig.testName}</code>:
        <span dangerouslySetInnerHTML={{__html: singleTestConfig.description}}/>
      </div>
    )}
  </>;

  function correct(files: ExerciseFileFragment[]): void {
    const solution: FilesSolutionInput = {
      files: files.map(({name, content, fileType, editable}) => ({name, content, fileType, editable}))
    };

    correctExercise({variables: {collId: exercise.collectionId, exId: exercise.exerciseId, solution, part: FlaskExercisePart.FlaskSingleExPart}})
      .catch((err) => console.error(err));
  }

  function renderCorrection({flaskExercise}: FlaskCorrectionMutation): JSX.Element {
    if (!flaskExercise) {
      throw new Error('TODO!');
    }

    const {solutionSaved,/*proficienciesUpdated, resultSaved,*/ result} = flaskExercise.correct;

    console.info(JSON.stringify(result, null, 2));

    return (
      <>
        <SolutionSaved solutionSaved={solutionSaved}/>

        <PointsNotification points={result.points} maxPoints={result.maxPoints}/>

        {result.testResults.map((testResult, index) =>
          <div className="my-3" key={index}>
            <div className={classNames('message', testResult.successful ? 'is-success' : 'is-danger')}>
              <header className="message-header">{testResult.testName}</header>
              <div className="message-body">
                <pre>{testResult.stderr.join('\n')}</pre>
              </div>
            </div>
          </div>
        )}
      </>
    );
  }

  return <FilesExercise exerciseId={exercise.exerciseId} exerciseDescription={exerciseDescription} initialFiles={content.files}
                        sampleSolutions={content.flaskSampleSolutions} correct={correct}
                        correctionTabRender={() => <WithQuery query={correctionMutationResult} render={renderCorrection}/>}
                        isCorrecting={false /*TODO!*/}/>;
}

// ui/src/app/tools/collection-tools/flask/flask-exercise/flask-exercise.component.ts
import {Component, Input, OnInit, ViewChild} from '@angular/core';
import {
  ExerciseFileFragment,
  ExerciseSolveFieldsFragment,
  FilesSolution,
  FilesSolutionInput,
  FlaskCorrectionGQL,
  FlaskCorrectionMutation,
  FlaskCorrectionMutationVariables,
  FlaskCorrectionResultFragment,
  FlaskExerciseContentFragment,
  FlaskExercisePart,
  FlaskResultFragment
} from "../../../../_services/apollo_services";
import {ComponentWithExerciseDirective} from "../../_helpers/component-with-exercise.directive";
import {DexieService} from "../../../../_services/dexie.service";
import {FilesExerciseComponent} from "../../_components/files-exercise/files-exercise.component";

import 'codemirror/mode/jinja2/jinja2';
import 'codemirror/mode/python/python';


function getIdForFlaskExPart(flaskExPart: FlaskExercisePart): string {
  switch (flaskExPart) {
    case FlaskExercisePart.FlaskSingleExPart:
      return 'solve';
  }
}

@Component({
  selector: 'it4all-flask-exercise',
  templateUrl: './flask-exercise.component.html'
})
export class FlaskExerciseComponent
  extends ComponentWithExerciseDirective<FilesSolutionInput, FlaskCorrectionMutation, FlaskCorrectionMutationVariables>
  implements OnInit {

  @Input() exerciseFragment: ExerciseSolveFieldsFragment;
  @Input() contentFragment: FlaskExerciseContentFragment;

  @ViewChild(FilesExerciseComponent) filesExerciseComponent: FilesExerciseComponent;

  readonly partId: string = getIdForFlaskExPart(FlaskExercisePart.FlaskSingleExPart);

  exerciseFileFragments: ExerciseFileFragment[] = [];

  constructor(flaskCorrectionGQL: FlaskCorrectionGQL, dexieService: DexieService) {
    super(flaskCorrectionGQL, dexieService);
  }

  ngOnInit(): void {
    this.exerciseFileFragments = this.contentFragment.files;

    this.loadOldSolutionAbstract(
      this.exerciseFragment,
      this.partId,
      (oldSol) => this.exerciseFileFragments = oldSol.files
    );
  }

  // Sample solutions

  get sampleSolutions(): FilesSolution[] {
    return this.contentFragment.flaskSampleSolutions;
  }

  // Correction

  protected getSolution(): FilesSolutionInput | undefined {
    return {files: this.exerciseFileFragments};
  }

  protected getMutationQueryVariables(): FlaskCorrectionMutationVariables {
    return {
      exId: this.exerciseFragment.exerciseId,
      collId: this.exerciseFragment.collectionId,
      part: FlaskExercisePart.FlaskSingleExPart,
      solution: this.getSolution()
    };
  }

  correct(): void {
    this.correctAbstract(this.exerciseFragment, this.partId, () => {
      if (this.filesExerciseComponent) {
        this.filesExerciseComponent.toggleCorrectionTab();
      }
    });
  }

  // Result

  get correctionResult(): FlaskCorrectionResultFragment | undefined {
    return this.resultQuery?.me.flaskExercise?.correct;
  }

  get result(): FlaskResultFragment | undefined {
    return this.correctionResult?.result;
  }

}

<it4all-files-exercise
  [exerciseFiles]="exerciseFileFragments"
  [isCorrecting]="isCorrecting"
  [sampleSolutions]="sampleSolutions"
  (correct)="correct()"
  defaultMode="'python'">

  <div class="content" exText>
    <div class="mb-3" [innerHTML]="exerciseFragment.text"></div>

    <p>Es werden folgende Testfälle ausgeführt:</p>

    <div *ngFor="let singleTestConfig of contentFragment.testConfig.tests">
      {{singleTestConfig.id}}. <code>{{singleTestConfig.testName}}</code>:
      <span [innerHTML]="singleTestConfig.description"></span>
    </div>
  </div>

  <ng-container correctionContent *ngIf="resultQuery">

    <div class="my-3">
      <it4all-solution-saved [solutionSaved]="correctionResult.solutionSaved"></it4all-solution-saved>
    </div>

    <div class="my-3">
      <it4all-points-notification [points]="result.points" [maxPoints]="result.maxPoints">
      </it4all-points-notification>
    </div>


    <div class="message is-danger" *ngIf="queryError">
      <div class="message-header">Es gab einen internen Fehler bei der Korrektur:</div>
      <div class="message-body">
        <pre>{{queryError.message}}</pre>
      </div>
    </div>

    <div *ngFor="let testResult of result.testResults" class="my-3">
      <div class="message" [ngClass]="testResult.successful ? 'is-success' : 'is-danger'">
        <header class="message-header">{{testResult.testName}}</header>
        <div class="message-body">
          <pre>{{testResult.stderr.join("\n")}}</pre>
        </div>
      </div>

    </div>
  </ng-container>

</it4all-files-exercise>
