// ui/src/app/tools/collection-tools/_components/exercise-file-card/exercise-file-card.component.ts
import {Component, Input} from '@angular/core';
import {ExerciseFileFragment} from "../../../../_services/apollo_services";

@Component({
  selector: 'it4all-exercise-file-card',
  template: `
    <div class="card">
      <header class="card-header">
        <p class="card-header-title">{{exerciseFile.name}}</p>
      </header>
      <div class="card-content">
        <pre>{{exerciseFile.content}}</pre>
      </div>
    </div>
  `
})
export class ExerciseFileCardComponent {

  @Input() exerciseFile: ExerciseFileFragment;

}

// react-ui/src/collectionTools/tools/ExerciseFileCard.tsx
import React from 'react';
import {ExerciseFileFragment} from '../../graphql';

interface IProps {
  exerciseFile: ExerciseFileFragment;
}

export function ExerciseFileCard({exerciseFile}: IProps): JSX.Element {
  return (
    <div className="card">
      <header className="card-header">
        <p className="card-header-title">{exerciseFile.name}</p>
      </header>
      <div className="card-content">
        <pre>{exerciseFile.content}</pre>
      </div>
    </div>
  );
}
