// it4all-client/src/app/tools/collection-tools/xml/xml-exercise/xml-exercise.component.ts
import {Component, Input, OnInit} from '@angular/core';
import {IExercise, IExerciseFile, IXmlCompleteResult, IXmlExerciseContent, IXmlSolution} from '../../../../_interfaces/models';
import {ToolPart} from '../../../../_interfaces/tool';

import 'codemirror/mode/dtd/dtd';
import 'codemirror/mode/xml/xml';
import {ApiService} from '../../_services/api.service';
import {ComponentWithExercise} from '../../_helpers/component-with-exercise';


@Component({
  selector: 'it4all-xml-exercise',
  templateUrl: './xml-exercise.component.html'
})
export class XmlExerciseComponent extends ComponentWithExercise<IXmlCompleteResult> implements OnInit {

  @Input() exercise: IExercise;
  @Input() part: ToolPart;

  exerciseContent: IXmlExerciseContent;

  grammarFile: IExerciseFile;
  documentFile: IExerciseFile;

  exerciseFiles: IExerciseFile[] = [];


  constructor(private apiService: ApiService) {
    super();
  }

  ngOnInit() {
    this.exerciseContent = this.exercise.content as IXmlExerciseContent;

    const isGrammarPart = this.part.id === 'grammar';

    const grammarFileName = `${this.exerciseContent.rootNode}.dtd`;
    this.grammarFile = {
      name: grammarFileName, content: `<!ELEMENT ${this.exerciseContent.rootNode} (EMPTY)>`,
      fileType: 'dtd', editable: isGrammarPart, resourcePath: grammarFileName
    };

    const documentFileName = `${this.exerciseContent.rootNode}.xml`;
    this.documentFile = {
      name: documentFileName, content: '', fileType: 'xml',
      editable: !isGrammarPart, resourcePath: documentFileName
    };

    this.exerciseFiles = [this.grammarFile, this.documentFile];
  }

  showSampleSolution(): void {
    console.error('TODO: show sample sol...');
  }

  correct(): void {
    this.isCorrecting = true;

    console.error('TODO: correct!');
    const solution: IXmlSolution = {grammar: this.grammarFile.content, document: this.documentFile.content};

    this.apiService.correctSolution<IXmlSolution, IXmlCompleteResult>(this.exercise, this.part.id, solution)
      .subscribe((result) => {
        this.isCorrecting = false;

        this.result = result;

        console.info(JSON.stringify(result, null, 2));
      });
  }

}

<div class="container is-fluid">

  <div class="columns">
    <div class="column is-half-desktop">
      <it4all-exercise-files-editor
        [exerciseFiles]="exerciseFiles"
        [mode]="'xml'">
      </it4all-exercise-files-editor>
    </div>

    <div class="column is-half-desktop">
      <it4all-tabs>
        <it4all-tab [title]="'Aufgabenstellung'">

          <div class="notification is-light-grey">
            <ng-container *ngIf="part.id === 'grammar'; else documentTextBlock">
              <p class="has-text-weight-bold">Erstellen Sie eine DTD zu folgender Beschreibung:</p>
              <p>{{exerciseContent.grammarDescription}}</p>
              <p class="is-italic has-text-info">
                Hinweis: Benutzen Sie die in Klammern angegebenen Element- bzw. Attributnamen. Falls nichts anderes
                angegeben ist, sollen die Elemente nur Text enthalten.
              </p>
            </ng-container>
            <ng-template #documentTextBlock>
              TODO!
            </ng-template>
          </div>

          <div class="columns">
            <div class="column">
              <button class="button is-link is-fullwidth" [class.is-loading]="isCorrecting" (click)="correct()">
                Korrektur
              </button>
            </div>
            <div class="column">
              <button class="button is-primary is-fullwidth" (click)="showSampleSolution()" disabled>
                Musterlösung anzeigen
              </button>
            </div>
            <div class="column">
              <a [routerLink]="['../..']" class="button is-dark is-fullwidth">Bearbeiten beenden</a>
            </div>
          </div>


        </it4all-tab>
      </it4all-tabs>

    </div>
  </div>

</div>

// react-ui/src/collectionTools/tools/xml/XmlExercise.tsx
import {ConcreteExerciseIProps} from '../../Exercise';
import {ExerciseFileFragment, FilesSolution, useXmlCorrectionMutation, XmlExerciseContentFragment, XmlExPart, XmlSolutionInput} from '../../../graphql';
import {FilesExercise} from '../FilesExercise';
import {WithQuery} from '../../../WithQuery';
import {SolutionSaved} from '../../../helpers/SolutionSaved';
import {PointsNotification} from '../../../helpers/PointsNotification';
import {XmlDocumentResultDisplay} from './XmlDocumentResultDisplay';
import {XmlGrammarResultDisplay} from './XmlGrammarResultDisplay';
import {database} from '../../DexieTable';
import {WithNullableNavigate} from '../../../WithNullableNavigate';

type IProps = ConcreteExerciseIProps<XmlExerciseContentFragment, XmlSolutionInput>;

export function getXmlGrammarContent(rootNode: string): string {
  return `<!ELEMENT ${rootNode} (EMPTY)>`;
}

export function getXmlDocumentContent(rootNode: string): string {
  return `
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ${rootNode} SYSTEM "${rootNode}.dtd">
<${rootNode}>
</${rootNode}>`.trim();
}


export function XmlExercise({exercise, content, partId, oldSolution}: IProps): JSX.Element {

  const [correctExercise, correctionMutationResult] = useXmlCorrectionMutation();

  const part = partId === 'grammar' ? XmlExPart.GrammarCreationXmlPart : XmlExPart.DocumentCreationXmlPart;

  const isGrammarPart = part === XmlExPart.GrammarCreationXmlPart;

  const grammarFile = {
    name: `${content.rootNode}.dtd`,
    content: oldSolution
      ? oldSolution.grammar
      : (isGrammarPart ? getXmlGrammarContent(content.rootNode) : content.xmlSampleSolutions[0].grammar),
    fileType: 'dtd',
    editable: isGrammarPart,
  };

  const documentFile = {
    name: `${content.rootNode}.xml`,
    content: oldSolution?.document || getXmlDocumentContent(content.rootNode),
    fileType: 'xml',
    editable: !isGrammarPart,
  };

  const exerciseDescription = isGrammarPart
    ? <>
      <p className="has-text-weight-bold">Erstellen Sie eine DTD zu folgender Beschreibung:</p>
      <p>{content.grammarDescription}</p>
      <p className="is-italic has-text-info">
        Hinweis: Benutzen Sie die in Klammern angegebenen Element- bzw. Attributnamen. Falls nichts anderes
        angegeben ist, sollen die Elemente nur Text enthalten.
      </p>
    </>
    : <span>{exercise.text}</span>;

  function correct(files: ExerciseFileFragment[], onCorrect: () => void): void {
    const solution: XmlSolutionInput = {grammar: files[0].content, document: files[1].content};

    database.upsertSolution(exercise.toolId, exercise.collectionId, exercise.exerciseId, partId, solution);

    correctExercise({variables: {collId: exercise.collectionId, exId: exercise.exerciseId, solution, part}})
      .then(onCorrect)
      .catch((err) => console.error(err));
  }

  // FIXME: sample solutions!

  const sampleSolutions: FilesSolution[] = content.xmlSampleSolutions.map(({document, grammar}) => {
    return {
      files: [
        isGrammarPart
          ? {name: `${content.rootNode}.dtd`, content: grammar, fileType: 'dtd', editable: false}
          : {name: `${content.rootNode}.xml`, content: document, fileType: 'xml', editable: false}
      ]
    };
  });

  const correctionTabRender = (
    <WithQuery query={correctionMutationResult}>
      {({xmlExercise}) => <WithNullableNavigate t={xmlExercise}>
        {({correct: {solutionSaved, /*proficienciesUpdated, resultSaved,*/ result}}) => <>
          <SolutionSaved solutionSaved={solutionSaved}/>

          {isGrammarPart && <PointsNotification points={result.points} maxPoints={result.maxPoints}/>}

          {result.documentResult && <XmlDocumentResultDisplay result={result.documentResult}/>}

          {result.grammarResult && <XmlGrammarResultDisplay result={result.grammarResult}/>}

        </>}
      </WithNullableNavigate>}
    </WithQuery>
  );

  return <FilesExercise exerciseDescription={exerciseDescription} initialFiles={[grammarFile, documentFile]}
                        sampleSolutions={sampleSolutions} correct={correct} isCorrecting={correctionMutationResult.loading}
                        correctionTabRender={correctionTabRender}/>;
}
