// react-ui/src/collectionTools/tools/regex/RegexExercise.tsx
import React, {useState} from "react";
import {ExerciseSolveFieldsFragment, RegexExerciseContentFragment} from "../../../generated/graphql";
import {RegexCheatSheet} from './RegexCheatSheet';
import {BulmaTabs, TabConfig} from "../../../helpers/BulmaTabs";
import {useTranslation} from "react-i18next";
import {RegexCorrection} from './RegexCorrection';
import {StringSampleSolution} from "../StringSampleSolution";

interface IProps {
  exerciseFragment: ExerciseSolveFieldsFragment;
  contentFragment: RegexExerciseContentFragment;
}

export function RegexExercise({exerciseFragment, contentFragment}: IProps): JSX.Element {

  const {t} = useTranslation('common');
  const [showInfo, setShowInfo] = useState(false);
  const [showSampleSolutions, setShowSampleSolutions] = useState(false);

  function correct(): void {
    console.info('TODO'!);
  }

  const tabConfigs: TabConfig[] = [
    {id: 'correction', name: t('correction'), render: () => <RegexCorrection/>},
    {
      id: 'sampleSolutions', name: t('sampleSolution_plural'), render: () => <div>
        <div className="buttons">
          <button className="button is-primary is-fullwidth" onClick={() => setShowSampleSolutions((value) => !value)}>
            Musterlösungen {showSampleSolutions ? 'ausblenden' : 'anzeigen'}
          </button>
        </div>

        {showSampleSolutions && contentFragment.regexSampleSolutions.map((sample, index) => <StringSampleSolution sample={sample} key={index}/>)}
      </div>
    }
  ];

  return (
    <div className="container is-fluid">

      <div className="columns">
        <div className="column is-two-fifths-desktop">
          <h1 className="title is-3 has-text-centered">{t('exerciseText')}</h1>
          <div className="notification is-light-grey">{exerciseFragment.text}</div>

          <div className="field has-addons">
            <div className="control">
              <label className="button is-static" htmlFor="solution">Ihre Lösung:</label>
            </div>
            <div className="control is-expanded">
              {/* [(ngModel)]="solution" */}
              <input type="text" className="input" id="solution" placeholder="Ihre Lösung" autoFocus autoComplete="off"/>
            </div>
          </div>

          <div className="columns">
            <div className="column">
              <button className="button is-link is-fullwidth" onClick={correct}>Lösung testen</button>
            </div>
            <div className="column">
              {/* [routerLink]="['../..']" */}
              <a className="button is-dark is-fullwidth">Bearbeiten beenden</a>
            </div>
          </div>
          <div className="buttons">
            <button className="button is-info is-fullwidth" onClick={() => setShowInfo((value) => !value)}>
              Hilfe {showInfo ? 'ausblenden' : 'anzeigen'}
            </button>
          </div>

          {showInfo && <RegexCheatSheet/>}
        </div>

        <div className="column">
          <BulmaTabs tabs={tabConfigs}/>
          {/*    <it4all-tabs>

        <it4all-tab [title]="sampleSolutionsTabTitle">

        </it4all-tab>
      </it4all-tabs>
      */}
        </div>
      </div>
    </div>


  )

}

// ui/src/app/tools/collection-tools/regex/regex-exercise/regex-exercise.component.ts
import {Component, HostListener, Input, OnInit} from '@angular/core';
import {DexieService} from '../../../../_services/dexie.service';
import {ComponentWithExerciseDirective} from '../../_helpers/component-with-exercise.directive';
import {
  ExerciseSolveFieldsFragment,
  RegexAbstractResultFragment,
  RegexCorrectionGQL,
  RegexCorrectionMutation,
  RegexCorrectionMutationVariables,
  RegexCorrectionResultFragment,
  RegexExerciseContentFragment,
  RegexExPart,
  RegexExtractionResultFragment,
  RegexInternalErrorResultFragment,
  RegexMatchingResultFragment
} from '../../../../_services/apollo_services';
import {HasSampleSolutions} from "../../_helpers/correction-helpers";


function getIdForRegexExercisePart(regexExPart: RegexExPart): string {
  switch (regexExPart) {
    case RegexExPart.RegexSingleExPart:
      return 'regex';
  }
}

@Component({
  selector: 'it4all-regex-exercise',
  templateUrl: './regex-exercise.component.html'
})
export class RegexExerciseComponent
  extends ComponentWithExerciseDirective<string, RegexCorrectionMutation, RegexCorrectionMutationVariables>
  implements OnInit, HasSampleSolutions<string> {

  @Input() exerciseFragment: ExerciseSolveFieldsFragment;
  @Input() contentFragment: RegexExerciseContentFragment;

  solution = '';

  showInfo = false;

  readonly partId: string = getIdForRegexExercisePart(RegexExPart.RegexSingleExPart);

  constructor(regexCorrectionGQL: RegexCorrectionGQL, dexieService: DexieService) {
    super(regexCorrectionGQL, dexieService);
  }

  ngOnInit(): void {
    this.loadOldSolutionAbstract(this.exerciseFragment, this.partId, (oldSol) => this.solution = oldSol);
  }

  // Sample solutions

  displaySampleSolutions = false;

  toggleSampleSolutions() {
    this.displaySampleSolutions = !this.displaySampleSolutions;
  }

  get sampleSolutions(): string[] {
    return this.contentFragment.regexSampleSolutions;
  }

  // Correction

  protected getSolution(): string {
    return this.solution;
  }

  protected getMutationQueryVariables(): RegexCorrectionMutationVariables {
    return {
      exId: this.exerciseFragment.exerciseId,
      collId: this.exerciseFragment.collectionId,
      solution: this.getSolution(),
      part: RegexExPart.RegexSingleExPart,
    };
  }

  correct(): void {
    if (this.solution === undefined || this.solution.length === 0) {
      alert('Sie können keine leere Lösung abgeben!');
      return;
    }

    this.correctAbstract(this.exerciseFragment, this.partId);
  }

  // Results

  get correctionResult(): RegexCorrectionResultFragment | null {
    return this.resultQuery?.me.regexExercise?.correct;
  }

  get abstractResult(): RegexAbstractResultFragment & (RegexInternalErrorResultFragment | RegexMatchingResultFragment | RegexExtractionResultFragment) {
    return this.correctionResult?.result;
  }

  get regexInternalErrorResult(): RegexInternalErrorResultFragment | null {
    return this.abstractResult?.__typename === 'RegexInternalErrorResult' ? this.abstractResult : null;
  }

  get regexMatchingResult(): RegexMatchingResultFragment | null {
    return this.abstractResult?.__typename === 'RegexMatchingResult' ? this.abstractResult : null;
  }

  get regexExtractionResult(): RegexExtractionResultFragment | undefined {
    return this.abstractResult?.__typename === 'RegexExtractionResult' ? this.abstractResult : undefined;
  }

  // Other

  // FIXME: make directive?
  @HostListener('document:keypress', ['$event'])
  handleKeyboardEvent(event: KeyboardEvent): void {
    if (event.key === 'Enter') {
      // if (this.correct) {
      // this.update();
      // } else {
      this.correct();
      // }
    }
  }

}

<div class="container is-fluid">

  <div class="columns">
    <div class="column is-two-fifths-desktop">
      <h1 class="title is-3 has-text-centered">Aufgabenstellung</h1>
      <div class="notification is-light-grey">{{exerciseFragment.text}}</div>

      <div class="field has-addons">
        <div class="control">
          <label class="button is-static" for="solution">Ihre Lösung:</label>
        </div>
        <div class="control is-expanded">
          <input type="text" class="input" id="solution" [(ngModel)]="solution" placeholder="Ihre Lösung" autofocus
                 autocomplete="off">
        </div>
      </div>

      <div class="columns">
        <div class="column">
          <button class="button is-link is-fullwidth" (click)="correct()">Lösung testen</button>
        </div>
        <div class="column">
          <a [routerLink]="['../..']" class="button is-dark is-fullwidth">Bearbeiten beenden</a>
        </div>
      </div>
      <div class="buttons">
        <button (click)="showInfo = !showInfo;" class="button is-info is-fullwidth">
          Hilfe&nbsp;<span *ngIf="!showInfo">anzeigen</span><span *ngIf="showInfo">ausblenden</span>
        </button>
      </div>

      <it4all-regex-cheatsheet *ngIf="showInfo"></it4all-regex-cheatsheet>
    </div>

    <div class="column">
      <it4all-tabs>
        <it4all-tab [title]="correctionTabTitle">

          <div class="message is-danger" *ngIf="queryError">
            <div class="message-header">Fehler beim Parsen des regulären Ausdrucks:</div>
            <div class="message-body">
              <pre>{{queryError.message}}</pre>
            </div>
          </div>


          <ng-container *ngIf="resultQuery">

            <div class="my-3">
              <it4all-solution-saved *ngIf="correctionResult" [solutionSaved]="correctionResult.solutionSaved">
              </it4all-solution-saved>
            </div>


            <div class="my-3">
              <it4all-points-notification [points]="abstractResult.points" [maxPoints]="abstractResult.maxPoints">
              </it4all-points-notification>
            </div>

            <div class="columns is-multiline my-3" *ngIf="regexMatchingResult">
              <div class="column is-half-desktop" *ngFor="let matchingResult of regexMatchingResult.matchingResults">
                <it4all-regex-matching-result [matchingResult]="matchingResult"></it4all-regex-matching-result>
              </div>
            </div>

            <ng-container *ngIf="regexExtractionResult">
              <div class="my-3" *ngFor="let extractionResult of regexExtractionResult.extractionResults">
                <it4all-regex-extraction-result [extractionResult]="extractionResult"></it4all-regex-extraction-result>
              </div>
            </ng-container>

          </ng-container>
        </it4all-tab>

        <it4all-tab [title]="sampleSolutionsTabTitle">
          <div class="buttons">
            <button class="button is-primary is-fullwidth" (click)="toggleSampleSolutions()">
              Musterlösungen {{displaySampleSolutions ? 'ausblenden' : 'anzeigen'}}
            </button>
          </div>

          <ng-container *ngIf="displaySampleSolutions">
            <ng-container *ngFor="let sample of sampleSolutions; let last = last">
              <it4all-string-sample-sol [sample]="sample"></it4all-string-sample-sol>

              <br *ngIf="!last">
            </ng-container>
          </ng-container>
        </it4all-tab>
      </it4all-tabs>
    </div>
  </div>
</div>
