// ui/src/app/shared/breadcrumbs/breadcrumbs.component.ts
import {Component, Input} from '@angular/core';

export interface BreadCrumbPart {
  routerLinkPart: string;
  title: string;
}

interface BreadCrumb {
  routerLink: string;
  title: string;
}

@Component({
  selector: 'it4all-breadcrumbs',
  template: `
    <nav class="breadcrumb" aria-label="breadcrumbs">
      <ul>
        <li *ngFor="let part of breadCrumbs; let last = last" [class.is-active]="last">
          <a routerLink="{{part.routerLink}}">{{part.title}}</a>
        </li>
      </ul>
    </nav>
  `
})
export class BreadcrumbsComponent {

  @Input() parts: BreadCrumbPart[];

  get breadCrumbs(): BreadCrumb[] {
    let partAggregator: string[] = [];

    return this.parts.map(({routerLinkPart, title}) => {
      partAggregator.push(routerLinkPart);

      return {routerLink: partAggregator.join('/'), title};
    });
  }

}

// react-ui/src/helpers/BreadCrumbs.tsx
import React from 'react';
import {Link} from 'react-router-dom';
import classNames from 'classnames';

export interface BreadCrumbPart {
  routerLinkPart: string;
  title: string;
}

interface BreadCrumb {
  routerLink: string;
  title: string;
}

interface IProps {
  parts: BreadCrumbPart[];
}

export function BreadCrumbs({parts}: IProps): JSX.Element {

  function breadCrumbs(): BreadCrumb[] {
    const partAggregator: string[] = [];

    return parts.map(({routerLinkPart, title}) => {
      partAggregator.push(routerLinkPart);

      return {routerLink: partAggregator.join(''), title};
    });
  }

  return (
    <nav className="breadcrumb" aria-label="breadcrumbs">
      <ul>
        {breadCrumbs().map((part, index, arr) =>
          <li className={classNames({'is-active': index === arr.length - 1})} key={part.routerLink}>
            <Link to={part.routerLink}>{part.title}</Link>
          </li>
        )}
      </ul>
    </nav>
  );
}
