// client/src/app/tools/collection-tools/tool-helpers/points-notification/points-notification.component.ts
import {Component, Input, OnChanges, OnInit, SimpleChanges} from '@angular/core';

@Component({
  selector: 'app-points-notification',
  template: `
      <div class="notification has-text-{{textColor}}">
          <p class="has-text-centered">Sie haben {{points}} von maximal {{maxPoints}} Punkten erreicht.</p>

          <br>

          <progress class="progress is-{{textColor}}" value="{{percentage}}" max="100">{{percentage}}%</progress>
      </div>`,
})
export class PointsNotificationComponent implements OnInit, OnChanges {

  @Input() points: number;
  @Input() maxPoints: number;

  percentage: number;
  textColor = 'danger';

  constructor() {
  }

  ngOnInit() {
    this.updatePercentage();
  }

  ngOnChanges(changes: SimpleChanges): void {
    this.updatePercentage();
  }

   updatePercentage(): void {
    this.percentage = this.points / this.maxPoints * 100;


    if (this.percentage >= 90) {
      this.textColor = 'success';
    } else if (this.percentage >= 75) {
      this.textColor = 'warning';
    }

  }

}

// react-ui/src/helpers/PointsNotification.tsx
import React from "react";
import classNames from "classnames";

interface IProps {
  points: number;
  maxPoints: number;
}

function getTextColorForPercentage(percentage: number): string {
  if (percentage >= 90) {
    return 'has-text-dark-success';
  } else if (percentage >= 75) {
    return 'has-text-warning';
  } else {
    return 'has-text-danger';
  }
}

export function PointsNotification({points, maxPoints}: IProps): JSX.Element {

  const percentage = points / maxPoints * 100;

  const textColor = getTextColorForPercentage(percentage);

  return (
    <div className={classNames('notification', 'is-light-grey', textColor)}>
      <p className="has-text-centered">
        Sie haben {points} von maximal {maxPoints} Punkten erreicht.
      </p>

      <br/>

      <progress className="progress" value={percentage} max="100">{percentage}%</progress>
    </div>
  );

}
