// ui/src/app/shared/solution-saved/solution-saved.component.ts
import {Component, Input} from '@angular/core';

@Component({
  selector: 'it4all-solution-saved',
  template: `
    <div class="notification is-light-grey" [ngClass]="solutionSaved ? 'has-text-dark-success' : 'has-text-danger'">
      &#10004; Ihre Lösung wurde <span [innerHTML]="solutionSaved ? '' : '<b>nicht</b>'"></span> gespeichert.
    </div>`,
})
export class SolutionSavedComponent {

  @Input() solutionSaved: boolean;

}

// react-ui/src/helpers/SolutionSaved.tsx
import React from "react";
import classNames from "classnames";

export function SolutionSaved({solutionSaved}: { solutionSaved: boolean }): JSX.Element {
  return (
    <div className={classNames('notification', 'is-light-grey', solutionSaved ? 'has-text-dark-success' : 'has-text-danger')}>
      &#10004; Ihre Lösung wurde {solutionSaved ? '' : <b>nicht</b>} gespeichert.
    </div>
  );
}
