// react-ui/src/collectionTools/ExerciseLinkCard.tsx
import React from 'react';
import {FilledPoints} from '../helpers/FilledPoints';
import classNames from 'classnames';
import {BulmaCard} from '../helpers/BulmaCard';
import {FieldsForLinkFragment} from '../graphql';
import {collectionsUrlFragment, exercisesUrlFragment, toolsUrlFragment} from '../urls';
import {useTranslation} from 'react-i18next';

interface IProps {
  exercise: FieldsForLinkFragment;
}

export function ExerciseLinkCard({exercise}: IProps): JSX.Element {

  const {t} = useTranslation('common');

  const {toolId, collectionId, exerciseId, title, parts, difficulty, topicsWithLevels} = exercise;

  const cardTitle = <>
    {exerciseId}. {title}
    &nbsp;
    <div className="tag" title="Schwierigkeit">
      <FilledPoints filledPoints={difficulty} maxPoints={5}/>
    </div>
  </>;

  return (
    <BulmaCard title={cardTitle} footerItems={[{
      link: `/${toolsUrlFragment}/${toolId}/${collectionsUrlFragment}/${collectionId}/${exercisesUrlFragment}/${exerciseId}`,
      title: t('toExercise')
    }]}>
      <>

        <div className="tags">
          {parts.map(({id, name, solved}) =>
            <div key={id} className={classNames('tag', {'is-success': solved})}>{name}</div>
          )}
        </div>
        {topicsWithLevels.length > 0
          ? <div className="tags">
            {topicsWithLevels.map(({topic, level}) =>
              <div className="tag" title={topic.title} key={topic.abbreviation}>
                {topic.abbreviation}&nbsp; - &nbsp;
                <FilledPoints filledPoints={level.levelIndex} maxPoints={topic.maxLevel.levelIndex}/>
              </div>)}
          </div>
          : <div className="tag is-warning">Keine Tags vorhanden</div>}
      </>
    </BulmaCard>
  );
}

// ui/src/app/tools/collection-tools/_components/exercise-link-card/exercise-link-card.component.ts
import {Component, Input} from '@angular/core';
import {FieldsForLinkFragment} from '../../../../_services/apollo_services';

@Component({
  selector: 'it4all-exercise-link-card',
  template: `
    <div class="card">
      <header class="card-header">
        <div class="card-header-title">
          {{exercise.exerciseId}}. {{exercise.title}}
          &nbsp;
          <div class="tag" title="Schwierigkeit">
            <it4all-filled-points [filledPoints]="exercise.difficulty" maxPoints="5"></it4all-filled-points>
          </div>
        </div>
      </header>

      <div class="card-content">

        <div class="tags">
          <div class="tag" [class.is-success]="part.solved" *ngFor="let part of exercise.parts">{{part.name}}</div>
        </div>

        <div class="tags" *ngIf="exercise.topicsWithLevels.length > 0; else noTagsBlock">
          <div *ngFor="let topicWithLevel of exercise.topicsWithLevels" class="tag" [title]="topicWithLevel.topic">
            {{topicWithLevel.topic.abbreviation}}&nbsp; - &nbsp;
            <it4all-filled-points [filledPoints]="topicWithLevel.level.levelIndex" [maxPoints]="topicWithLevel.topic.maxLevel.levelIndex">
            </it4all-filled-points>
          </div>
        </div>

      </div>

      <footer class="card-footer">
        <a class="card-footer-item"
           [routerLink]="['/tools', exercise.toolId, 'collections', exercise.collectionId, 'exercises', exercise.exerciseId]">
          Zur Aufgabe
        </a>
      </footer>

    </div>

    <ng-template #noTagsBlock>
      <div class="tag is-warning">Keine Tags vorhanden</div>
    </ng-template>
  `
})
export class ExerciseLinkCardComponent {

  @Input() exercise: FieldsForLinkFragment;

}

<div class="card">
  <div class="card-header">
    <div class="card-header-title">{{exercise.exerciseId}}. {{exercise.title}}</div>
  </div>

  <div class="card-content">
    <div class="columns">
      <div class="column">Schwierigkeit:</div>
      <div class="column">
        <it4all-filled-points [filledPoints]="exercise.difficulty" maxPoints="5"></it4all-filled-points>
      </div>
    </div>

    <hr>

    <div class="columns" *ngFor="let topicWithLevel of exercise.topics">
      <div class="column">{{topicWithLevel.topic.title}}:</div>
      <div class="column">
        <it4all-filled-points
          [filledPoints]="topicWithLevel.level"
          [maxPoints]="topicWithLevel.topic.maxLevel"></it4all-filled-points>
      </div>
    </div>
  </div>

  <footer class="card-footer">
    <a class="card-footer-item"
       [routerLink]="['/tools', exercise.toolId, 'collections', exercise.collectionId, 'exercises', exercise.exerciseId]">
      Zur Aufgabe
    </a>
  </footer>

</div>
