// react-ui/src/randomTools/BoolFillOut.tsx
import React, {useState} from 'react';
import {BooleanFormula, generateBooleanFormula} from './bool/_model/bool-formula';
import {displayAssignmentValue, isCorrect, learnerVariable, sampleVariable} from './bool/_model/bool-component-helper';
import classNames from 'classnames';
import {RandomSolveButtons} from './RandomToolBase';
import {Assignment, BooleanNode, calculateAssignments} from './bool/_model/bool-node';

interface IState {
  formula: BooleanFormula;
  assignments: Assignment[];
  subFormulas: BooleanNode[];
  withSubFormulas: boolean;
  corrected: boolean;
}

function initState(withSubFormulas = false): IState {
  const formula = generateBooleanFormula(sampleVariable);

  const subFormulas = formula.getSubFormulas();

  const assignments = calculateAssignments(formula.getVariables());

  assignments.forEach((assignment) => {
    assignment.set(sampleVariable.variable, formula.evaluate(assignment));
    assignment.set(learnerVariable.variable, false);
  });

  return {formula, assignments, subFormulas, withSubFormulas, corrected: false};
}

export function BoolFillOut(): JSX.Element {

  const completelyCorrect = false;

  const [state, setState] = useState<IState>(initState());

  function updateAssignment(assignment: Assignment): void {
    // FIXME: use assignment...
    console.info(assignment);

    setState(({assignments, ...rest}) => {
      return {...rest, assignments};
    });
  }

  function correct(): void {
    setState((state) => ({...state, corrected: true}));
  }

  function nextExercise(): void {
    setState(initState());
  }

  return (
    <div className="columns">
      <div className="column is-half-desktop is-offset-one-quarter-desktop">

        {/*
      <!--      <div className="field">-->
      <!--        <div className="control has-text-centered">-->
      <!--          <label className="checkbox">-->
      <!--            <input type="checkbox" [(ngModel)]="withSubFormulas"> Mit Zwischenschritten-->
      <!--          </label>-->
      <!--        </div>-->
      <!--      </div>-->
      */}

        <div className="my-3">
          <h2 className="subtitle is-4 has-text-centered" dangerouslySetInnerHTML={{__html: `<code>${state.formula.asHtmlString()}</code>`}}/>
          <h3 className="subtitle is-5 has-text-centered has-text-grey">{state.formula.asString()}</h3>
        </div>

        <table className="table is-bordered is-fullwidth my-3">
          <thead>
            <tr>
              {state.formula.getVariables().map(({variable}) =>
                <th className="has-text-centered" key={variable}>{variable}</th>
              )}
              {state.withSubFormulas && state.subFormulas.map((subFormula) =>
                <th key={subFormula.asString()} className="has-text-centered">{subFormula.asHtmlString()}</th>
              )}
              <th className="has-text-centered">{learnerVariable.variable}</th>
            </tr>
          </thead>
          <tbody>
            {state.assignments.map((assignment, index) =>
              <tr key={index}>
                {state.formula.getVariables().map((variable) =>
                  <td className="has-text-centered" key={variable.variable}>{displayAssignmentValue(assignment, variable)}</td>
                )}
                {state.withSubFormulas && state.subFormulas.map((subFormula, index) =>
                  <th key={index}>{/* FIXME: button for subFormula... */}</th>)}

                <td className={classNames({
                  'has-background-danger': state.corrected && !isCorrect(assignment),
                  'has-background-success': state.corrected && isCorrect(assignment)
                }, 'has-text-centered')}>
                  <button onClick={() => updateAssignment(assignment)} className={classNames('button', {'is-link': assignment.get(learnerVariable.variable)})}>
                    {displayAssignmentValue(assignment, learnerVariable)}
                  </button>
                  &nbsp;
                  {state.corrected && (isCorrect(assignment) ? <span>&#10004;</span> : <span>&#10008;</span>)}
                </td>
              </tr>
            )}
          </tbody>
        </table>

        {state.corrected &&
        <div
          className={classNames('notification', 'has-text-centered', completelyCorrect ? 'is-success' : 'is-danger')}>
          (completelyCorrect
          ? <span>&#10004; Ihre Lösung ist korrekt.</span>
          : <span>&#10008; Ihre Lösung ist nicht (komplett) korrekt.</span>)
        </div>}

        <RandomSolveButtons correct={correct} nextExercise={nextExercise}/>
      </div>
    </div>
  );
}

// ui/src/app/tools/random-tools/bool/bool-fill-out/bool-fill-out.component.ts
import {Component, HostListener, OnInit} from '@angular/core';
import {BoolComponentHelper} from '../_model/bool-component-helper';
import {BooleanNode, calculateAssignments} from '../_model/bool-node';
import {generateBooleanFormula} from '../_model/bool-formula';

@Component({
  selector: 'it4all-bool-fillout',
  templateUrl: './bool-fill-out.component.html'
})
export class BoolFillOutComponent extends BoolComponentHelper implements OnInit {

  withSubFormulas = false;
  subFormulas: BooleanNode[] = [];

  ngOnInit(): void {
    this.update();
  }

  update(): void {
    this.completelyCorrect = false;
    this.corrected = false;

    this.formula = generateBooleanFormula(this.sampleVariable);
    this.assignments = calculateAssignments(this.formula.getVariables());
    this.subFormulas = this.formula.getSubFormulas();

    this.assignments.forEach((assignment) => {
      assignment.set(this.sampleVariable.variable, this.formula.evaluate(assignment));
      assignment.set(this.learnerVariable.variable, false);
    });
  }

  correct(): void {
    this.corrected = true;

    this.completelyCorrect = this.assignments.every((a) => this.isCorrect(a));
  }

  updateAssignment(assignment: Map<string, boolean>): void {
    for (const as of this.assignments) {
      if (as === assignment) {
        const newValue = !as.get(this.learnerVariable.variable);
        as.set(this.learnerVariable.variable, newValue);
      }
    }

    if (this.corrected) {
      this.correct();
    }
  }

  @HostListener('document:keypress', ['$event'])
  handleKeyboardEvent(event: KeyboardEvent): void {
    if (event.key === 'Enter') {
      if (this.completelyCorrect) {
        this.update();
      } else {
        this.corrected = true;
      }
    }
  }

}

<div class="columns">
  <div class="column is-half-desktop is-offset-one-quarter-desktop">

    <!--      <div class="field">-->
    <!--        <div class="control has-text-centered">-->
    <!--          <label class="checkbox">-->
    <!--            <input type="checkbox" [(ngModel)]="withSubFormulas"> Mit Zwischenschritten-->
    <!--          </label>-->
    <!--        </div>-->
    <!--      </div>-->

    <br>

    <h2 class="subtitle is-4 has-text-centered"><code [innerHTML]="formula.asHtmlString()"></code></h2>
    <h3 class="subtitle is-5 has-text-centered has-text-grey">{{formula.asString()}}</h3>

    <br>

    <table class="table is-bordered is-fullwidth">
      <thead>
        <tr>
          <th class="has-text-centered" *ngFor="let variable of formula.getVariables()">{{variable.variable}}</th>
          <ng-container *ngIf="withSubFormulas">
            <th class="has-text-centered" *ngFor="let subFormula of subFormulas"
                [innerHTML]="subFormula.asHtmlString()"></th>
          </ng-container>
          <th class="has-text-centered">{{learnerVariable.variable}}</th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let assignment of assignments">
          <td class="has-text-centered"
              *ngFor="let variable of formula.getVariables()">{{displayAssignmentValue(assignment, variable) }}</td>
          <ng-container *ngIf="withSubFormulas">
            <th *ngFor="let subFormula of subFormulas">
              <!-- FIXME: button for subFormula... -->
            </th>
          </ng-container>
          <td [class.has-background-danger]="corrected && !isCorrect(assignment)"
              [class.has-background-success]="corrected && isCorrect(assignment)"
              class="has-text-centered">
            <button (click)="updateAssignment(assignment)" class="button"
                    [class.is-link]="assignment.get(this.learnerVariable.variable)">
              {{displayAssignmentValue(assignment, this.learnerVariable)}}
            </button>
            &nbsp;
            <span *ngIf="corrected && isCorrect(assignment)">&#10004;</span>
            <span *ngIf="corrected && !isCorrect(assignment)">&#10008;</span>
          </td>
        </tr>
      </tbody>
    </table>

    <div class="notification has-text-centered is-danger" *ngIf="corrected && !completelyCorrect">
      &#10008; Ihre Lösung ist nicht (komplett) korrekt.
    </div>
    <div class="notification has-text-centered is-success" *ngIf="corrected && completelyCorrect">
      &#10004; Ihre Lösung ist korrekt.
    </div>

    <it4all-random-solve-buttons
      (correctEmitter)="correct()"
      (nextEmitter)="update()">
    </it4all-random-solve-buttons>
  </div>
</div>
