// ui/src/app/tools/collection-tools/all-exercises-overview/all-exercises-overview.component.ts
import {Component, OnDestroy, OnInit} from '@angular/core';
import {ActivatedRoute} from '@angular/router';
import {distinctObjectArray, flatMapArray} from '../../../helpers';
import {
  AllExercisesOverviewGQL,
  AllExercisesOverviewQuery,
  FieldsForLinkFragment,
  TopicFragment,
  TopicWithLevelFragment
} from "../../../_services/apollo_services";
import {Subscription} from "rxjs";

@Component({templateUrl: './all-exercises-overview.component.html'})
export class AllExercisesOverviewComponent implements OnInit, OnDestroy {

  private sub: Subscription;
  allExercisesOverviewQuery: AllExercisesOverviewQuery;

  distinctTopicWithLevels: TopicWithLevelFragment[];
  filteredExercises: FieldsForLinkFragment[];
  filtersActivated: Map<TopicFragment, boolean> = new Map();

  constructor(private route: ActivatedRoute, private allExercisesOverviewGQL: AllExercisesOverviewGQL) {
  }

  ngOnInit() {
    this.sub = this.route.paramMap.subscribe((paramMap) => {
      const toolId = paramMap.get('toolId');

      this.allExercisesOverviewGQL
        .watch({toolId})
        .valueChanges
        .subscribe(({data}) => {
          this.allExercisesOverviewQuery = data;

          this.filteredExercises = this.allExercisesOverviewQuery.tool.allExercises;

          this.distinctTopicWithLevels = distinctObjectArray(
            flatMapArray(
              this.allExercisesOverviewQuery.tool.allExercises,
              (exercises) => exercises.topics
            ),
            (t) => t.topic.abbreviation
          );
        });
    });
  }

  ngOnDestroy(): void {
    this.sub.unsubscribe();
  }

  toggleFilter(topicWithLevel: TopicWithLevelFragment): void {
    this.filtersActivated.set(topicWithLevel.topic, !this.filtersActivated.get(topicWithLevel.topic));

    const activatedFilters: TopicFragment[] = Array.from(this.filtersActivated.entries())
      .filter(([_, activated]) => activated)
      .map(([t, _]) => t);

    if (activatedFilters.length > 0) {
      this.filteredExercises = this.allExercisesOverviewQuery.tool.allExercises
        .filter((metaData) => activatedFilters.every((t) => this.exerciseHasTag(metaData, t)));
    } else {
      this.filteredExercises = this.allExercisesOverviewQuery.tool.allExercises;
    }
  }

  exerciseHasTag(exercise: FieldsForLinkFragment, tag: TopicFragment): boolean {
    return exercise.topics
      .map((t) => t.topic.abbreviation)
      .includes(tag.abbreviation);
  }


}

<div class="container">
  <ng-container *ngIf="allExercisesOverviewQuery; else loadingExercisesBlock">

    <section>
      <h2 class="title is-3 has-text-centered">Filter</h2>

      <div class="columns is-multiline">
        <div class="column" *ngFor="let topicWithLevel of distinctTopicWithLevels">
          <button class="button is-fullwidth" [class.is-link]="filtersActivated.get(topicWithLevel.topic)"
                  (click)="toggleFilter(topicWithLevel)">
            {{topicWithLevel.topic.title}}
          </button>
        </div>
      </div>
    </section>

    <hr>

    <h1 class="title is-3 has-text-centered">Alle Aufgaben</h1>

    <div class="columns is-multiline">
      <div class="column is-one-quarter-desktop" *ngFor="let metaData of filteredExercises">
        <it4all-exercise-link-card [exercise]="metaData"></it4all-exercise-link-card>
      </div>
    </div>

  </ng-container>
</div>


<ng-template #loadingExercisesBlock>
  <div class="notification is-primary has-text-centered">Lade Aufgaben...</div>
</ng-template>

// react-ui/src/collectionTools/AllExercisesOverview.tsx
import React, {useState} from 'react';
import {AllExercisesOverviewQuery, useAllExercisesOverviewQuery} from '../graphql';
import {Redirect} from 'react-router-dom';
import {homeUrl} from '../urls';
import {WithQuery} from '../WithQuery';
import {useTranslation} from 'react-i18next';
import {distinctObjectArray} from './tools/uml/UmlMemberAllocation';
import classNames from 'classnames';
import {ExerciseLinkCard} from './ExerciseLinkCard';

interface IProps {
  toolId: string;
}

export function AllExercisesOverview({toolId}: IProps): JSX.Element {

  const {t} = useTranslation('common');
  const allExercisesOverviewQuery = useAllExercisesOverviewQuery({variables: {toolId}});
  const [filterAbbreviationsActivated, setFilterAbbreviationsActivated] = useState<string[]>([]);

  function render({tool}: AllExercisesOverviewQuery): JSX.Element {
    if (!tool) {
      return <Redirect to={homeUrl}/>;
    }

    const {name, allExercises} = tool;

    const distinctTopicWithLevels = distinctObjectArray(
      allExercises.flatMap((exercises) => exercises.topicsWithLevels),
      (t) => t.topic.abbreviation
    );

    const filteredExercises = filterAbbreviationsActivated.length > 0
      ? allExercises.filter((exercise) => filterAbbreviationsActivated.every((topicAbb) => exercise.topicsWithLevels.map(({topic}) => topic.abbreviation).includes(topicAbb)))
      : allExercises;

    function toggleFilter(topicWithLevelAbbreviation: string): void {
      setFilterAbbreviationsActivated((filters) => filters.includes(topicWithLevelAbbreviation)
        ? filters.filter((s) => s !== topicWithLevelAbbreviation)
        : [...filters, topicWithLevelAbbreviation]
      );
    }

    return (
      <>
        <h1 className="title is-3 has-text-centered">{t('tool')} {name}: {t('allExercises')}</h1>

        <section>
          <h2 className="title is-3 has-text-centered">Filter</h2>

          <div className="columns is-multiline">
            {distinctTopicWithLevels.map((topicWithLevel) =>
              <div className="column is-one-fifth" key={topicWithLevel.topic.abbreviation}>
                <button className={classNames('button', 'is-fullwidth', {'is-link': filterAbbreviationsActivated.includes(topicWithLevel.topic.abbreviation)})}
                        onClick={() => toggleFilter(topicWithLevel.topic.abbreviation)}>
                  {topicWithLevel.topic.title}
                </button>
              </div>)}
          </div>
        </section>

        <hr/>

        <h1 className="title is-3 has-text-centered">Alle Aufgaben</h1>

        <div className="columns is-multiline">
          {filteredExercises.map((exercise) => <div className="column is-one-third-desktop" key={exercise.title}>
            <ExerciseLinkCard exercise={exercise}/>
          </div>)}
        </div>
      </>
    );
  }

  return (
    <div className="container">
      <WithQuery query={allExercisesOverviewQuery} render={render}/>
    </div>
  );
}
