// ui/src/app/tools/collection-tools/collection-overview/collection-overview.component.ts
import {Component, OnDestroy, OnInit} from '@angular/core';
import {ActivatedRoute} from '@angular/router';
import {
  CollectionOverviewGQL,
  CollectionOverviewQuery,
  CollOverviewToolFragment,
  FieldsForLinkFragment
} from '../../../_services/apollo_services';
import {Subscription} from 'rxjs';
import {AuthenticationService} from '../../../_services/authentication.service';
import {BreadCrumbPart} from "../../../shared/breadcrumbs/breadcrumbs.component";

const SLICE_COUNT: number = 12;

// url => /tools/:toolId/collections/:collId

@Component({templateUrl: './collection-overview.component.html'})
export class CollectionOverviewComponent implements OnInit, OnDestroy {

  private sub: Subscription;

  collectionOverviewQuery: CollectionOverviewQuery;

  paginationNeeded = false;

  maxPage = 0;
  currentPage = 0;

  pages: number[] = [];

  constructor(
    private authenticationService: AuthenticationService,
    private route: ActivatedRoute,
    private collectionOverviewGQL: CollectionOverviewGQL
  ) {
  }

  ngOnInit() {
    const userJwt = this.authenticationService.currentUserValue.jwt;

    this.sub = this.route.paramMap.subscribe((paramMap) => {
      const toolId: string = paramMap.get('toolId');
      const collId: number = parseInt(paramMap.get('collId'), 10);

      this.collectionOverviewGQL
        .watch({userJwt, toolId, collId})
        .valueChanges
        .subscribe(({data}) => {
          this.collectionOverviewQuery = data;

          this.paginationNeeded = this.exercises.length > SLICE_COUNT;

          this.maxPage = Math.ceil(this.collectionOverviewQuery.me.tool.collection.exercises.length / SLICE_COUNT);

          this.pages = Array(this.maxPage).fill(0).map((value, index) => index);
        });
    });
  }

  ngOnDestroy(): void {
    this.sub.unsubscribe();
  }

  get tool(): CollOverviewToolFragment {
    return this.collectionOverviewQuery.me.tool;
  }

  get exercises(): FieldsForLinkFragment[] {
    return this.tool.collection.exercises;
  }

  getExercisesPaginated(): FieldsForLinkFragment[] {
    return this.exercises.slice(this.currentPage * SLICE_COUNT, (this.currentPage + 1) * SLICE_COUNT);
  }

  get breadCrumbs(): BreadCrumbPart[] {
    return [
      {routerLinkPart: '/', title: 'Tools'},
      {routerLinkPart: `tools/${this.tool.id}`, title: this.tool.name},
      {routerLinkPart: 'collections', title: 'Sammlungen'},
      {routerLinkPart: this.tool.collection.collectionId.toString(), title: this.tool.collection.title}
    ]
  }

}

<div class="container">

  <ng-container *ngIf="collection; else loadingCollectionBlock">
    <h1 class="title is-3 has-text-centered">Sammlung &quot;{{collection.title}}&quot;</h1>

    <div class="buttons">
      <a class="button is-primary is-fullwidth" [routerLink]="['../..']">Zurück zur Sammlungübersicht</a>
    </div>

    <br>

    <ng-container *ngIf="collection">
      <h2 class="subtitle is-3 has-text-centered">Aufgaben</h2>

      <ng-container *ngIf="collection.exercises; else loadingExercisesBlock">
        <div class="columns is-multiline" *ngIf="collection.exercises.length > 0; else noExercisesFoundBlock">
          <div *ngFor="let exercise of collection.exercises" class="column is-one-quarter-desktop is-half">

            <div class="card">
              <div class="card-header">
                <div class="card-header-title">{{exercise.id}}. {{exercise.title}}</div>
              </div>
              <div class="card-content">

                <!-- Tags -->
                <div class="buttons" *ngIf="exercise.tags">
                  <span *ngIf="exercise.tags.length === 0">&nbsp;</span>
                  <it4all-tag *ngFor="let tag of exercise.tags" [tag]="tag"></it4all-tag>
                </div>

              </div>
              <footer class="card-footer">
                <a class="card-footer-item" [routerLink]="['exercises', exercise.id]">Zur Aufgabe</a>
              </footer>
            </div>

          </div>
        </div>
      </ng-container>
    </ng-container>

    <ng-template #noExercisesFoundBlock>
      <div class="notification is-danger has-text-centered">
        Es konnten keine Aufgaben für die Sammlung {{collection.title}} gefunden werden!
      </div>
    </ng-template>

    <ng-template #loadingExercisesBlock>
      <div class="notification">
        <p class="has-text-centered">Lade Aufgaben...</p>
        <br>
        <progress class="progress" max="100">20%</progress>
      </div>
    </ng-template>

  </ng-container>
  <ng-template #loadingCollectionBlock>
    <div class="notification is-danger has-text-centered">
      Lade Sammlung...
    </div>
  </ng-template>

</div>

// react-ui/src/collectionTools/CollectionOverview.tsx
import React, {useState} from 'react';
import {CollectionBaseParams} from '../ToolBase';
import {useTranslation} from 'react-i18next';
import {CollectionOverviewQuery, FieldsForLinkFragment, useCollectionOverviewQuery} from '../graphql';
import {BreadCrumbPart, BreadCrumbs} from '../helpers/BreadCrumbs';
import {Redirect} from 'react-router-dom';
import {WithQuery} from '../WithQuery';
import classNames from 'classnames';
import {ExerciseLinkCard} from './ExerciseLinkCard';

const SLICE_COUNT = 12;

export function CollectionOverview({toolId, collectionId}: CollectionBaseParams): JSX.Element {

  const {t} = useTranslation('common');
  const query = useCollectionOverviewQuery({variables: {toolId, collId: collectionId}});
  const [currentPage, setCurrentPage] = useState(0);

  function render({tool}: CollectionOverviewQuery): JSX.Element {
    if (!tool) {
      return <Redirect to={''}/>;
    }

    const {name: toolName, collection} = tool;

    if (!collection) {
      return <Redirect to={''}/>;
    }

    const {title, exercises} = collection;

    const paginationNeeded = exercises.length > SLICE_COUNT;
    const maxPage = Math.ceil(exercises.length / SLICE_COUNT);
    const pages: number[] = Array(maxPage).fill(0).map((value, index) => index);

    function getExercisesPaginated(): FieldsForLinkFragment[] {
      return exercises.slice(currentPage * SLICE_COUNT, (currentPage + 1) * SLICE_COUNT);
    }

    const breadCrumbs: BreadCrumbPart[] = [
      {routerLinkPart: '/', title: 'Tools'},
      {routerLinkPart: `tools/${toolId}`, title: toolName},
      {routerLinkPart: 'collections', title: 'Sammlungen'},
      {routerLinkPart: collectionId.toString(), title: title}
    ];

    return <div className="container">
      <h1 className="title is-3 has-text-centered">{t('collection')} &quot;{title}&quot; - {t('exercise_plural')}</h1>

      <div className="mb-3">
        <BreadCrumbs parts={breadCrumbs}/>
      </div>

      {paginationNeeded && <nav className="pagination is-centered" role="navigation" aria-label="pagination">
        <button className="button pagination-previous" onClick={() => setCurrentPage(currentPage - 1)} disabled={currentPage < 1}>
          {t('previous')}
        </button>
        <ul className="pagination-list">
          {pages.map((page) => <li key={page}>
            <button className={classNames('button', 'pagination-link', {'is-current': page === currentPage})} onClick={() => setCurrentPage(page)}>
              {page}
            </button>
          </li>)}
        </ul>
        <button className="button pagination-next" onClick={() => setCurrentPage(currentPage + 1)} disabled={currentPage >= maxPage - 1}>
          {t('next')}
        </button>
      </nav>}

      {exercises.length > 0
        ? <div className="columns is-multiline">
          {getExercisesPaginated().map((exercise) =>
            <div className="column is-one-third-desktop is-half" key={exercise.exerciseId}>
              <ExerciseLinkCard exercise={exercise}/>
            </div>
          )}
        </div>
        : <div className="notification is-danger has-text-centered">{t('noExercisesFound')}</div>}

    </div>;


  }

  return <WithQuery query={query} render={render}/>;
}
