// ui/src/app/tools/collection-tools/exercise/exercise.component.ts
import {Component, OnDestroy, OnInit} from '@angular/core';
import {ActivatedRoute} from '@angular/router';
import {
  ExerciseGQL,
  ExerciseQuery,
  ExerciseSolveFieldsFragment,
  FlaskExerciseContentFragment,
  ProgrammingExerciseContentFragment,
  RegexExerciseContentFragment,
  SqlExerciseContentFragment,
  UmlExerciseContentFragment,
  WebExerciseContentFragment,
  XmlExerciseContentFragment
} from '../../../_services/apollo_services';
import {Subscription} from 'rxjs';


@Component({templateUrl: './exercise.component.html'})
export class ExerciseComponent implements OnInit, OnDestroy {

  private sub: Subscription;
  private apolloSub: Subscription;

  exerciseQuery: ExerciseQuery;

  constructor(private route: ActivatedRoute, private exerciseGQL: ExerciseGQL) {
  }

  ngOnInit() {
    this.sub = this.route.paramMap.subscribe((paramMap) => {
      const toolId = paramMap.get('toolId');
      const collId = parseInt(paramMap.get('collId'), 10);
      const exId = parseInt(paramMap.get('exId'), 10);
      const partId = paramMap.get('partId');

      this.apolloSub = this.exerciseGQL
        .watch({toolId, collId, exId, partId})
        .valueChanges
        .subscribe(({data}) => this.exerciseQuery = data);
    });
  }

  ngOnDestroy(): void {
    this.apolloSub.unsubscribe();
    this.sub.unsubscribe();
  }

  // Exercise content

  get exercise(): ExerciseSolveFieldsFragment {
    return this.exerciseQuery.me.tool.collection.exercise;
  }

  get flaskExerciseContent(): FlaskExerciseContentFragment | null {
    return this.exercise.content.__typename === 'FlaskExerciseContent' ? this.exercise.content : null;
  }

  get programmingExerciseContent(): ProgrammingExerciseContentFragment | null {
    return this.exercise.content.__typename === 'ProgrammingExerciseContent' ? this.exercise.content : null;
  }

  get regexExerciseContent(): RegexExerciseContentFragment | null {
    return this.exercise.content.__typename === 'RegexExerciseContent' ? this.exercise.content : null;
  }

  get sqlExerciseContent(): SqlExerciseContentFragment | null {
    return this.exercise.content.__typename === 'SqlExerciseContent' ? this.exercise.content : null;
  }

  get umlExerciseContent(): UmlExerciseContentFragment | null {
    return this.exercise.content.__typename === 'UmlExerciseContent' ? this.exercise.content : null;
  }

  get webExerciseContent(): WebExerciseContentFragment | null {
    return this.exercise.content.__typename === 'WebExerciseContent' ? this.exercise.content : null;
  }

  get xmlExerciseContent(): XmlExerciseContentFragment | null {
    return this.exercise.content.__typename === 'XmlExerciseContent' ? this.exercise.content : null;
  }

}

<ng-container *ngIf=" exerciseQuery; else loadingDataBlock">

  <it4all-ebnf-exercise
    *ngIf="ebnfExerciseContent"
    [exerciseFragment]="exercise"
    [contentFragment]="ebnfExerciseContent">
  </it4all-ebnf-exercise>

  <it4all-flask-exercise
    *ngIf="flaskExerciseContent"
    [exerciseFragment]="exercise"
    [contentFragment]="flaskExerciseContent">
  </it4all-flask-exercise>

  <it4all-programming-exercise
    *ngIf="programmingExerciseContent"
    [exerciseFragment]="exercise"
    [contentFragment]="programmingExerciseContent">
  </it4all-programming-exercise>

  <it4all-regex-exercise
    *ngIf="regexExerciseContent"
    [exerciseFragment]="exercise"
    [contentFragment]="regexExerciseContent">
  </it4all-regex-exercise>

  <it4all-sql-exercise
    *ngIf="sqlExerciseContent"
    [exerciseFragment]="exercise"
    [contentFragment]="sqlExerciseContent">
  </it4all-sql-exercise>

  <it4all-uml-exercise
    *ngIf="umlExerciseContent"
    [exerciseFragment]="exercise"
    [contentFragment]="umlExerciseContent">
  </it4all-uml-exercise>

  <it4all-web-exercise
    *ngIf="webExerciseContent"
    [exerciseFragment]="exercise"
    [contentFragment]="webExerciseContent">
  </it4all-web-exercise>

  <it4all-xml-exercise
    *ngIf="xmlExerciseContent"
    [exerciseFragment]="exercise"
    [contentFragment]="xmlExerciseContent">
  </it4all-xml-exercise>

</ng-container>

<ng-template #loadingDataBlock>
  <div class="notification is-primary has-text-centered">Lade Aufgabe...</div>
</ng-template>

// react-ui/src/collectionTools/Exercise.tsx
import React, {useEffect, useState} from 'react';
import {ExerciseIProps} from '../ToolBase';
import {Redirect, useRouteMatch} from 'react-router-dom';
import {ExerciseQuery, ExerciseSolveFieldsFragment, FilesSolutionInput, useExerciseQuery, XmlSolutionInput} from '../graphql';
import {WithQuery} from '../WithQuery';
import {EbnfExercise} from './tools/ebnf/EbnfExercise';
import {RegexExercise} from './tools/regex/RegexExercise';
import {SqlExercise} from './tools/sql/SqlExercise';
import {ProgrammingExercise} from './tools/programming/ProgrammingExercise';
import {WebExercise} from './tools/web/WebExercise';
import {XmlExercise} from './tools/xml/XmlExercise';
import {FlaskExercise} from './tools/flask/FlaskExercise';
import {database} from './DexieTable';
import {useTranslation} from 'react-i18next';
import {UmlExercise} from './tools/uml/UmlExercise';
import {neverRender} from '../helpers';
import {UmlDbClassDiagram} from './tools/uml/UmlDiagramDrawing';

export interface ConcreteExerciseIProps<T, S> {
  exercise: ExerciseSolveFieldsFragment;
  content: T;
  partId: string;
  oldSolution?: S;
}

interface IState<S> {
  oldSolutionLoaded: boolean;
  oldSolution?: S;
}

export function Exercise<SolutionType>({toolId, collectionId, exerciseId}: ExerciseIProps): JSX.Element {

  const {t} = useTranslation('common');
  const partId = useRouteMatch<{ partId: string }>().params.partId;
  const [state, setState] = useState<IState<SolutionType>>({oldSolutionLoaded: false});
  const exerciseQuery = useExerciseQuery({variables: {toolId, collectionId, exerciseId, partId}});

  useEffect(() => {
    database.getSolution<SolutionType>(toolId, collectionId, exerciseId, partId)
      .then((oldSolution) => setState({oldSolutionLoaded: true, oldSolution: oldSolution?.solution}));
  }, [partId]);

  function render({tool}: ExerciseQuery): JSX.Element {

    if (!tool) {
      return <Redirect to={''}/>;
    }

    const collection = tool.collection;

    if (!collection) {
      return <Redirect to={''}/>;
    }

    const exercise = collection.exercise;

    if (!exercise) {
      return <Redirect to={''}/>;
    }

    const content = exercise.content;

    if (!state.oldSolutionLoaded) {
      return <div className="notification is-primary has-text-centered">{t('loadingOldSolution')}...</div>;
    }

    if (content.__typename === 'EbnfExerciseContent') {
      return <EbnfExercise exercise={exercise} content={content} partId={partId} oldSolution={state.oldSolution as string | undefined}/>;
    } else if (content.__typename === 'FlaskExerciseContent') {
      return <FlaskExercise exercise={exercise} content={content} partId={partId} oldSolution={state.oldSolution as FilesSolutionInput | undefined}/>;
    } else if (content.__typename === 'ProgrammingExerciseContent') {
      return <ProgrammingExercise exercise={exercise} content={content} partId={partId} oldSolution={state.oldSolution as FilesSolutionInput | undefined}/>;
    } else if (content.__typename === 'RegexExerciseContent') {
      return <RegexExercise exercise={exercise} content={content} partId={partId} oldSolution={state.oldSolution as string | undefined}/>;
    } else if (content.__typename === 'SqlExerciseContent') {
      return <SqlExercise exercise={exercise} content={content} partId={partId} oldSolution={state.oldSolution as string | undefined}/>;
    } else if (content.__typename === 'UmlExerciseContent') {
      return <UmlExercise exercise={exercise} content={content} partId={partId} oldSolution={state.oldSolution as UmlDbClassDiagram | undefined}/>;
    } else if (content.__typename === 'WebExerciseContent') {
      return <WebExercise exercise={exercise} content={content} partId={partId} oldSolution={state.oldSolution as FilesSolutionInput | undefined}/>;
    } else if (content.__typename === 'XmlExerciseContent') {
      return <XmlExercise exercise={exercise} content={content} partId={partId} oldSolution={state.oldSolution as XmlSolutionInput | undefined}/>;
    } else {
      return neverRender(content);
    }
  }

  return <WithQuery query={exerciseQuery} render={render}/>;

}
