// ui/src/app/tools/collection-tools/exercise-overview/exercise-overview.component.ts
import {Component, OnDestroy, OnInit} from '@angular/core';
import {ActivatedRoute} from '@angular/router';
import {
  ExerciseOverviewFragment,
  ExerciseOverviewGQL,
  ExerciseOverviewQuery,
  PartFragment
} from '../../../_services/apollo_services';
import {Subscription} from 'rxjs';
import {AuthenticationService} from '../../../_services/authentication.service';
import {BreadCrumbPart} from "../../../shared/breadcrumbs/breadcrumbs.component";

@Component({templateUrl: './exercise-overview.component.html'})
export class ExerciseOverviewComponent implements OnInit, OnDestroy {

  private sub: Subscription;
  private exerciseOverviewQuery: ExerciseOverviewQuery;

  constructor(
    private authenticationService: AuthenticationService,
    private route: ActivatedRoute,
    private exerciseOverviewGQL: ExerciseOverviewGQL
  ) {
  }

  ngOnInit() {
    const userJwt = this.authenticationService.currentUserValue.jwt;

    this.sub = this.route.paramMap.subscribe((paramMap) => {
      const toolId = paramMap.get('toolId');
      const collId = parseInt(paramMap.get('collId'), 10);
      const exId = parseInt(paramMap.get('exId'), 10);

      this.exerciseOverviewGQL
        .watch({userJwt, toolId, collId, exId})
        .valueChanges
        .subscribe(({data}) => this.exerciseOverviewQuery = data);
    });
  }

  ngOnDestroy(): void {
    this.sub.unsubscribe();
  }

  private getTool() {
    return this.exerciseOverviewQuery?.me.tool;
  }

  get exercise(): ExerciseOverviewFragment | undefined {
    return this.exerciseOverviewQuery?.me.tool.collection.exercise;
  }

  get entryParts(): PartFragment[] {
    return this.exercise.parts.filter((p) => p.isEntryPart);
  }

  get breadCrumbs(): BreadCrumbPart[] {
    return [
      {routerLinkPart: '/', title: 'Tools'},
      {routerLinkPart: `tools/${this.getTool().id}`, title: this.getTool().name},
      {routerLinkPart: 'collections', title: 'Sammlungen'},
      {routerLinkPart: this.getTool().collection.collectionId.toString(), title: this.getTool().collection.title},
      {routerLinkPart: 'exercises', title: 'Aufgaben'},
      {routerLinkPart: this.exercise.exerciseId.toString(), title: this.exercise.exerciseId.toString()}
    ]
  }

}

<div class="container">
  <ng-container *ngIf="exercise; else loadingDataBlock">

    <h1 class="title is-3 has-text-centered">Aufgabe &quot;{{exercise.title}}&quot;</h1>

    <div class="my-3">
      <it4all-breadcrumbs [parts]="breadCrumbs"></it4all-breadcrumbs>
    </div>

    <div class="notification is-light-grey" [innerHTML]="exercise.text"></div>

    <div class="columns">
      <div class="column" *ngFor="let part of entryParts">
        <a class="button is-link is-fullwidth" [routerLink]="['parts', part.id]">{{part.name}}</a>
      </div>
    </div>

  </ng-container>
</div>

<ng-template #loadingDataBlock>
  <div class="notification is-primary has-text-centered">Lade Daten...</div>
</ng-template>

// react-ui/src/collectionTools/ExerciseOverview.tsx
import React from 'react';
import {ExerciseOverviewQuery, PartFragment, useExerciseOverviewQuery} from '../graphql';
import {ExerciseIProps} from '../ToolBase';
import {Link, Redirect, useRouteMatch} from 'react-router-dom';
import {BreadCrumbPart, BreadCrumbs} from '../helpers/BreadCrumbs';
import {WithQuery} from '../WithQuery';

export function ExerciseOverview({toolId, collectionId, exerciseId}: ExerciseIProps): JSX.Element {

  const {url} = useRouteMatch();

  const exerciseOverviewQuery = useExerciseOverviewQuery({variables: {toolId, collectionId, exerciseId}});

  function render({me}: ExerciseOverviewQuery): JSX.Element {
    if (!me || !me.tool || !me.tool.collection || !me.tool.collection.exercise) {
      return <Redirect to={'/'}/>;
    }

    const tool = me.tool;
    const collection = me.tool.collection;
    const exercise = me.tool.collection.exercise;

    const entryParts: PartFragment[] = exercise.parts.filter((p) => p.isEntryPart);

    const breadCrumbs: BreadCrumbPart[] = [
      {routerLinkPart: '/', title: 'Tools'},
      {routerLinkPart: `tools/${toolId}`, title: tool.name},
      {routerLinkPart: 'collections', title: 'Sammlungen'},
      {routerLinkPart: collection.collectionId.toString(), title: collection.title},
      {routerLinkPart: 'exercises', title: 'Aufgaben'},
      {routerLinkPart: exercise.exerciseId.toString(), title: exercise.exerciseId.toString()}
    ];

    return (
      <div className="container">

        <h1 className="title is-3 has-text-centered">Aufgabe &quot;{exercise.title}&quot;</h1>

        <div className="my-3">
          <BreadCrumbs parts={breadCrumbs}/>
        </div>

        <div className="notification is-light-grey" dangerouslySetInnerHTML={{__html: exercise.text}}/>

        <div className="columns">
          {entryParts.map((part) =>
            <div className="column" key={part.id}>
              <Link className=" button is-link is-fullwidth" to={`${url}/parts/${part.id}`}>{part.name}</Link>
            </div>
          )}
        </div>

      </div>
    );

  }

  return <WithQuery query={exerciseOverviewQuery} render={render}/>;
}
