// react-ui/src/collectionTools/tools/uml/UmlDiagramDrawing.tsx
import React, {useEffect, useMemo, useRef, useState} from 'react';
import * as joint from 'jointjs';
import {
  ExerciseSolveFieldsFragment,
  UmlClassDiagramInput,
  UmlClassInput,
  UmlExerciseContentFragment,
  UmlMultiplicity,
  useUmlCorrectionMutation
} from '../../../graphql';
import {BulmaTabs, Tabs} from '../../../helpers/BulmaTabs';
import {useTranslation} from 'react-i18next';
import {GRID_SIZE, PAPER_HEIGHT} from './model/uml-consts';
import {addAssociationToGraph, addClassToGraph, addImplementationToGraph, findFreePositionForNextClass} from './model/class-diag-helpers';
import {isAssociation, isImplementation, isMyJointClass, MyJointClass} from './model/joint-class-diag-elements';
import {UmlDiagramDrawingExerciseTextTabContent} from './UmlDiagramDrawingExerciseTextTabContent';
import {umlAssocFromConnection, umlImplFromConnection} from './model/my-uml-interfaces';
import {database} from '../../DexieTable';
import {UmlDiagramDrawingCorrectionTabContent} from './UmlDiagramDrawingCorrectionTabContent';
import {WithQuery} from '../../../WithQuery';
import {UmlClassEdit} from './UmlClassEdit';

enum CreatableClassDiagramObject {Class, Association, Implementation}

export interface SelectableClassDiagramObject {
  name: string;
  key: CreatableClassDiagramObject;
  disabled?: boolean;
}

export interface UmlDbClass extends UmlClassInput {
  position?: joint.dia.Point;
}

export interface UmlDbClassDiagram extends UmlClassDiagramInput {
  classes: UmlDbClass[];
}

interface IProps {
  exercise: ExerciseSolveFieldsFragment;
  content: UmlExerciseContentFragment;
  withHelp: boolean;
  partId: string;
  oldSolution: UmlDbClassDiagram | undefined;
}

interface IState {
  markedClass?: MyJointClass;
  editedClass?: MyJointClass;
  editedAssociation?: joint.shapes.uml.Association;
  selectedCreatableObject?: SelectableClassDiagramObject;
}

export function UmlDiagramDrawing({exercise, content, withHelp, partId, oldSolution}: IProps): JSX.Element {

  const {t} = useTranslation('common');
  const canvas = useRef<HTMLDivElement>(null);

  const [activeTab, setActiveTab] = useState<keyof Tabs>('exerciseText');
  const [state, setState] = useState<IState>({});

  const [correctExercise, correctionMutationResult] = useUmlCorrectionMutation();

  if (!content.umlPart) {
    throw new Error('no part found?');
  }

  const part = content.umlPart;

  // vars get recreated after every rerender!
  const graph: joint.dia.Graph = useMemo(() => new joint.dia.Graph(), []);
  let paper: joint.dia.Paper;

  useEffect(() => {
    if (canvas.current) {
      // Initialize paper
      paper = new joint.dia.Paper({
        el: canvas.current, model: graph,
        width: canvas.current.clientWidth, height: PAPER_HEIGHT,
        gridSize: GRID_SIZE, drawGrid: {name: 'dot'}
      });

      createPaperEvents();

      if (oldSolution) {
        loadClassDiagram(oldSolution, false, true);
      } else if (withHelp) {
        loadClassDiagram(content.umlSampleSolutions[0], true, false);
      }
    }
  }, []);

  const creatableClassDiagramObjects: SelectableClassDiagramObject[] = [
    {name: 'Klasse', key: CreatableClassDiagramObject.Class, disabled: withHelp},
    {name: 'Assoziation', key: CreatableClassDiagramObject.Association},
    {name: 'Vererbung', key: CreatableClassDiagramObject.Implementation}
  ];

  function createPaperEvents(): void {
    paper.on('blank:pointerclick', (evt: joint.dia.Event, x: number, y: number) => setState((state) => {
      if (state.selectedCreatableObject && state.selectedCreatableObject.key === CreatableClassDiagramObject.Class) {
        addClassToGraph(graph, 'Klasse 1', [], [], {x, y});
      }

      return state;
    }));

    paper.on('cell:pointerclick', (cellView) =>
      setState(({markedClass, selectedCreatableObject, ...rest}) => {

        const model = cellView.model;

        if (!(model instanceof MyJointClass)) {
          return {...rest, markedClass: undefined, selectedCreatableObject};
        }

        if (!markedClass) {
          // Nothing set yet
          cellView.highlight();
          return {...rest, markedClass: model, selectedCreatableObject};
        }

        if (markedClass.getClassName() === model.getClassName()) {
          // class was clicked again
          cellView.unhighlight();
          return {...rest, markedClass: undefined, selectedCreatableObject};
        }

        if (selectedCreatableObject) {
          if (selectedCreatableObject.key === CreatableClassDiagramObject.Association) {
            addAssociationToGraph(graph, markedClass, UmlMultiplicity.Unbound, model as MyJointClass, UmlMultiplicity.Unbound);
          } else if (selectedCreatableObject.key === CreatableClassDiagramObject.Implementation) {
            addImplementationToGraph(graph, markedClass, cellView.model as MyJointClass);
          }

          markedClass.findView(paper).unhighlight();

          return {...rest, markedClass: undefined, selectedCreatableObject};
        }

        // New class selected, nothing to create
        markedClass.findView(paper).unhighlight();
        cellView.highlight();
        return {...rest, markedClass: cellView.model, selectedCreatableObject};
      })
    );

    paper.on('cell:contextmenu', (cellView) => setState((state) => {
      const model = cellView.model;

      if (model instanceof joint.shapes.uml.Association) {
        return {...state, editedAssociation: model};
      }

      if (model instanceof MyJointClass && !withHelp) {
        console.info(state.editedClass);
        return {...state, editedClass: state.editedClass?.getClassName() === model.getClassName() ? undefined : model};
      }

      return state;
    }));
  }

  function loadClassDiagram({classes, associations, implementations}: UmlDbClassDiagram, loadAttrsAndMethods = false, loadAssocsAndImpl = false): void {

    classes.forEach(({name, attributes, methods, position}) => {
      const thePosition = position || findFreePositionForNextClass(paper);
      addClassToGraph(graph, name, loadAttrsAndMethods ? [] : (attributes || []), loadAttrsAndMethods ? [] : (methods || []), thePosition);
    });

    if (loadAssocsAndImpl) {
      const allCells: MyJointClass[] = graph.getCells().filter(isMyJointClass);

      associations.forEach(({firstEnd, firstMult, secondEnd, secondMult}) => {
        const maybeFirstEnd = allCells.find((c) => c.getClassName() === firstEnd);
        const maybeSecondEnd = allCells.find((c) => c.getClassName() === secondEnd);

        if (maybeFirstEnd && maybeSecondEnd) {
          addAssociationToGraph(graph, maybeFirstEnd, firstMult, maybeSecondEnd, secondMult);
        }
      });

      implementations.forEach(({subClass, superClass}) => {
        const maybeSubClass = allCells.find((c) => c.getClassName() === subClass);
        const maybeSuperClass = allCells.find((c) => c.getClassName() === superClass);

        if (maybeSubClass && maybeSuperClass) {
          addImplementationToGraph(graph, maybeSubClass, maybeSuperClass);
        }
      });
    }
  }

  function toggle(x: SelectableClassDiagramObject): void {
    setState((state) => ({...state, selectedCreatableObject: x.key === state.selectedCreatableObject?.key ? undefined : x}));
  }

  function correct(): void {
    const dbSolution: UmlDbClassDiagram = {
      classes: graph.getCells().filter(isMyJointClass).map((cell) => cell.getAsUmlClass()),
      associations: graph.getLinks().filter(isAssociation).map(umlAssocFromConnection),
      implementations: graph.getLinks().filter(isImplementation).map(umlImplFromConnection)
    };

    database.upsertSolution(exercise.toolId, exercise.collectionId, exercise.exerciseId, partId, dbSolution);

    const solution: UmlClassDiagramInput = {
      ...dbSolution,
      classes: dbSolution.classes.map(({classType, name, attributes, methods}) => ({classType, name, attributes, methods})),
    };

    correctExercise({variables: {collId: exercise.collectionId, exId: exercise.exerciseId, part, solution}})
      .then(() => setActiveTab('correction'))
      .catch((error) => console.error(error));
  }

  const tabs: Tabs = {
    exerciseText: {
      name: t('exerciseText'),
      render: <UmlDiagramDrawingExerciseTextTabContent exercise={exercise} content={content} correct={() => correct()}
                                                       creatableClassDiagramObjects={creatableClassDiagramObjects}
                                                       onClassClick={(name) => console.warn(name)} toggle={toggle}
                                                       selectedCreatableObject={state.selectedCreatableObject}
                                                       isCorrecting={correctionMutationResult.called && correctionMutationResult.loading}/>
    },
    correction: {
      name: t('correction'),
      render: <WithQuery query={correctionMutationResult} render={(data) => <UmlDiagramDrawingCorrectionTabContent corrResult={data}/>}/>
    }
  };

  return (
    <div className="container is-fluid">

      <div className="columns">
        <div className="column is-three-fifths">

          <div ref={canvas} className="myPaper"/>

          {/*debug &&                   <div className="columns my-3">
              <div className="column is-one-quarter-desktop">
                <label className="label" htmlFor="importFile">Alte Lösung importieren:</label>
              </div>
              <div className="column">
                <input type="file" id="importFile" className="input is-fullwidth" (change)="readFile($event.target.files)">
              </div>
            </div>          */}
        </div>

        <div className="column">

          <BulmaTabs tabs={tabs} activeTabId={activeTab} setActiveTabId={setActiveTab}/>

          {state.editedClass && <>
            <hr/>

            <UmlClassEdit editedClass={state.editedClass} cancelEdit={() => setState((state) => ({...state, editedClass: undefined}))}/>

            {/*< it4all - uml - className - edit [editedClass] = 'editedClass'(cancel) = 'editedClass = undefined' > < /it4all-uml-className-edit>*/}
          </>}

          {/*
  <ng-container *ngIf = 'editedAssociation' >
  < hr >

  < it4all - uml - assoc - edit [editedAssociation] = 'editedAssociation'
  (cancel) = 'editedAssociation = undefined' > < /it4all-uml-assoc-edit>;;;;
</ng-container>
*/}

        </div>
      </div>
    </div>
  );
}

// ui/src/app/tools/collection-tools/uml/uml-diagram-drawing/uml-diagram-drawing.component.ts
import {Component, Input, OnInit} from '@angular/core';
import {isAssociation, isImplementation, isMyJointClass, MyJointClass} from '../_model/joint-class-diag-elements';
import {
  getUmlExerciseTextParts,
  SelectableClass,
  UmlDiagramDrawingHelpPart,
  UmlExerciseTextPart,
  UmlMemberAllocationPart
} from '../uml-tools';
import {GRID_SIZE, PAPER_HEIGHT} from '../_model/uml-consts';
import {IUmlClassDiagram, IUmlCompleteResult} from '../uml-interfaces';
import {addAssociationToGraph, addClassToGraph, addImplementationToGraph} from '../_model/class-diag-helpers';
import {ExportedUmlClassDiagram, umlAssocfromConnection, umlImplfromConnection} from '../_model/my-uml-interfaces';

import * as joint from 'jointjs';
import {ComponentWithExercise} from '../../_helpers/component-with-exercise';
import {ToolPart} from '../../../../_interfaces/tool';
import {ApiService} from '../../_services/api.service';
import {DexieService} from '../../../../_services/dexie.service';
import {environment} from '../../../../../environments/environment';
import {
  ExerciseSolveFieldsFragment,
  UmlExerciseContentSolveFieldsFragment
} from "../../../../_services/apollo_services";


enum CreatableClassDiagramObject {
  Class,
  Association,
  Implementation
}


/**
 * @deprecated
 */
interface SelectableClassDiagramObject {
  name: string;
  key: CreatableClassDiagramObject;
  selected: boolean;
  disabled?: boolean;
}

@Component({
  selector: 'it4all-uml-diagram-drawing',
  templateUrl: './uml-diagram-drawing.component.html',
  styles: [`
    #myPaper {
      border: 1px solid slategrey;
      border-radius: 5px;
    }
  `]
})
export class UmlDiagramDrawingComponent extends ComponentWithExercise<ExportedUmlClassDiagram, IUmlCompleteResult> implements OnInit {

  readonly nextPart = UmlMemberAllocationPart;

  @Input() part: ToolPart;
  @Input() exerciseFragment: ExerciseSolveFieldsFragment;
  @Input() exerciseContent: UmlExerciseContentSolveFieldsFragment;

  withHelp: boolean;

  graph: joint.dia.Graph = new joint.dia.Graph();
  paper: joint.dia.Paper;

  selectableClasses: SelectableClass[];
  umlExerciseTextParts: UmlExerciseTextPart[];

  markedClass: MyJointClass | undefined;
  editedClass: MyJointClass | undefined;
  editedAssociation: joint.shapes.uml.Association | undefined;

  creatableClassDiagramObjects: SelectableClassDiagramObject[];

  corrected = false;

  readonly debug = !environment.production;

  constructor(apiService: ApiService, dexieService: DexieService) {
    super(apiService, dexieService);
  }

  ngOnInit(): void {
    this.withHelp = this.part == UmlDiagramDrawingHelpPart;

    this.creatableClassDiagramObjects = [
      {name: 'Klasse', key: CreatableClassDiagramObject.Class, selected: false, disabled: this.withHelp},
      {name: 'Assoziation', key: CreatableClassDiagramObject.Association, selected: false},
      {name: 'Vererbung', key: CreatableClassDiagramObject.Implementation, selected: false}
    ];

    const {selectableClasses, textParts} = getUmlExerciseTextParts(this.exerciseFragment, this.exerciseContent);

    this.selectableClasses = selectableClasses;
    this.umlExerciseTextParts = textParts;

    const paperJQueryElement = $('#myPaper');

    this.paper = new joint.dia.Paper({
      el: paperJQueryElement, model: this.graph,
      width: Math.floor(paperJQueryElement.width()), height: PAPER_HEIGHT,
      gridSize: GRID_SIZE, drawGrid: {name: 'dot'}
    });

    this.createPaperEvents(this.paper);

    // load classes

    this.loadOldSolutionAbstract(this.exerciseFragment.id, this.exerciseFragment.collectionId, this.exerciseFragment.toolId, this.part)
      .then((oldSol) => {
        if (oldSol) {
          this.loadClassDiagram(oldSol);
        } else {
          this.loadClassDiagram(this.exerciseContent.umlSampleSolutions[0].sample as ExportedUmlClassDiagram);
        }
      });
  }

  loadClassDiagram(cd: ExportedUmlClassDiagram): void {
    for (const clazz of cd.classes) {
      addClassToGraph(clazz.name, this.paper, clazz.position, clazz.attributes, clazz.methods);
    }

    const allCells: MyJointClass[] = this.graph.getCells().filter(isMyJointClass);

    for (const assoc of cd.associations) {
      addAssociationToGraph(
        allCells.find((c) => c.getClassName() === assoc.firstEnd),
        assoc.firstMult === 'UNBOUND' ? '*' : '1',
        allCells.find((c) => c.getClassName() === assoc.secondEnd),
        assoc.secondMult === 'UNBOUND' ? '*' : '1',
        this.graph
      );
    }

    for (const impl of cd.implementations) {
      addImplementationToGraph(
        allCells.find((c) => c.getClassName() === impl.subClass),
        allCells.find((c) => c.getClassName() === impl.superClass),
        this.graph
      );
    }
  }

  createPaperEvents(paper: joint.dia.Paper): void {
    paper.on('blank:pointerclick', (evt: joint.dia.Event, x: number, y: number) => {
        const selectedObjectToCreate: SelectableClassDiagramObject =
          this.creatableClassDiagramObjects.find((scdo) => scdo.selected);

        if (selectedObjectToCreate && CreatableClassDiagramObject.Class === selectedObjectToCreate.key) {
          addClassToGraph('Klasse 1', paper, {x, y});
        }
      }
    );

    paper.on('cell:pointerclick', (cellView: joint.dia.CellView, event: joint.dia.Event /*, x: number, y: number*/) => {
      if (cellView.model instanceof MyJointClass) {
        const selectedObjectToCreate: SelectableClassDiagramObject =
          this.creatableClassDiagramObjects.find((scdo) => scdo.selected);

        if (!this.markedClass) {
          this.markedClass = cellView.model as MyJointClass;
          cellView.highlight();
        } else if (this.markedClass === cellView.model) {
          this.markedClass = undefined;
          cellView.unhighlight();
        } else if (selectedObjectToCreate) {
          if (selectedObjectToCreate.key === CreatableClassDiagramObject.Association) {
            addAssociationToGraph(this.markedClass, '*', cellView.model as MyJointClass, '*', this.graph);
          } else if (selectedObjectToCreate.key === CreatableClassDiagramObject.Implementation) {
            addImplementationToGraph(this.markedClass, cellView.model as MyJointClass, this.graph);
          }

          this.markedClass.findView(paper).unhighlight();
          this.markedClass = undefined;
        }
      } else {
        console.info(cellView.model);
        event.preventDefault();
        event.stopImmediatePropagation();
        event.stopPropagation();
      }
    });

    paper.on('cell:contextmenu', (cellView: joint.dia.CellView/*, event: joint.dia.Event, x: number, y: number*/) => {
      if (this.withHelp) {
        if (cellView.model instanceof MyJointClass) {
          // Cannot change classes
          return;
        } else if (cellView.model instanceof joint.shapes.uml.Association) {
          // Change association...
          this.editedAssociation = cellView.model;
        }
      } else if (cellView.model instanceof MyJointClass) {
        if (!this.editedClass) {
          this.editedClass = cellView.model as MyJointClass;
        } else {
          this.editedClass = undefined;
        }
      } else {
        console.info(cellView.model);
      }
    });
  }

  createClass(selectableClass: SelectableClass): void {
    if (this.withHelp || selectableClass.selected) {
      // Class is already in graph!
      return;
    }

    selectableClass.selected = true;

    addClassToGraph(selectableClass.name, this.paper);
  }

  toggle(toCreate: SelectableClassDiagramObject): void {
    this.creatableClassDiagramObjects.forEach((scdo) => scdo.selected = (scdo.key === toCreate.key) ? !scdo.selected : false);
  }

  readFile(files: FileList): void {
    const fileReader = new FileReader();

    fileReader.onload = ((pe) => {
      const read: string = pe.target['result'] as string;

      const loaded: ExportedUmlClassDiagram = JSON.parse(read);

      for (const clazz of loaded.classes) {
        addClassToGraph(clazz.name, this.paper, clazz.position, clazz.attributes || []);
      }

      const allCells = this.graph.getCells().filter(isMyJointClass);

      for (const impl of loaded.implementations) {
        addImplementationToGraph(
          allCells.find((c) => c.getClassName() === impl.subClass),
          allCells.find((c) => c.getClassName() === impl.superClass),
          this.graph
        );
      }
    });

    fileReader.readAsText(files.item(0));
  }

  protected getSolution(): ExportedUmlClassDiagram {
    return {
      classes: this.graph.getCells().filter(isMyJointClass).map((cell) => cell.getAsUmlClass()),
      associations: this.graph.getLinks().filter(isAssociation).map(umlAssocfromConnection),
      implementations: this.graph.getLinks().filter(isImplementation).map(umlImplfromConnection)
    };
  }

  get sampleSolutions(): IUmlClassDiagram[] {
    return this.exerciseContent.umlSampleSolutions.map((sample) => sample.sample);
  }

  correct(): void {
    super.correctAbstract(this.exerciseFragment.id, this.exerciseFragment.collectionId, this.exerciseFragment.toolId, this.part);
    this.corrected = true;
  }

}

<div class="container is-fluid">
  <div class="columns">
    <div class="column is-three-fifths">
      <div id="myPaper"></div>

      <ng-container *ngIf="debug">
        <br>

        <div class="columns">
          <div class="column is-one-quarter-desktop">
            <label class="label" for="importFile">Alte Lösung importieren:</label>
          </div>
          <div class="column">
            <input type="file" id="importFile" class="input is-fullwidth" (change)="readFile($event.target.files)">
          </div>
        </div>
      </ng-container>

    </div>
    <div class="column">

      <it4all-tabs>
        <it4all-tab [title]="exerciseTextTabTitle">
          <div class="notification is-light-grey">
            <ng-container *ngFor="let tp of umlExerciseTextParts">
              <span *ngIf="tp.selectableClass" (click)="createClass(tp.selectableClass)">{{tp.text}}</span>
              <span *ngIf="!tp.selectableClass">{{tp.text}}</span>
            </ng-container>
          </div>

          <div class="columns">
            <div class="column" *ngFor="let x of creatableClassDiagramObjects">
              <button class="button is-fullwidth" (click)="toggle(x)"
                      [ngClass]="x.selected ? 'is-link': ''" [disabled]="x.disabled">
                {{x.name}}
              </button>
            </div>
          </div>

          <div class="columns">
            <div class="column">
              <button class="button is-link is-fullwidth" [class.is-loading]="isCorrecting" (click)="correct()">
                Korrektur
              </button>
            </div>
            <!--
            <div class="column">
              <button class="button is-primary is-fullwidth" (click)="showSampleSolution()" disabled>Musterlösung
                anzeigen
              </button>
            </div>
            -->
            <div class="column">
              <button class="button is-fullwidth" [routerLink]="['..', nextPartId]" [disabled]="!corrected"
                      [ngClass]="corrected ? 'is-link': 'is-dark'">
                Zum nächsten Aufgabenteil
              </button>
            </div>
            <div class="column">
              <a [routerLink]="['../..']" class="button is-dark is-fullwidth">Bearbeiten beenden</a>
            </div>
          </div>
        </it4all-tab>
        <it4all-tab [title]="correctionTabTitle">

          <it4all-solution-saved *ngIf="umlAbstractResult" [solutionSaved]="correctionResult.solutionSaved">
          </it4all-solution-saved>

          <it4all-uml-diag-drawing-correction *ngIf="resultQuery" [result]="result">
          </it4all-uml-diag-drawing-correction>
        </it4all-tab>
      </it4all-tabs>

      <ng-container *ngIf="editedClass">
        <hr>

        <it4all-uml-class-edit [editedClass]="editedClass" (cancel)="editedClass = undefined"></it4all-uml-class-edit>
      </ng-container>

      <ng-container *ngIf="editedAssociation">
        <hr>

        <it4all-uml-assoc-edit [editedAssociation]="editedAssociation"
                               (cancel)="editedAssociation = undefined"></it4all-uml-assoc-edit>
      </ng-container>

    </div>
  </div>
</div>
