// ui/src/app/tools/collection-tools/sql/_results/sql-matching-result/sql-matching-result.component.ts
import {Component, Input, OnChanges, SimpleChanges} from '@angular/core';
import {MatchType, StringMatchFragment, StringMatchingResultFragment} from '../../../../../_services/apollo_services';

@Component({
  selector: 'it4all-sql-matching-result',
  template: `
    <div [ngClass]="successful ? 'has-text-success' : 'has-text-danger'">
      ({{matchingResult.points.toFixed(1)}} / {{matchingResult.maxPoints.toFixed(1)}} P)
      Der Vergleich der {{matchName}} war {{successful ? "" : "nicht"}} erfolgreich.
    </div>
    <div class="content" *ngIf="!successful">
      <ul>
        <li *ngFor="let match of matchingResult.allMatches" [class]="getCssClassForMatchType(match.matchType)">
          Die Angabe {{matchSingularName}}
          <code>{{getArgDescription(match)}}</code> {{getTextForMatchType(match.matchType)}}.
        </li>
        <li *ngFor="let notMatchedForUser of matchingResult.notMatchedForUser" class="has-text-danger">
          Die Angabe {{matchSingularName}} <code>{{notMatchedForUser}}</code> ist falsch.
        </li>
        <li *ngFor="let notMatchedForSample of matchingResult.notMatchedForSample" class="has-text-danger">
          Die Angabe {{matchSingularName}} <code>{{notMatchedForSample}}</code> fehlt.
        </li>
      </ul>
    </div>
  `
})
export class SqlMatchingResultComponent implements OnChanges {

  @Input() matchName: string;
  @Input() matchSingularName: string;

  @Input() matchingResult: StringMatchingResultFragment;

  successful: boolean;

  ngOnChanges(changes: SimpleChanges): void {
    this.successful = this.matchingResult.allMatches
      .every((m) => m.matchType === MatchType.SuccessfulMatch);
  }

  getCssClassForMatchType(matchType: MatchType): string {
    return (matchType === MatchType.SuccessfulMatch) ? 'has-text-success' : 'has-text-danger';
  }

  getArgDescription(match: StringMatchFragment): string {
    return match.userArg;
  }

  getTextForMatchType(matchType: MatchType): string {
    return matchType === MatchType.SuccessfulMatch ? 'ist korrekt' : 'ist nicht komplett richtig.';
  }

}

<span [ngClass]="successful ? 'has-text-success' : 'has-text-danger'">
  ({{matchingResult.points.toFixed(1)}} / {{matchingResult.maxPoints.toFixed(1)}} P)
  Der Vergleich der {{matchingResult.matchName}} war <ng-container *ngIf="!successful">nicht</ng-container> erfolgreich.
</span>

<div class="content">
  <ul *ngIf="!successful">
    <li *ngFor="let match of matchingResult.allMatches">
      <ng-container [ngSwitch]="match.analysisResult.matchType">

        <span *ngSwitchCase="'SUCCESSFUL_MATCH'" class="has-text-success">
          Die Angabe {{matchingResult.matchSingularName}} <code>{{match.userArg}}</code> war korrekt.
        </span>

        <span *ngSwitchCase="'ONLY_SAMPLE'" class="has-text-danger">
         Die Angabe {{matchingResult.matchSingularName}} <code>{{match.sampleArg}}</code> fehlt!
        </span>

        <span *ngSwitchCase="'ONLY_USER'" class="has-text-danger">
         Die Angabe {{matchingResult.matchSingularName}} <code>{{match.userArg}}</code> ist falsch!
        </span>

        <span *ngSwitchDefault class="has-text-danger">
         Die Angabe {{matchingResult.matchSingularName}} <code>{{match.userArg}}</code> war nicht komplett richtig.
        </span>

      </ng-container>
    </li>
  </ul>
</div>

// react-ui/src/collectionTools/tools/sql/SqlMatchingResult.tsx
import React from 'react';
import {MatchType, NewMatchFragment, SqlMatchingResultFragment} from '../../../graphql';
import classNames from 'classnames';
import {getCssClassForMatchType, getTextForMatchType} from './SqlStringMatchingResult';

interface IProps {
  matchName: string;
  matchSingularName: string;
  matchingResult: SqlMatchingResultFragment;
}

export function SqlMatchingResult({matchName, matchSingularName, matchingResult}: IProps): JSX.Element {

  const allMatches: NewMatchFragment[] = matchingResult.allMatches;

  const successful = allMatches.every((m: NewMatchFragment) => m.matchType === MatchType.SuccessfulMatch)
    && matchingResult.notMatchedForUserString.length === 0
    && matchingResult.notMatchedForSampleString.length === 0;

  return (
    <>
      <div className={classNames(successful ? 'has-text-success' : 'has-text-danger')}>
        {/* ({matchingResult.points.toFixed(1)} / {matchingResult.maxPoints.toFixed(1)} P) */}
        Der Vergleich der {matchName} war {successful ? '' : 'nicht'} erfolgreich.
      </div>

      {!successful && <div className="content">
        <ul>
          {allMatches.map((match, index) =>
            <li className={getCssClassForMatchType(match.matchType)} key={index}>
              Die Angabe {{matchSingularName}}
              <code>{match.userArgDescription}</code> {getTextForMatchType(match.matchType)}.
            </li>
          )}
          {matchingResult.notMatchedForUserString.map((notMatchedForUser, index) =>
            <li className="has-text-danger" key={index}>
              Die Angabe {matchSingularName} <code>{notMatchedForUser}</code> ist falsch.
            </li>
          )}
          {matchingResult.notMatchedForSampleString.map((notMatchedForSample, index) =>
            <li className="has-text-danger" key={index}>
              Die Angabe {matchSingularName} <code>{notMatchedForSample}</code> fehlt.
            </li>
          )}
        </ul>
      </div>
      }
    </>
  );

}
