// it4all-client/src/app/tools/collection-tools/sql/sql-matching-result/sql-matching-result.component.ts
import {Component, Input} from '@angular/core';
import {AnalysisResult, MatchingResult} from '../../../basics';

@Component({
  selector: 'it4all-sql-matching-result',
  templateUrl: './sql-matching-result.component.html'
})
export class SqlMatchingResultComponent {

  @Input() matchingResult: MatchingResult<string, AnalysisResult>;

}

<span [ngClass]="matchingResult.success ? 'has-text-success' : 'has-text-danger'">
  ({{matchingResult.points.toFixed(1)}} / {{matchingResult.maxPoints.toFixed(1)}} P)
  Der Vergleich der {{matchingResult.matchName}} war <ng-container *ngIf="!matchingResult.success">nicht</ng-container> erfolgreich.
</span>

<div class="content">
  <ul *ngIf="!matchingResult.success">
    <li *ngFor="let match of matchingResult.matches">
      <ng-container [ngSwitch]="match.matchType">

        <span *ngSwitchCase="'SUCCESSFUL_MATCH'" class="has-text-success">
          Die Angabe {{matchingResult.matchSingularName}} <code>{{match.userArg}}</code> war korrekt.
        </span>

        <span *ngSwitchCase="'ONLY_SAMPLE'" class="has-text-danger">
         Die Angabe {{matchingResult.matchSingularName}} <code>{{match.sampleArg}}</code> fehlt!
        </span>

        <span *ngSwitchCase="'ONLY_USER'" class="has-text-danger">
         Die Angabe {{matchingResult.matchSingularName}} <code>{{match.userArg}}</code> ist falsch!
        </span>

        <span *ngSwitchDefault class="has-text-danger">
         Die Angabe {{matchingResult.matchSingularName}} <code>{{match.userArg}}</code> war nicht komplett richtig.
        </span>

      </ng-container>
    </li>
  </ul>
</div>

// react-ui/src/collectionTools/tools/sql/SqlMatchingResult.tsx
import React from 'react';
import {MatchType, NewMatchFragment, SqlMatchingResultFragment} from '../../../graphql';
import classNames from 'classnames';
import {getCssClassForMatchType, getTextForMatchType} from './SqlStringMatchingResult';

interface IProps {
  matchName: string;
  matchSingularName: string;
  matchingResult: SqlMatchingResultFragment;
}

export function SqlMatchingResult({matchName, matchSingularName, matchingResult}: IProps): JSX.Element {

  const allMatches: NewMatchFragment[] = matchingResult.allMatches;

  const successful = allMatches.every((m: NewMatchFragment) => m.matchType === MatchType.SuccessfulMatch)
    && matchingResult.notMatchedForUserString.length === 0
    && matchingResult.notMatchedForSampleString.length === 0;

  return (
    <>
      <div className={classNames(successful ? 'has-text-success' : 'has-text-danger')}>
        {/* ({matchingResult.points.toFixed(1)} / {matchingResult.maxPoints.toFixed(1)} P) */}
        Der Vergleich der {matchName} war {successful ? '' : 'nicht'} erfolgreich.
      </div>

      {!successful && <div className="content">
        <ul>
          {allMatches.map((match, index) =>
            <li className={getCssClassForMatchType(match.matchType)} key={index}>
              Die Angabe {{matchSingularName}}
              <code>{match.userArgDescription}</code> {getTextForMatchType(match.matchType)}.
            </li>
          )}
          {matchingResult.notMatchedForUserString.map((notMatchedForUser, index) =>
            <li className="has-text-danger" key={index}>
              Die Angabe {matchSingularName} <code>{notMatchedForUser}</code> ist falsch.
            </li>
          )}
          {matchingResult.notMatchedForSampleString.map((notMatchedForSample, index) =>
            <li className="has-text-danger" key={index}>
              Die Angabe {matchSingularName} <code>{notMatchedForSample}</code> fehlt.
            </li>
          )}
        </ul>
      </div>
      }
    </>
  );

}
