// client/src/app/tools/random-tools/bool/bool-create/bool-create.component.ts
import {Component, HostListener, OnInit} from '@angular/core';
import {ToolPart} from '../../../../_interfaces/tool';
import {BoolCreatePart} from '../../random-tools-list';
import {parseBooleanFormula} from '../_model/boolean-formula-parser';
import {BoolComponentHelper} from '../_model/bool-component-helper';
import {BooleanNode, calculateAssignments} from '../_model/bool-node';
import {generateBooleanFormula} from '../_model/bool-formula';
import {Router} from '@angular/router';

@Component({templateUrl: './bool-create.component.html'})
export class BoolCreateComponent extends BoolComponentHelper implements OnInit {

  readonly part: ToolPart = BoolCreatePart;

  solution = '';

  oldSolution: BooleanNode | undefined;

  formulaParsed = false;

  showInstructions = false;
  showSampleSolutions = false;

  constructor(protected router: Router) {
    super(router);
  }

  ngOnInit(): void {
    this.update();
  }

  update(): void {
    this.showSampleSolutions = false;
    this.showInstructions = false;

    this.completelyCorrect = false;
    this.formulaParsed = false;
    this.corrected = false;

    this.oldSolution = undefined;

    this.solution = '';

    this.formula = generateBooleanFormula();

    this.assignments = calculateAssignments(this.formula.getVariables());
    this.assignments.forEach((assignment) => assignment.set(this.sampleVariable.variable, this.formula.evaluate(assignment)));
  }

  correct(): void {
    this.corrected = true;

    const booleanFormula: BooleanNode | undefined = parseBooleanFormula(this.solution);

    if (!booleanFormula) {
      alert('Konnte Formel >>' + this.solution + '<< nicht parsen!');
      return;
    }

    this.oldSolution = booleanFormula;

    this.formulaParsed = true;

    // check contained variables!
    const variablesAllowed: string[] = this.formula.getVariables().map((v) => v.variable);
    const variablesUsed: string[] = booleanFormula.getVariables().map((v) => v.variable);

    const illegalVariables = variablesUsed.filter((v) => !variablesAllowed.includes(v));


    if (illegalVariables.length > 0) {
      alert('Sie haben die falschen Variablen ' + illegalVariables + ' benutzt!');
      return;
    }

    this.completelyCorrect = this.assignments
      .map((assignment) => {
        const value: boolean = booleanFormula.evaluate(assignment);
        assignment.set(this.learnerVariable.variable, value);
        return assignment.get(this.sampleVariable.variable) === value;
      })
      .every((a) => a);
  }

  @HostListener('document:keypress', ['$event'])
  handleKeyboardEvent(event: KeyboardEvent): void {
    if (event.key === 'Enter') {
      if (this.completelyCorrect) {
        this.update();
      } else {
        this.correct();
      }
    }
  }

}

<div class="container">
  <h1 class="title is-3 has-text-centered">{{part.name}}</h1>

  <div class="columns">
    <div class="column is-half-desktop is-offset-one-quarter-desktop">

      <table class="table is-bordered is-fullwidth">
        <thead>
          <tr>
            <th class="has-text-centered" *ngFor="let variable of formula.getVariables()">{{variable.variable}}</th>
            <th class="has-text-centered">{{sampleVariable.variable}}</th>
            <th class="has-text-centered">{{learnerVariable.variable}}</th>
          </tr>
        </thead>
        <tbody>
          <tr *ngFor="let assignment of assignments">
            <td class="has-text-centered"
                *ngFor="let variable of formula.getVariables()">{{displayAssignmentValue(assignment, variable)}}</td>
            <td class="has-text-centered">{{displayAssignmentValue(assignment, sampleVariable)}}</td>
            <td [class.has-background-danger]="corrected && !isCorrect(assignment)"
                [class.has-background-success]="corrected && isCorrect(assignment)"
                [class.has-text-white]="corrected" class="has-text-centered">
              {{displayAssignmentValue(assignment, learnerVariable)}}
              &nbsp;
              <span class="has-text-white" *ngIf="corrected && !isCorrect(assignment)">&#10008;</span>
              <span class="has-text-white" *ngIf="corrected && isCorrect(assignment)">&#10004;</span>
            </td>
          </tr>
        </tbody>
      </table>

      <hr>

      <div class="field has-addons">
        <div class="control">
          <label for="solution" class="button is-static">{{sampleVariable.variable}} = </label>
        </div>
        <div class="control is-expanded">
          <input type="text" class="input" id="solution" autocomplete="off" placeholder="Boolesche Formel"
                 autofocus [(ngModel)]="solution">
        </div>
      </div>

      <!-- FIXME: show current solutions... -->
      <div class="notification has-text-centered" *ngIf="oldSolution">
        <code [innerHTML]="'y = ' + oldSolution.asHtmlString()"></code>
      </div>

      <div class="notification has-text-centered is-danger" *ngIf="corrected && !formulaParsed">
        &#10071; Ihre Formel konnte nicht geparst werden!
      </div>
      <div class="notification has-text-centered is-danger" *ngIf="corrected && formulaParsed && !completelyCorrect">
        &#10008; Die Formel ist nicht korrekt.
      </div>
      <div class="notification has-text-centered is-success" *ngIf="corrected && formulaParsed && completelyCorrect">
        &#10004; Die Formel ist korrekt.
      </div>

      <br>

      <it4all-random-solve-buttons (correctEmitter)="correct()" (nextEmitter)="update()" (endEmitter)="end()">
      </it4all-random-solve-buttons>

      <br>

      <div class="columns">
        <div class="column is-half-desktop">
          <button class="button is-primary is-fullwidth" (click)="showSampleSolutions = !showSampleSolutions">
            Musterlösungen anzeigen
          </button>
        </div>
        <div class="column is-half-desktop">
          <button class="button is-info is-fullwidth" (click)="showInstructions = !showInstructions">
            Hilfe anzeigen
          </button>
        </div>
      </div>

      <div class="card" *ngIf="showSampleSolutions">
        <header class="card-header">
          <p class="card-header-title is-centered">Musterlösungen</p>
        </header>
        <div class="card-content">
          <code>{{formula.asString()}}</code>
        </div>
      </div>

    </div>
  </div>

  <it4all-bool-create-instructions *ngIf="showInstructions"></it4all-bool-create-instructions>
</div>

// react-ui/src/randomTools/BoolCreate.tsx
import React, {useState} from 'react';
import {BooleanFormula, generateBooleanFormula} from './bool/_model/bool-formula';
import {displayAssignmentValue, learnerVariable, sampleVariable} from './bool/_model/bool-component-helper';
import {useTranslation} from 'react-i18next';
import {Assignment, calculateAssignments} from './bool/_model/bool-node';
import classNames from 'classnames';
import {RandomSolveButtons} from './RandomToolBase';
import {BoolCreateInstructions} from './BoolCreateInstructions';
import {parseBooleanFormula} from './bool/_model/boolean-formula-parser';

interface IState {
  formula: BooleanFormula;
  assignments: Assignment[];
  corrected: boolean;
  showSampleSolutions: boolean;
  solution: string;
}

function initState(): IState {
  const formula = generateBooleanFormula(sampleVariable);

  const assignments = calculateAssignments(formula.getVariables());

  assignments.forEach((assignment) => {
    assignment[sampleVariable.variable] = formula.evaluate(assignment);
  });

  return {formula, assignments, corrected: false, showSampleSolutions: false, solution: ''};
}

export function BoolCreate(): JSX.Element {

  const {t} = useTranslation('common');
  const [state, setState] = useState(initState());
  const [showInstructions, setShowInstructions] = useState(false);

  function isCorrect(assignment: Assignment): boolean {
    return false;
  }

  function correct(): void {
    const parsed = parseBooleanFormula(state.solution);
    console.error(JSON.stringify(parsed));
  }

  const corrected = false;

  return (
    <div className="container">
      <h1 className="title is-3 has-text-centered">{t('createBooleanFormula')}</h1>

      <table className="table is-bordered is-fullwidth">
        <thead>
          <tr>
            {state.formula.getVariables().map(({variable}) => <th className="has-text-centered" key={variable}>{variable}</th>)}
            <th className="has-text-centered">{sampleVariable.variable}</th>
            <th className="has-text-centered">{learnerVariable.variable}</th>
          </tr>
        </thead>
        <tbody>
          {state.assignments.map((assignment, index) =>
            <tr key={index}>
              {state.formula.getVariables().map((variable) =>
                <td className="has-text-centered" key={variable.variable}>{displayAssignmentValue(assignment, variable)}</td>
              )}
              <td className="has-text-centered">{displayAssignmentValue(assignment, sampleVariable)}</td>
              <td className={classNames({
                'has-background-danger': corrected && !isCorrect(assignment),
                'has-background-success': corrected && isCorrect(assignment),
                'has-text-white': corrected
              }, 'has-text-centered')}>
                {displayAssignmentValue(assignment, learnerVariable)}
                &nbsp;
                {corrected && !isCorrect(assignment) && <span className="has-text-white">&#10008;</span>}
                {corrected && !isCorrect(assignment) && <span className="has-text-white">&#10004;</span>}
              </td>
            </tr>
          )}
        </tbody>
      </table>

      <hr/>

      <div className="field has-addons">
        <div className="control">
          <label htmlFor="solution" className="button is-static">{sampleVariable.variable} = </label>
        </div>
        <div className="control is-expanded">
          {/*[(ngModel)]="solution"*/}
          <input type="text" defaultValue={state.solution} onChange={(event) => setState((state) => ({...state, solution: event.target.value}))}
                 className="input" id="solution" autoComplete="off" placeholder="Boolesche Formel" autoFocus/>
        </div>
      </div>


      <RandomSolveButtons correct={correct} nextExercise={() => setState(initState())}/>


      <div className="columns my-3">
        <div className="column is-half-desktop">
          <button className="button is-primary is-fullwidth"
                  onClick={() => setState(({showSampleSolutions, ...rest}) => ({...rest, showSampleSolutions: !showSampleSolutions}))}>
            Musterlösungen anzeigen
          </button>
        </div>
        <div className="column is-half-desktop">
          <button className="button is-info is-fullwidth" onClick={() => setShowInstructions((showInstructions) => !showInstructions)}>
            Hilfe anzeigen
          </button>
        </div>
      </div>

      {state.showSampleSolutions && <div className="card">
        <header className="card-header">
          <p className="card-header-title is-centered">Musterlösungen</p>
        </header>
        <div className="card-content">
          <code>{state.formula.asString()}</code>
        </div>
      </div>}


      {showInstructions && <BoolCreateInstructions/>}

    </div>
  );
}
