// client/src/app/tools/random-tools/nary/_components/nary-number-read-only-input/nary-number-read-only-input.component.ts
import {Component, Input} from '@angular/core';
import {NaryReadOnlyNumberInput} from '../../nary';

@Component({selector: 'it4all-nary-number-read-only-input', templateUrl: './nary-number-read-only-input.component.html'})
export class NaryNumberReadOnlyInputComponent {

  @Input() naryNumberInput: NaryReadOnlyNumberInput;

  constructor() {
  }

  getSummandNary(): string {
    const radix = this.naryNumberInput.numberingSystem.radix;

    let naryString: string = this.naryNumberInput.decimalNumber.toString(radix);

    if (radix === 2) {
      naryString = naryString
        .padStart(8, '0')
        .match(/.{1,4}/g) // split in block of size 4
        .join(' ');
    }

    return naryString;
  }

  getPlaceholder(): string {
    return this.naryNumberInput.fieldPlaceholder || this.naryNumberInput.labelContent;
  }

}

<div class="field has-addons">
  <div class="control">
    <div class="button is-static">
      <label for="{{naryNumberInput.fieldId}}">{{naryNumberInput.labelContent}}</label>
    </div>
  </div>
  <div class="control is-expanded">
    <input class="input has-text-right" id="{{naryNumberInput.fieldId}}" [value]="getSummandNary()"
           [placeholder]="naryNumberInput.labelContent" readonly>
  </div>
  <div class="control">
    <div class="button is-static">
      <sub>{{naryNumberInput.numberingSystem.radix}}</sub>
    </div>
  </div>
</div>

// react-ui/src/randomTools/NaryNumberReadOnlyInput.tsx
import React from "react";
import {NaryReadOnlyNumberInput} from "./nary";


interface IProps {
  naryNumberInput: NaryReadOnlyNumberInput;
}

export function NaryNumberReadOnlyInputComponent({naryNumberInput}: IProps) {

  function getSummandNary(): string {
    const radix = naryNumberInput.numberingSystem.radix;
    const blockSize = radix === 2 ? 4 : 2;

    const minimalDigits: number = Math.log2(naryNumberInput.maxValueForDigits) / Math.log2(radix);
    const newDigitCount: number = Math.ceil(minimalDigits / blockSize) * blockSize;

    return naryNumberInput.decimalNumber
      .toString(radix)
      .padStart(newDigitCount, '0')
      .match(new RegExp(`.{1,${blockSize}}`, 'g'))! // split in blocks
      .join(' ');
  }

  return (
    <div className="field has-addons">
      <div className="control">
        <div className="button is-static">
          <label htmlFor="{naryNumberInput.fieldId}">{naryNumberInput.labelContent}</label>
        </div>
      </div>
      <div className="control is-expanded">
        <input className="input has-text-right" id={naryNumberInput.fieldId} value={getSummandNary()}
               placeholder={naryNumberInput.labelContent} readOnly/>
      </div>
      <div className="control">
        <div className="button is-static">
          <sub>{naryNumberInput.numberingSystem.radix}</sub>
        </div>
      </div>
    </div>

  )

}
