// client/src/app/tools/random-tools/_components/random-solve-buttons/random-solve-buttons.component.ts
import {Component, EventEmitter, Output} from '@angular/core';

@Component({selector: 'it4all-random-solve-buttons', templateUrl: './random-solve-buttons.component.html'})
export class RandomSolveButtonsComponent {

  @Output() correctEmitter: EventEmitter<void> = new EventEmitter<void>();
  @Output() nextEmitter: EventEmitter<void> = new EventEmitter<void>();
  @Output() endEmitter: EventEmitter<void> = new EventEmitter<void>();

  constructor() {
  }

  correct(): void {
    this.correctEmitter.emit();
  }

  next(): void {
    this.nextEmitter.emit();
  }

  end(): void {
    this.endEmitter.emit();
  }

}

<div class="columns">
  <div class="column is-one-third-desktop">
    <button class="button is-link is-fullwidth" (click)="correct()">Lösung testen</button>
  </div>
  <div class="column is-one-third-desktop">
    <button class="button is-primary is-fullwidth" (click)="next()">Nächste Aufgabe</button>
  </div>
  <div class="column is-one-third-desktop">
    <button class="button is-dark is-fullwidth" (click)="end()">Bearbeiten beenden</button>
  </div>
</div>

// react-ui/src/randomTools/RandomSolveButtons.tsx
import {Link} from 'react-router-dom';
import {randomToolsUrlFragment} from '../urls';
import React from 'react';

interface RandomSolveButtonsIProps {
  toolId: string;
  correct: () => void;
  nextExercise: () => void;
}

export function RandomSolveButtons({toolId, correct, nextExercise}: RandomSolveButtonsIProps): JSX.Element {
  return (
    <div className="columns">
      <div className="column is-one-third-desktop">
        <button className="button is-link is-fullwidth" onClick={correct}>Lösung testen</button>
      </div>
      <div className="column is-one-third-desktop">
        <button className="button is-primary is-fullwidth" onClick={nextExercise}>Nächste Aufgabe</button>
      </div>
      <div className="column is-one-third-desktop">
        {/* FIXME: link target is not correct! */}
        <Link className="button is-dark is-fullwidth" to={`/${randomToolsUrlFragment}/${toolId}`}>Bearbeiten beenden</Link>
      </div>
    </div>
  );
}
