// react-ui/src/collectionTools/tools/uml/UmlClassSelection.tsx
import { Fragment, useState } from 'react';
import {ExerciseSolveFieldsFragment, UmlExerciseContentFragment} from '../../../graphql';
import {getUmlExerciseTextParts} from './uml-helpers';
import classNames from 'classnames';
import {Link} from 'react-router-dom';
import {useTranslation} from 'react-i18next';

interface IProps {
  exercise: ExerciseSolveFieldsFragment;
  content: UmlExerciseContentFragment;
}

interface Correction {
  correctClasses: string[];
  missingClasses: string[];
  wrongClasses: string[];
}

interface IState {
  selectedClasses: string[];
  correction?: Correction;
}

function compareClasses(userClasses: string[], sampleClasses: string[]): Correction {
  return {
    correctClasses: userClasses.filter((name) => sampleClasses.includes(name)),
    missingClasses: sampleClasses.filter((name) => !userClasses.includes(name)),
    wrongClasses: userClasses.filter((name) => !sampleClasses.includes(name))
  };
}

function UmlClassSelectionCorrection({correction}: { correction: Correction }): JSX.Element {

  const {correctClasses, missingClasses, wrongClasses} = correction;

  return (
    <>
      <hr/>

      <h2 className="subtitle is-3 has-text-centered">Korrektur</h2>

      <div className="columns">
        <div className="column">
          <h3 className="subtitle is-4 has-text-centered">Korrekte Klassen:</h3>
          <ul>
            {correctClasses.map((name) => <li key={name}>&#10004;&nbsp;<code className="has-text-dark-success">{name}</code></li>)}
          </ul>
        </div>

        <div className="column">
          <h3 className="subtitle is-4 has-text-centered">Fehlende Klassen:</h3>
          <ul>
            {missingClasses.map((name) => <li key={name}>&#10008;&nbsp;<code>{name}</code></li>)}
          </ul>
        </div>

        <div className="column">
          <h3 className="subtitle is-4 has-text-centered">Falsche Klassen</h3>
          <ul>
            {wrongClasses.map((name) => <li key={name}>&#10067;&nbsp;<code>{name}</code></li>)}
          </ul>
        </div>
      </div>
    </>
  );
}

export function UmlClassSelection({exercise, content}: IProps): JSX.Element {

  const {t} = useTranslation('common');

  const textParts = getUmlExerciseTextParts(exercise, content);

  const sampleClasses = content.umlSampleSolutions[0].classes.map(({name}) => name);

  const [state, setState] = useState<IState>({selectedClasses: []});

  function toggleClass(name: string): void {
    setState(({selectedClasses, correction}) => {
        const newSelectedClasses = selectedClasses.includes(name)
          ? selectedClasses.filter((n) => n !== name)
          : [...selectedClasses, name].sort();

        const newCorrection = correction
          ? compareClasses(newSelectedClasses, sampleClasses)
          : undefined;

        return {selectedClasses: newSelectedClasses, correction: newCorrection};
      }
    );
  }

  function correct(): void {
    setState(({selectedClasses}) => ({selectedClasses, correction: compareClasses(selectedClasses, sampleClasses)}));
  }

  return (
    <div className="container">
      <h1 className="title is-3 has-text-centered">{t('classSelection')}</h1>

      <div className="columns">
        <div className="column is-two-thirds-desktop">
          <h2 className="subtitle is-3 has-text-centered">{t('exerciseText')}</h2>

          {/* TODO: use component UmlExerciseText! */}
          <div className="notification is-light-grey">
            {textParts.map((textPart, index) =>
              <Fragment key={index}>
                {typeof textPart !== 'string'
                  ? <span onClick={() => toggleClass(textPart.className)}
                          className={state.selectedClasses.includes(textPart.className) ? 'has-text-link' : 'has-text-black'}>{textPart.text}</span>
                  : <span>{textPart}</span>}
              </Fragment>
            )}
          </div>
        </div>

        <div className="column is-one-third-desktop">
          <h2 className="subtitle is-3 has-text-centered">{t('chosenClasses')}</h2>

          <div className="content">
            <ul>{state.selectedClasses.map((name) => <li key={name}>{name}</li>)}</ul>
          </div>
        </div>
      </div>

      <div className="columns">
        <div className="column">
          <button className={classNames('button', 'is-fullwidth', state.correction ? 'is-dark' : 'is-link')} onClick={correct} disabled={!!state.correction}>
            {t('correct')}
          </button>
        </div>
        <div className="column">
          <Link className={classNames('button', 'is-fullwidth', state.correction ? 'is-link' : 'is-dark')}
                to={'../parts/diagramDrawingHelp'} /*disabled={!corrected}*/
                title="Führen Sie zuerst die Korrektur aus!">Zum nächsten Aufgabenteil
          </Link>
        </div>
        <div className="column">
          <Link to="['../..']" className="button is-dark-warning is-fullwidth">Bearbeiten beenden</Link>
        </div>
      </div>

      {state.correction && <UmlClassSelectionCorrection correction={state.correction}/>}

    </div>
  );
}

// ui/src/app/tools/collection-tools/uml/uml-class-selection/uml-class-selection.component.ts
import {Component, Input, OnInit} from '@angular/core';
import {getIdForUmlExPart, getUmlExerciseTextParts, SelectableClass, UmlExerciseTextPart} from '../uml-tools';
import {ExerciseSolveFieldsFragment, UmlExerciseContentFragment} from '../../../../_services/apollo_services';
import {UmlExPart} from "../../../../_interfaces/graphql-types";

@Component({
  selector: 'it4all-uml-class-selection',
  templateUrl: './uml-class-selection.component.html'
})
export class UmlClassSelectionComponent implements OnInit {

  readonly nextPartId: string = getIdForUmlExPart(UmlExPart.DiagramDrawingHelp);

  @Input() exerciseFragment: ExerciseSolveFieldsFragment;
  @Input() exerciseContent: UmlExerciseContentFragment;

  selectableClasses: SelectableClass[];
  umlExerciseTextParts: UmlExerciseTextPart[];

  corrected = false;

  ngOnInit() {
    const {selectableClasses, textParts} = getUmlExerciseTextParts(this.exerciseFragment, this.exerciseContent);

    this.selectableClasses = selectableClasses;
    this.umlExerciseTextParts = textParts;
  }

  getSelectedClasses(): SelectableClass[] {
    return this.selectableClasses.filter((sc) => sc.selected);
  }

  toggleClassSelected(selectableClass: SelectableClass): void {
    selectableClass.selected = !selectableClass.selected;
  }

  correct(): void {
    this.corrected = true;
  }

  getCorrectClasses(): SelectableClass[] {
    return this.selectableClasses.filter((sc) => sc.selected && sc.isCorrect);
  }

  getMissingClasses(): SelectableClass[] {
    return this.selectableClasses.filter((sc) => !sc.selected && sc.isCorrect);
  }

  getWrongClasses(): SelectableClass[] {
    return this.selectableClasses.filter((sc) => sc.selected && !sc.isCorrect);
  }

}

<div class="container">
  <h1 class="title is-3 has-text-centered">Klassenselektion</h1>

  <div class="columns">
    <div class="column is-two-thirds-desktop">

      <h2 class="subtitle is-3 has-text-centered">Aufgabentext</h2>
      <div class="notification is-light-grey">
        <ng-container *ngFor="let textPart of umlExerciseTextParts">
          <span *ngIf="textPart.selectableClass"
                (click)="toggleClassSelected(textPart.selectableClass)"
                [ngClass]="textPart.selectableClass.selected ? 'has-text-link' : 'has-text-black'">{{textPart.text}}</span>

          <span *ngIf="!textPart.selectableClass">{{textPart.text}}</span>
        </ng-container>
      </div>
    </div>
    <div class="column is-one-third-desktop">
      <h2 class="subtitle is-3 has-text-centered">Gewählte Klassen</h2>

      <div class="content">
        <ul>
          <li *ngFor="let selectableClass of getSelectedClasses()">{{selectableClass.name}}</li>
        </ul>
      </div>
    </div>
  </div>

  <div class="columns">
    <div class="column">
      <button class="button is-fullwidth" (click)="correct()" [disabled]="corrected"
              [ngClass]="corrected ? 'is-dark' : 'is-link'">
        Korrektur
      </button>
    </div>
    <div class="column">
      <button class="button is-fullwidth" [routerLink]="['..', nextPartId]" [disabled]="!corrected"
              [ngClass]="corrected ? 'is-link': 'is-dark'" title="Führen Sie zuerst die Korrektur aus!">
        Zum nächsten Aufgabenteil
      </button>
    </div>
    <div class="column">
      <a [routerLink]="['../..']" class="button is-dark-warning is-fullwidth">Bearbeiten beenden</a>
    </div>
  </div>

  <ng-container *ngIf="corrected">
    <hr>

    <h2 class="subtitle is-3 has-text-centered">Korrektur</h2>

    <div class="columns">
      <div class="column">
        <h3 class="subtitle is-4 has-text-centered">Korrekte Klassen:</h3>
        <ul>
          <li *ngFor="let correctClass of getCorrectClasses()">&#10004;&nbsp;<code
            class="has-text-dark-success">{{correctClass.name}}</code></li>
        </ul>
      </div>

      <div class="column">
        <h3 class="subtitle is-4 has-text-centered">Fehlende Klassen:</h3>
        <ul>
          <li *ngFor="let missingClass of getMissingClasses()">&#10008;&nbsp;<code>{{missingClass.name}}</code></li>
        </ul>
      </div>

      <div class="column">
        <h3 class="subtitle is-4 has-text-centered">Falsche Klassen</h3>
        <ul>
          <li *ngFor="let wrongClass of getWrongClasses()">&#10067;&nbsp;<code>{{wrongClass.name}}</code></li>
        </ul>
      </div>
    </div>
  </ng-container>

</div>
