// react-ui/src/helpers/SolutionSaved.tsx
import React from "react";
import classNames from "classnames";

export function SolutionSaved({solutionSaved}: { solutionSaved: boolean }): JSX.Element {
  return (
    <div className={classNames('notification', 'is-light-grey', solutionSaved ? 'has-text-dark-success' : 'has-text-danger')}>
      &#10004; Ihre Lösung wurde {solutionSaved ? '' : <b>nicht</b>} gespeichert.
    </div>
  );
}

// client/src/app/tools/collection-tools/tool-helpers/solution-saved/solution-saved.component.ts
import {Component, Input} from '@angular/core';

@Component({
  selector: 'it4all-solution-saved',
  template: `
      <div class="notification has-text-success" *ngIf="saved; else notSavedBlock">Ihre Lösung wurde
          gespeichert.
      </div>
      <ng-template #notSavedBlock>
          <div class="notification has-text-danger">Ihre Lösung konnte nicht gespeichert werden!</div>
      </ng-template>`,
})
export class SolutionSavedComponent {

  @Input() saved: boolean;

  constructor() {
  }

}
