// react-ui/src/collectionTools/tools/uml/UmlAssocEdit.tsx
import { useState } from 'react';
import * as joint from 'jointjs';
import {MyJointClass} from './model/joint-class-diag-elements';

interface IProps {
  editedAssociation: joint.shapes.uml.Association;
  cancelEdit: () => void;
}

type Cardinality = '1' | '*';

interface IState {
  firstMult: Cardinality;
  secondMult: Cardinality;
}

export function UmlAssocEdit({editedAssociation, cancelEdit}: IProps): JSX.Element {

  const labels = editedAssociation.labels();

  const firstEnd = editedAssociation.getSourceCell() as MyJointClass;
  const secondEnd = editedAssociation.getTargetCell() as MyJointClass;

  const [state, setState] = useState<IState>({
    firstMult: (labels[0].attrs?.text?.text || '*') as Cardinality,
    secondMult: (labels[1].attrs?.text?.text || '*') as Cardinality
  });

  function updateAssoc(): void {
    editedAssociation.label(0, {position: 25, attrs: {text: {text: state.firstMult}}});
    editedAssociation.label(1, {position: -25, attrs: {text: {text: state.secondMult}}});

    cancelEdit();
  }

  return (
    <div className="card">
      <header className="card-header">
        <p className="card-header-title">Assoziation bearbeiten</p>
      </header>
      <div className="card-content">
        <div className="columns">
          <div className="column">{firstEnd.getClassName()}</div>
          <div className="column">
            <div className="select">
              <select title="Multiplizität" defaultValue={state.firstMult}
                      onChange={(event) => setState(({secondMult}) => ({secondMult, firstMult: event.target.value as Cardinality}))}>
                <option>1</option>
                <option>*</option>
              </select>
            </div>
          </div>
          <div className="column">
            <div className="select">
              <select defaultValue={state.secondMult}
                      onChange={(event) => setState(({firstMult}) => ({firstMult, secondMult: event.target.value as Cardinality}))}>
                <option>1</option>
                <option>*</option>
              </select>
            </div>
          </div>
          <div className="column">{secondEnd.getClassName()}</div>
        </div>
      </div>
      <footer className="card-footer">
        <a className="card-footer-item" onClick={cancelEdit}>Verwerfen</a>
        <a className="card-footer-item" onClick={updateAssoc}>Anwenden</a>
      </footer>
    </div>
  );
}

// ui/src/app/tools/collection-tools/uml/_components/uml-assoc-edit/uml-assoc-edit.component.ts
import {Component, EventEmitter, Input, OnChanges, Output, SimpleChanges} from '@angular/core';
import * as joint from 'jointjs';
import {MyJointClass} from '../../_model/joint-class-diag-elements';

@Component({
  selector: 'it4all-uml-assoc-edit',
  templateUrl: './uml-assoc-edit.component.html'
})
export class UmlAssocEditComponent implements OnChanges {

  @Input() editedAssociation: joint.shapes.uml.Association;

  @Output() cancel = new EventEmitter<void>();

  firstEnd: MyJointClass;
  firstMult: string;

  secondEnd: MyJointClass;
  secondMult: string;

  ngOnChanges(changes: SimpleChanges): void {
    const labels = this.editedAssociation.labels();

    this.firstEnd = this.editedAssociation.getSourceCell() as MyJointClass;
    this.firstMult = labels[0].attrs.text.text;

    this.secondEnd = this.editedAssociation.getTargetCell() as MyJointClass;
    this.secondMult = labels[1].attrs.text.text;
  }

  updateAssoc(firstMultValue: string, secondMultValue: string): void {
    this.editedAssociation.label(0, {position: 25, attrs: {text: {text: firstMultValue}}});
    this.editedAssociation.label(1, {position: -25, attrs: {text: {text: secondMultValue}}});
  }

}

<div class="card">
  <header class="card-header">
    <p class="card-header-title">Assoziation bearbeiten</p>
  </header>
  <div class="card-content">

    <div class="columns">
      <div class="column">
        {{firstEnd.getClassName()}}
      </div>
      <div class="column">
        <div class="select">
          <select title="Multiplizität" #firstMultSelect>
            <option [selected]="firstMult === '1'">1</option>
            <option [selected]="firstMult === '*'">*</option>
          </select>
        </div>
      </div>
      <div class="column">
        <div class="select">
          <select title="Multiplizität" #secondMultSelect>
            <option [selected]="secondMult === '1'">1</option>
            <option [selected]="secondMult === '*'">*</option>
          </select>
        </div>
      </div>
      <div class="column">
        {{secondEnd.getClassName()}}
      </div>
    </div>

  </div>
  <footer class="card-footer">
    <a class="card-footer-item" (click)="cancel.emit()">Verwerfen</a>
    <a class="card-footer-item" (click)="updateAssoc(firstMultSelect.value, secondMultSelect.value)">Anwenden</a>
  </footer>
</div>
