// react-ui/src/collectionTools/tools/sql/SqlTableContents.tsx
import React, {useState} from 'react';
import {SqlQueryResultFragment} from '../../../graphql';
import classNames from 'classnames';
import {SqlQueryResultTable} from './SqlQueryResultTable';

interface IProps {
  tables: SqlQueryResultFragment[];
}

export function SqlTableContents({tables}: IProps): JSX.Element {

  const [shownDbContent, setShownDbContent] = useState<SqlQueryResultFragment | undefined>();

  function activateModal(dbContent: SqlQueryResultFragment): void {
    setShownDbContent((currentShownDbContent) =>
      currentShownDbContent?.tableName === dbContent.tableName ? undefined : dbContent
    );
  }

  return (
    <>
      <div className="columns is-multiline">
        {tables.map((dbContent, index) =>
          <div className="column is-one-quarter-desktop" key={index}>
            <button className={classNames('button', 'is-fullwidth', {'is-info': dbContent === shownDbContent})} onClick={() => activateModal(dbContent)}>
              {dbContent.tableName}
            </button>
          </div>
        )}

      </div>

      {shownDbContent && <div className="card">
        <header className="card-header">
          <p className="card-header-title">{shownDbContent.tableName}</p>
        </header>
        <section className="card-content">
          <div className=" table-container">
            <SqlQueryResultTable queryResult={shownDbContent}/>
          </div>
        </section>
      </div>}
    </>
  );
}

// ui/src/app/tools/collection-tools/sql/_components/sql-table-contents/sql-table-contents.component.ts
import {Component, Input} from '@angular/core';
import {SqlQueryResultFragment} from "../../../../../_services/apollo_services";

@Component({
  selector: 'it4all-sql-table-contents',
  template: `
    <div class="columns is-multiline">
      <div class="column is-one-quarter-desktop" *ngFor="let dbContent of dbContents">
        <button class="button is-fullwidth" (click)="activateModal(dbContent)"
                [class.is-info]="dbContent === shownDbContent">
          {{dbContent.tableName}}
        </button>
      </div>
    </div>

    <div class="card" *ngIf="shownDbContent">
      <header class="card-header">
        <p class="card-header-title">{{shownDbContent.tableName}}</p>
      </header>
      <section class="card-content">
        <div class="table-container">
          <it4all-query-result-table [queryResult]="shownDbContent"></it4all-query-result-table>
        </div>
      </section>
    </div>`
})
export class SqlTableContentsComponent {

  @Input() dbContents: SqlQueryResultFragment[];

  shownDbContent: SqlQueryResultFragment | undefined;

  activateModal(sqlQueryResult: SqlQueryResultFragment): void {
    if (this.shownDbContent === sqlQueryResult) {
      this.shownDbContent = undefined;
    } else {
      this.shownDbContent = sqlQueryResult;
    }
  }

}

<div class="columns is-multiline">
  <div class="column is-one-quarter-desktop" *ngFor="let dbContent of dbContents">
    <button class="button is-fullwidth" (click)="activateModal(dbContent)"
            [ngClass]="shownDbContent === dbContent ? '' : 'is-info'">
      {{dbContent.tableName}}
    </button>
  </div>
</div>

<div class="card" *ngIf="shownDbContent">
  <header class="card-header">
    <p class="card-header-title">{{shownDbContent.tableName}}</p>
  </header>
  <section class="card-content">
    <div class="table-container">
      <table class="table is-bordered is-fullwidth">
        <thead>
          <tr>
            <th *ngFor="let colName of shownDbContent.columnNames">{{colName}}</th>
          </tr>
        </thead>
        <tbody>
          <tr *ngFor="let row of shownDbContent.rows">
            <td *ngFor="let colName of shownDbContent.columnNames">{{row.cells[colName].content}}</td>
          </tr>
        </tbody>
      </table>
    </div>
  </section>
</div>
