// react-ui/src/randomTools/NaryAddition.tsx
import {useState} from 'react';
import {RandomSolveButtons} from './RandomSolveButtons';
import {NaryNumberReadOnlyInputComponent, NaryReadOnlyNumberInput} from './NaryNumberReadOnlyInput';
import {BINARY_SYSTEM, NaryIState, NumberingSystem} from './nary';
import {randomInt} from './boolModel/booleanFormulaGenerator';
import {useTranslation} from 'react-i18next';
import {NaryLimits} from './NaryLimits';
import {NaryNumberInput} from './NaryNumberInput';
import {NaryNumberingSystemSelect} from './NaryNumberingSystemSelect';

interface IState extends NaryIState {
  numberingSystem: NumberingSystem;
  target: number,
  firstSummand: NaryReadOnlyNumberInput,
  secondSummand: NaryReadOnlyNumberInput,
}

function generateExercise(maxValueForDigits = 256, numberingSystem: NumberingSystem = BINARY_SYSTEM): IState {
  const target = randomInt(1, maxValueForDigits);

  const firstSummandDecimal = randomInt(1, target);

  const firstSummand: NaryReadOnlyNumberInput = {decimalNumber: firstSummandDecimal, maxValueForDigits, numberingSystem};

  const secondSummand: NaryReadOnlyNumberInput = {decimalNumber: target - firstSummandDecimal, maxValueForDigits, numberingSystem};

  return {max: maxValueForDigits, numberingSystem, target, firstSummand, secondSummand, checked: false, correct: false, solutionString: ''};
}

export function NaryAddition(): JSX.Element {

  const {t} = useTranslation('common');
  const [state, setState] = useState(generateExercise());

  function nextExercise(): void {
    setState((state) => generateExercise(state.max, state.numberingSystem));
  }

  function checkSolution(): void {
    const reversedSolutionString: string = state.solutionString
      .replace(/\s/g, '')
      .split('')
      .reverse()
      .join('');

    const solution: number = parseInt(reversedSolutionString, state.numberingSystem.radix);

    setState((state) => ({...state, checked: true, correct: solution === state.target}));
  }

  return (
    <div className="container mx-auto">
      <h1 className="mb-4 font-bold text-2xl text-center">{t('naryAddition')}</h1>

      <div className="grid grid-cols-2 gap-2">
        <NaryLimits max={state.max} update={(newValue) => setState(generateExercise(newValue))}/>
        <NaryNumberingSystemSelect label={t('numberingSystem')} system={state.numberingSystem}
                                   update={(newSystem) => setState(({max}) => generateExercise(max, newSystem))}/>
      </div>

      <hr className="my-4"/>

      <div className="my-4">
        <NaryNumberReadOnlyInputComponent labelContent={'Summand 1'} naryNumberInput={state.firstSummand}/>
      </div>

      <div className="my-4">
        <NaryNumberReadOnlyInputComponent labelContent={'Summand 2'} naryNumberInput={state.secondSummand}/>
      </div>

      <hr className="my-4"/>

      <NaryNumberInput key={state.solutionString} labelContent={t('solution')} initialValue={state.solutionString} checked={state.checked} correct={state.correct}
                       radix={state.numberingSystem.radix} update={(newValue) => setState((state) => ({...state, solutionString: newValue}))} rtl={true}/>

      <RandomSolveButtons toolId={'nary'} correct={checkSolution} nextExercise={nextExercise}/>

    </div>
  );
}

// it4all-client/src/app/tools/random-tools/nary/nary-addition/nary-addition.component.ts
import {Component, HostListener, OnInit} from '@angular/core';
import {NaryAdditionToolPart} from '../../random-tools-list';
import {ToolPart} from '../../../../_interfaces/tool';
import {BINARY_SYSTEM, NaryComponentBase, NaryReadOnlyNumberInput, NUMBERING_SYSTEMS, NumberingSystem} from '../nary';
import {randomInt} from '../../../../helpers';
import {Router} from '@angular/router';

@Component({
  templateUrl: './nary-addition.component.html',
  styles: [`
      #solution {
          direction: rtl;
          unicode-bidi: bidi-override
      }`
  ]
})
export class NaryAdditionComponent extends NaryComponentBase implements OnInit {

  toolPart: ToolPart = NaryAdditionToolPart;

  // noinspection JSMismatchedCollectionQueryUpdate
  numberingSystems: NumberingSystem[] = NUMBERING_SYSTEMS;

  system: NumberingSystem = BINARY_SYSTEM;

  target = 0;

  firstSummandInput: NaryReadOnlyNumberInput = {
    decimalNumber: 0,
    numberingSystem: this.system,
    fieldId: 'firstSummand',
    labelContent: 'Summand 1:',
    maxValueForDigits: this.max
  };

  secondSummandInput: NaryReadOnlyNumberInput = {
    decimalNumber: 0,
    numberingSystem: this.system,
    fieldId: 'secondSummand',
    labelContent: 'Summand 2:',
    maxValueForDigits: this.max
  };

  checked = false;
  correct = false;
  solutionString = '';

  constructor(private router: Router) {
    super();
  }

  ngOnInit(): void {
    this.update();
  }

  update(): void {
    this.checked = false;
    this.correct = false;
    this.solutionString = '';

    this.target = randomInt(1, this.max);

    const firstSummand = randomInt(1, this.target);

    this.firstSummandInput.decimalNumber = firstSummand;
    this.firstSummandInput.numberingSystem = this.system;
    this.firstSummandInput.maxValueForDigits = this.max;

    this.secondSummandInput.decimalNumber = this.target - firstSummand;
    this.secondSummandInput.numberingSystem = this.system;
    this.secondSummandInput.maxValueForDigits = this.max;
  }

  checkSolution(): void {
    const reversedSolutionString: string = this.solutionString
      .replace(/\s/g, '')
      .split('').reverse().join('');

    const solution: number = parseInt(reversedSolutionString, this.system.radix);

    this.checked = true;

    this.correct = solution === this.target;
  }

  end(): void {
    this.router.navigate(['/randomTools', this.tool.id]);
  }

  @HostListener('document:keypress', ['$event'])
  handleKeyboardEvent(event: KeyboardEvent): void {
    if (event.key === 'Enter') {
      if (this.correct) {
        this.update();
      } else {
        this.checkSolution();
      }
    }
  }

}
