// react-ui/src/collectionTools/tools/uml/UmlAssocMatchResult.tsx
import React from 'react';
import {MatchType, UmlAssociationMatchFragment, UmlMultiplicity} from '../../../graphql';


function printCardinality(c: UmlMultiplicity): string {
  return c === UmlMultiplicity.Unbound ? '*' : '1';
}

export function UmlAssocMatchResult({m}: { m: UmlAssociationMatchFragment }): JSX.Element {

  const {matchType, userArg, sampleArg, analysisResult} = m;

  const isCorrect = matchType === MatchType.SuccessfulMatch;

  const gottenCardinalities = `${printCardinality(userArg.firstMult)} : ${printCardinality(userArg.secondMult)}`;

  const correctCardinalities = (userArg.firstEnd === sampleArg.firstEnd)
    ? `${printCardinality(sampleArg.firstMult)} : ${printCardinality(sampleArg.secondMult)}`
    : `${printCardinality(sampleArg.secondMult)} : ${printCardinality(sampleArg.firstMult)}`;

  return (
    <div className={isCorrect ? 'has-text-dark-success' : 'has-text-danger'}>
      Die Assoziation von <code>{userArg.firstEnd}</code> nach <code>{userArg.secondEnd}</code> ist {isCorrect ? '' : 'nicht'} korrekt.

      {!isCorrect && <div className="content">
        <ul>
          <li className={analysisResult.assocTypeEqual ? 'has-text-dark-success' : 'has-text-danger'}>
            Der Typ der Assoziation <code>{userArg.assocType}</code> war {analysisResult.assocTypeEqual ? '' : 'nicht'} korrekt.
          </li>
          <li className={analysisResult.multiplicitiesEqual ? 'has-text-dark-success' : 'has-text-danger'}>
            Die Kardinalitäten der Assoziation <code>{gottenCardinalities}</code> waren {analysisResult.multiplicitiesEqual ? '' : 'nicht'} korrekt.
            {!analysisResult.multiplicitiesEqual && <> Erwartet wurde <code>{correctCardinalities}</code></>}
          </li>
        </ul>
      </div>}
    </div>
  );
}

// ui/src/app/tools/collection-tools/uml/_components/uml-assoc-match-result/uml-assoc-match-result.component.ts
import {Component, Input} from '@angular/core';
import {
  MatchType,
  UmlAssociationMatchFragment,
  UmlAssociationMatchingResultFragment,
  UmlMultiplicity
} from "../../../../../_services/apollo_services";

function printCardinality(c: UmlMultiplicity): string {
  return c === UmlMultiplicity.Unbound ? '*' : '1';
}

@Component({
  selector: 'it4all-uml-assoc-match-result',
  template: `
    <ul>
      <li *ngFor="let m of assocResult.allMatches">
        <div [ngClass]="isCorrect(m) ? 'has-text-dark-success' : 'has-text-danger'">
          Die Assoziation von <code>{{m.userArg.firstEnd}}</code> nach
          <code>{{m.userArg.secondEnd}}</code> ist {{isCorrect(m) ? '' : 'nicht'}} korrekt.

          <div *ngIf="!isCorrect" class="content">
            <ul>
              <li [ngClass]="m.analysisResult.assocTypeEqual ? 'has-text-dark-success' : 'has-text-danger'">
                Der Typ der Assoziation <code>{{m.userArg.assocType}}</code>
                war {{m.analysisResult.assocTypeEqual ? '' : 'nicht'}} korrekt.
              </li>
              <li
                [ngClass]="m.analysisResult.multiplicitiesEqual ? 'has-text-dark-success' : 'has-text-danger'">
                Die Kardinalitäten der Assoziation <code>{{gottenMultiplicities(m)}}</code>
                waren {{m.analysisResult.multiplicitiesEqual ? '' : 'nicht'}}
                korrekt.
                <ng-container *ngIf="!m.analysisResult.multiplicitiesEqual">Erwartet
                  wurde {{correctCardinalities}}</ng-container>
              </li>
            </ul>
          </div>
        </div>
      </li>

      <li *ngFor="let mu of assocResult.notMatchedForUser" class="has-text-danger">
        Die Assoziation von <code>{{mu.firstEnd}}</code> nach <code>{{mu.secondEnd}}</code> ist falsch.
      </li>

      <li *ngFor="let ms of assocResult.notMatchedForSample" class="has-text-danger">
        Die Assoziation von <code>{{ms.firstEnd}}</code> nach <code>{{ms.secondEnd}}</code> fehlt.
      </li>
    </ul>
  `
})
export class UmlAssocMatchResultComponent {

  @Input() assocResult: UmlAssociationMatchingResultFragment;

  isCorrect(m: UmlAssociationMatchFragment): boolean {
    return m.matchType === MatchType.SuccessfulMatch;
  }

  gottenMultiplicities(m: UmlAssociationMatchFragment): string {
    return `${printCardinality(m.userArg.firstMult)} : ${printCardinality(m.userArg.secondMult)}`;
  }

  correctCardinalities(m: UmlAssociationMatchFragment): string {
    if (m.userArg.firstEnd === m.sampleArg.firstEnd) {
      return printCardinality(m.sampleArg.firstMult) + ' : ' + printCardinality(m.sampleArg.secondMult);
    } else {
      return printCardinality(m.sampleArg.secondMult) + ' : ' + printCardinality(m.sampleArg.firstMult);
    }
  }


}
