// ui/src/app/tools/collection-tools/uml/_components/uml-class-edit/uml-class-edit.component.ts
import {Component, Input} from '@angular/core';
import {MyJointClass} from '../../_model/joint-class-diag-elements';
import {IUmlAttribute} from '../../uml-interfaces';

@Component({
  selector: 'it4all-uml-class-edit',
  templateUrl: './uml-class-edit.component.html'
})
export class UmlClassEditComponent {

  readonly visibilities = ['+', '-', '#', '~'];
  readonly umlTypes = ['String', 'int', 'double', 'char', 'boolean', 'void'];

  @Input() editedClass: MyJointClass;

  removeAttribute(attr: IUmlAttribute): void {
    const newAttributes = this.editedClass.getAttributes().filter((a) => a !== attr);
    this.editedClass.setAttributes(newAttributes);

    console.info(this.editedClass.getAttributes());
  }

}

<div class="card">
  <header class="card-header">
    <p class="card-header-title">{{editedClass.getClassName()}}</p>
  </header>
  <div class="card-content">
    <ng-container *ngFor="let attr of editedClass.getAttributes()">
      <select title="Sichtbarkeit" [value]="attr.visibility">
        <option *ngFor="let visibility of visibilities" [selected]="visibility === attr.visibility">
          {{visibility}}
        </option>
      </select>
      &nbsp;
      <input type="text" title="Attributname" placeholder="Attributname" [value]="attr.name">
      :
      <select title="Datentyp" [value]="attr.type">
        <option *ngFor="let umlType of umlTypes" [selected]="umlType === attr.type">{{umlType}}</option>
      </select>
      &nbsp;
      <button title="Attribut löschen" (click)="removeAttribute(attr)">-</button>
    </ng-container>

    <hr>

    <div>
      <select title="Sichtbarkeit">
        <option *ngFor="let visibility of visibilities">{{visibility}}</option>
      </select>
      &nbsp;
      <input type="text" title="Attributname" placeholder="Attributname">
      :
      <select title="Datentyp">
        <option *ngFor="let umlType of umlTypes">{{umlType}}</option>
      </select>
    </div>

    <hr>

    <ng-container *ngFor="let method of editedClass.getMethods()">
      {{method | json}}
    </ng-container>

  </div>
  <footer class="card-footer">
    <a class="card-footer-item" (click)="editedClass = undefined">Verwerfen</a>
    <a class="card-footer-item">Anwenden</a>
  </footer>
</div>

// react-ui/src/collectionTools/tools/uml/UmlClassEdit.tsx
import React from 'react';
import {MyJointClass} from './model/joint-class-diag-elements';
import {UmlAttribute, UmlClass, UmlClassType, UmlMethod, UmlVisibility} from '../../../graphql';
import {Field, FieldArray, Form, Formik} from 'formik';
import {useTranslation} from 'react-i18next';

interface IProps {
  editedClass: MyJointClass;
  cancelEdit: () => void;
}

const visibilities = ['+', '-', '#', '~'];
const umlTypes = ['String', 'int', 'double', 'char', 'boolean', 'void'];

const umlClassTypes: UmlClassType[] = [UmlClassType.Abstract, UmlClassType.Interface, UmlClassType.Class];

function emptyAttribute(): UmlAttribute {
  return {memberType: umlTypes[umlTypes.length - 1], memberName: '', visibility: UmlVisibility.Public, isAbstract: false, isDerived: false, isStatic: false};
}

function emptyMethod(): UmlMethod {
  return {memberType: umlTypes[umlTypes.length - 1], memberName: '', visibility: UmlVisibility.Public, isAbstract: false, isStatic: false, parameters: ''};
}

export function UmlClassEdit({editedClass, cancelEdit}: IProps): JSX.Element {

  const {t} = useTranslation('common');

  const initialValues: UmlClass = {
    classType: UmlClassType.Class,
    name: editedClass.getClassName(),
    attributes: editedClass.getAttributes(),
    methods: editedClass.getMethods()
  };

  function onSubmit(newClass: UmlClass): void {
    console.info(JSON.stringify(newClass, null, 2));
  }

  return (
    <Formik initialValues={initialValues} onSubmit={onSubmit}>
      {({values}) =>
        <Form>
          <div className="box">

            <div className="field has-addons">
              <div className="control">
                <div className="select">
                  <Field as="select" name="classType">
                    {umlClassTypes.map((classType) => <option key={classType}>{classType}</option>)}
                  </Field>
                </div>
              </div>
              <div className="control is-expanded">
                <Field name="name" className="input"/>
              </div>
            </div>

            <hr/>

            <FieldArray name="attributes">
              {(arrayHelpers) => <>

                {values.attributes.map((attr, index) =>
                  <div className="field has-addons" key={index}>
                    <div className="control">
                      <div className="select">
                        <Field as="select" name={`attributes.${index}.visibility`}>
                          {visibilities.map((visibility) => <option key={visibility}>{visibility}</option>)}
                        </Field>
                      </div>
                    </div>
                    <div className="control is-expanded">
                      <Field type="text" name={`attributes.${index}.memberName`} className="input" placeholder={t('name')}/>
                    </div>
                    <div className="control">
                      <button className="button is-static">:</button>
                    </div>
                    <div className="control">
                      <div className="select">
                        <Field as="select" name={`attributes.${index}.memberType`}>
                          {umlTypes.map((umlType) => <option key={umlType}>{umlType}</option>)}
                        </Field>
                      </div>
                    </div>
                    <div className="control">
                      <button onClick={() => arrayHelpers.remove(index)} className="button">-</button>
                    </div>
                  </div>
                )}

                <button type="button" onClick={() => arrayHelpers.push(emptyAttribute())} className="button">+</button>
              </>}
            </FieldArray>

            <hr/>

            <FieldArray name="methods">
              {(arrayHelpers) => <>

                {values.methods.map((method, index) => <div className="field has-addons" key={index}>
                  <div className="control">
                    <div className="select">
                      <Field as="select" name={`methods.${index}.visibility`}>
                        {visibilities.map((visibility) => <option key={visibility}>{visibility}</option>)}
                      </Field>
                    </div>
                  </div>
                  <div className="control">
                    <Field name={`methods.${index}.memberName`} className="input" placeholder={t('name')}/>
                  </div>
                  <div className="control">
                    <button className="button is-static">(</button>
                  </div>
                  <div className="control is-expanded">
                    <Field name={`methods.${index}.parameters`} className="input" placeholder={t('parameters')}/>
                  </div>
                  <div className="control">
                    <button className="button is-static">):</button>
                  </div>
                  <div className="control">
                    <div className="select">
                      <Field as="select" name={`methods.${index}.memberType`}>
                        {umlTypes.map((umlType) => <option key={umlType}>{umlType}</option>)}
                      </Field>
                    </div>
                  </div>
                  <div className="control">
                    <button className="button" onClick={() => arrayHelpers.remove(index)}>-</button>
                  </div>
                </div>)}

                <button type="button" onClick={() => arrayHelpers.push(emptyMethod())} className="button">+</button>
              </>}
            </FieldArray>

            <hr/>

            <div className="columns">
              <div className="column">
                <button className="button is-fullwidth" onClick={cancelEdit}>Verwerfen</button>
              </div>
              <div className="column">
                <button className="button is-link is-fullwidth">Anwenden</button>
              </div>
            </div>
          </div>

        </Form>
      }
    </Formik>
  );
}
