// client/src/app/tools/collection-tools/regex/regex-exercise/regex-exercise.component.ts
import {Component, HostListener, OnInit} from '@angular/core';
import {ActivatedRoute} from '@angular/router';
import {ApiService} from '../../_services/api.service';
import {RegexCorrectionResult, RegexExercise} from '../regex-exercise';
import {RegexTool} from '../regex-tool';
import {Tool} from '../../../../_interfaces/tool';
import {DexieService} from '../../../../_services/dexie.service';

@Component({templateUrl: './regex-exercise.component.html'})
export class RegexExerciseComponent implements OnInit {

  tool: Tool = RegexTool;
  solution = '';

  collId: number;
  exId: number;

  exercise: RegexExercise;

  corrected = false;
  result: RegexCorrectionResult;

  displaySampleSolutions = false;
  showInfo = false;

  constructor(private route: ActivatedRoute, private apiService: ApiService, private dexieService: DexieService) {
    this.collId = parseInt(route.snapshot.paramMap.get('collId'), 10);
    this.exId = parseInt(route.snapshot.paramMap.get('exId'), 10);
  }

  ngOnInit(): void {
    this.apiService.getExercise<RegexExercise>(this.tool.id, this.collId, this.exId)
      .subscribe((exercise: RegexExercise) => this.exercise = exercise);

    this.dexieService.regexSolutions.get([this.collId, this.exId])
      .then((oldSolution) => this.solution = oldSolution ? oldSolution.solution : '');
  }

  correct(): void {
    if (this.solution === undefined || this.solution.length === 0) {
      alert('Sie können keine leere Lösung abgeben!');
      return;
    }

    this.dexieService.regexSolutions.put({
      collId: this.collId, exId: this.exercise.id, solution: this.solution
    });

    this.apiService
      .correctSolution<string, RegexCorrectionResult>(this.tool.id, this.collId, this.exId, 'regex', this.solution)
      .subscribe((result: RegexCorrectionResult) => {
        this.corrected = true;
        this.result = result;
        // // console.error(JSON.stringify(this.result.extractionResults, null, 2));
        // console.warn(this.result.extractionResults.length);
      });
  }

  triggerSampleSolutions(): void {
    this.displaySampleSolutions = !this.displaySampleSolutions;
  }

// FIXME: make directive?
  @HostListener('document:keypress', ['$event'])
  handleKeyboardEvent(event: KeyboardEvent): void {
    if (event.key === 'Enter') {
      // if (this.correct) {
      // this.update();
      // } else {
      this.correct();
      // }
    }
  }

}

<div *ngIf="exercise != undefined" class="container is-fluid">

  <div class="columns">
    <div class="column is-half-desktop">
      <h1 class="title is-3 has-text-centered">Aufgabenstellung</h1>
      <div class="notification is-dark">{{exercise.text}}</div>

      <div class="field has-addons">
        <div class="control">
          <label class="button is-static" for="solution">Ihre Lösung:</label>
        </div>
        <div class="control is-expanded">
          <input type="text" class="input" id="solution" [(ngModel)]="solution" placeholder="Ihre Lösung" autofocus
                 autocomplete="off">
        </div>
      </div>

      <div class="columns">
        <div class="column">
          <button class="button is-link is-fullwidth" (click)="correct()">Lösung testen</button>
        </div>
        <div class="column">
          <button class="button is-primary is-fullwidth" (click)="triggerSampleSolutions()">
            Musterlösungen&nbsp;<span *ngIf="!displaySampleSolutions">anzeigen</span><span
            *ngIf="displaySampleSolutions">ausblenden</span>
          </button>
        </div>
        <div class="column">
          <a [routerLink]="['/tools', tool.id, 'collections', collId]" class="button is-dark is-fullwidth">
            Bearbeiten beenden
          </a>
        </div>
      </div>

      <ng-container *ngIf="displaySampleSolutions">
        <h2 class="subtitle is-4 has-text-centered">Musterlösungen</h2>

        <div class="columns is-multiline">
          <div class="column is-half" *ngFor="let sampleSolution of exercise.sampleSolutions">
            <div class="notification is-dark">
              <code>{{sampleSolution.sample}}</code>
            </div>
          </div>
        </div>
      </ng-container>

      <div class="buttons">
        <button (click)="showInfo = !showInfo;" class="button is-info is-fullwidth">
          Hilfe&nbsp;<span *ngIf="!showInfo">anzeigen</span><span *ngIf="showInfo">ausblenden</span>
        </button>
      </div>

      <it4all-regex-cheatsheet *ngIf="showInfo"></it4all-regex-cheatsheet>


    </div>

    <div class="column is-half-desktop" *ngIf="corrected && result">

      <h1 class="title is-3 has-text-centered">Korrektur</h1>

      <it4all-solution-saved [saved]="result.solutionSaved"></it4all-solution-saved>

      <br>

      <it4all-points-notification [result]="result"></it4all-points-notification>

      <br>

      <ng-container [ngSwitch]="result.correctionType">

        <ng-container *ngSwitchCase="'MATCHING'">
          <div class="columns is-multiline">
            <div class="column is-half-desktop" *ngFor="let matchingResult of result.matchingResults">
              <it4all-regex-matching-result [matchingResult]="matchingResult"></it4all-regex-matching-result>
            </div>
          </div>
        </ng-container>

        <ng-container *ngSwitchCase="'EXTRACTION'">
          <ng-container *ngFor="let extractionResult of result.extractionResults">
            <it4all-regex-extraction-result [extractionResult]="extractionResult"></it4all-regex-extraction-result>

            <br>
          </ng-container>
        </ng-container>
      </ng-container>

      <!-- FIXME: sample solutions! -->
    </div>
  </div>
</div>

// react-ui/src/collectionTools/tools/regex/RegexExercise.tsx
import React, {useState} from "react";
import {ExerciseSolveFieldsFragment, RegexExerciseContentFragment} from "../../../generated/graphql";
import {RegexCheatSheet} from './RegexCheatSheet';
import {BulmaTabs, TabConfig} from "../../../helpers/BulmaTabs";
import {useTranslation} from "react-i18next";
import {RegexCorrection} from './RegexCorrection';
import {StringSampleSolution} from "../StringSampleSolution";

interface IProps {
  exerciseFragment: ExerciseSolveFieldsFragment;
  contentFragment: RegexExerciseContentFragment;
}

export function RegexExercise({exerciseFragment, contentFragment}: IProps): JSX.Element {

  const {t} = useTranslation('common');
  const [showInfo, setShowInfo] = useState(false);
  const [showSampleSolutions, setShowSampleSolutions] = useState(false);

  function correct(): void {
    console.info('TODO'!);
  }

  const tabConfigs: TabConfig[] = [
    {id: 'correction', name: t('correction'), render: () => <RegexCorrection/>},
    {
      id: 'sampleSolutions', name: t('sampleSolution_plural'), render: () => <div>
        <div className="buttons">
          <button className="button is-primary is-fullwidth" onClick={() => setShowSampleSolutions((value) => !value)}>
            Musterlösungen {showSampleSolutions ? 'ausblenden' : 'anzeigen'}
          </button>
        </div>

        {showSampleSolutions && contentFragment.regexSampleSolutions.map((sample, index) => <StringSampleSolution sample={sample} key={index}/>)}
      </div>
    }
  ];

  return (
    <div className="container is-fluid">

      <div className="columns">
        <div className="column is-two-fifths-desktop">
          <h1 className="title is-3 has-text-centered">{t('exerciseText')}</h1>
          <div className="notification is-light-grey">{exerciseFragment.text}</div>

          <div className="field has-addons">
            <div className="control">
              <label className="button is-static" htmlFor="solution">Ihre Lösung:</label>
            </div>
            <div className="control is-expanded">
              {/* [(ngModel)]="solution" */}
              <input type="text" className="input" id="solution" placeholder="Ihre Lösung" autoFocus autoComplete="off"/>
            </div>
          </div>

          <div className="columns">
            <div className="column">
              <button className="button is-link is-fullwidth" onClick={correct}>Lösung testen</button>
            </div>
            <div className="column">
              {/* [routerLink]="['../..']" */}
              <a className="button is-dark is-fullwidth">Bearbeiten beenden</a>
            </div>
          </div>
          <div className="buttons">
            <button className="button is-info is-fullwidth" onClick={() => setShowInfo((value) => !value)}>
              Hilfe {showInfo ? 'ausblenden' : 'anzeigen'}
            </button>
          </div>

          {showInfo && <RegexCheatSheet/>}
        </div>

        <div className="column">
          <BulmaTabs tabs={tabConfigs}/>
          {/*    <it4all-tabs>

        <it4all-tab [title]="sampleSolutionsTabTitle">

        </it4all-tab>
      </it4all-tabs>
      */}
        </div>
      </div>
    </div>


  )

}
