// react-ui/src/collectionTools/tools/xml/XmlExercise.tsx
import React from 'react';
import {ConcreteExerciseIProps} from '../../Exercise';
import {
  ExerciseFileFragment,
  FilesSolution,
  useXmlCorrectionMutation,
  XmlCorrectionMutation,
  XmlExerciseContentFragment,
  XmlExPart,
  XmlSolutionInput
} from '../../../graphql';
import {FilesExercise} from '../FilesExercise';
import {WithQuery} from '../../../WithQuery';
import {useTranslation} from 'react-i18next';
import {SolutionSaved} from '../../../helpers/SolutionSaved';
import {PointsNotification} from '../../../helpers/PointsNotification';
import {XmlDocumentResultDisplay} from './XmlDocumentResultDisplay';
import {XmlGrammarResultDisplay} from './XmlGrammarResultDisplay';
import {database} from '../../DexieTable';

type IProps = ConcreteExerciseIProps<XmlExerciseContentFragment, XmlSolutionInput>;

export function getXmlGrammarContent(rootNode: string): string {
  return `<!ELEMENT ${rootNode} (EMPTY)>`;
}

export function getXmlDocumentContent(rootNode: string): string {
  return `
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ${rootNode} SYSTEM "${rootNode}.dtd">
<${rootNode}>
</${rootNode}>`.trim();
}


export function XmlExercise({exercise, content, partId, oldSolution}: IProps): JSX.Element {

  const {t} = useTranslation('common');
  const [correctExercise, correctionMutationResult] = useXmlCorrectionMutation();

  if (!content.xmlPart) {
    throw new Error('TODO!');
  }

  const part = content.xmlPart;

  const isGrammarPart = part === XmlExPart.GrammarCreationXmlPart;

  const grammarFile = {
    name: `${content.rootNode}.dtd`,
    content: oldSolution
      ? oldSolution.grammar
      : (isGrammarPart ? getXmlGrammarContent(content.rootNode) : content.xmlSampleSolutions[0].grammar),
    fileType: 'dtd',
    editable: isGrammarPart,
  };

  const documentFile = {
    name: `${content.rootNode}.xml`,
    content: oldSolution?.document || getXmlDocumentContent(content.rootNode),
    fileType: 'xml',
    editable: !isGrammarPart,
  };

  const exerciseDescription = isGrammarPart
    ? <>
      <p className="has-text-weight-bold">Erstellen Sie eine DTD zu folgender Beschreibung:</p>
      <p>{content.grammarDescription}</p>
      <p className="is-italic has-text-info">
        Hinweis: Benutzen Sie die in Klammern angegebenen Element- bzw. Attributnamen. Falls nichts anderes
        angegeben ist, sollen die Elemente nur Text enthalten.
      </p>
    </>
    : <span>{exercise.text}</span>;

  function correct(files: ExerciseFileFragment[]): void {
    const solution: XmlSolutionInput = {grammar: files[0].content, document: files[1].content};

    database.upsertSolution(exercise.toolId, exercise.collectionId, exercise.exerciseId, partId, solution);

    correctExercise({variables: {collId: exercise.collectionId, exId: exercise.exerciseId, solution, part}})
      .catch((err) => console.error(err));
  }

  function renderCorrection({xmlExercise}: XmlCorrectionMutation): JSX.Element {
    if (!xmlExercise) {
      return <div className="notification is-danger has-text-centered">{t('error while correction...')}</div>;
    }

    const {solutionSaved, /*proficienciesUpdated, resultSaved,*/ result} = xmlExercise.correct;

    return (
      <>
        <SolutionSaved solutionSaved={solutionSaved}/>

        {isGrammarPart && <PointsNotification points={result.points} maxPoints={result.maxPoints}/>}

        {result.documentResult && <XmlDocumentResultDisplay result={result.documentResult}/>}

        {result.grammarResult && <XmlGrammarResultDisplay result={result.grammarResult}/>}

      </>
    );
  }

  // FIXME: sample solutions!

  const sampleSolutions: FilesSolution[] = content.xmlSampleSolutions.map(({document, grammar}) => {
    return {
      files: [
        isGrammarPart
          ? {name: `${content.rootNode}.dtd`, content: grammar, fileType: 'dtd', editable: false}
          : {name: `${content.rootNode}.xml`, content: document, fileType: 'xml', editable: false}
      ]
    };
  });

  const correctionTabRender = <WithQuery query={correctionMutationResult} render={renderCorrection}/>;

  return <FilesExercise exerciseId={exercise.exerciseId} exerciseDescription={exerciseDescription} initialFiles={[grammarFile, documentFile]}
                        sampleSolutions={sampleSolutions} correct={correct} isCorrecting={correctionMutationResult.loading}
                        correctionTabRender={correctionTabRender}/>;
}

// ui/src/app/tools/collection-tools/xml/xml-exercise/xml-exercise.component.ts
import {Component, Input, OnInit} from '@angular/core';
import {ComponentWithExerciseDirective} from '../../_helpers/component-with-exercise.directive';
import {
  ExerciseFileFragment,
  ExerciseSolveFieldsFragment,
  XmlAbstractResultFragment,
  XmlCorrectionGQL,
  XmlCorrectionMutation,
  XmlCorrectionMutationVariables,
  XmlCorrectionResultFragment,
  XmlDocumentResultFragment,
  XmlExerciseContentFragment,
  XmlExPart,
  XmlGrammarResultFragment,
  XmlInternalErrorResultFragment,
  XmlResultFragment,
  XmlSolution,
  XmlSolutionInput
} from '../../../../_services/apollo_services';

import 'codemirror/mode/dtd/dtd';
import 'codemirror/mode/xml/xml';
import {HasSampleSolutions} from "../../_helpers/correction-helpers";
import {DexieService} from "../../../../_services/dexie.service";


export function getIdForXmlExPart(xmlExPart: XmlExPart): string {
  switch (xmlExPart) {
    case XmlExPart.DocumentCreationXmlPart:
      return 'document';
    case XmlExPart.GrammarCreationXmlPart:
      return 'grammar';
  }
}

export function getXmlGrammarContent(rootNode: string): string {
  return `<!ELEMENT ${rootNode} (EMPTY)>`;
}

export function getXmlDocumentContent(rootNode: string): string {
  return `
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ${rootNode} SYSTEM "${rootNode}.dtd">
<${rootNode}>
</${rootNode}>`.trim();
}


@Component({
  selector: 'it4all-xml-exercise',
  templateUrl: './xml-exercise.component.html'
})
export class XmlExerciseComponent
  extends ComponentWithExerciseDirective<XmlSolutionInput, XmlCorrectionMutation, XmlCorrectionMutationVariables>
  implements OnInit, HasSampleSolutions<XmlSolution> {

  @Input() exerciseFragment: ExerciseSolveFieldsFragment;
  @Input() contentFragment: XmlExerciseContentFragment;

  partId: string;

  isGrammarPart: boolean;

  grammarFile: ExerciseFileFragment;
  documentFile: ExerciseFileFragment;

  exerciseFileFragments: ExerciseFileFragment[] = [];

  constructor(xmlCorrectionGQL: XmlCorrectionGQL, dexieService: DexieService) {
    super(xmlCorrectionGQL, dexieService);
  }

  ngOnInit() {
    const rootNode = this.contentFragment.rootNode;

    this.partId = getIdForXmlExPart(this.contentFragment.xmlPart);
    this.isGrammarPart = this.partId === 'grammar';

    const grammarFileName = `${rootNode}.dtd`;
    this.grammarFile = {
      name: grammarFileName,
      content: this.isGrammarPart ? getXmlGrammarContent(rootNode) : this.contentFragment.xmlSampleSolutions[0].grammar,
      fileType: 'dtd',
      editable: this.isGrammarPart,
    };

    const documentFileName = `${rootNode}.xml`;
    this.documentFile = {
      name: documentFileName,
      content: getXmlDocumentContent(rootNode),
      fileType: 'xml',
      editable: !this.isGrammarPart,
    };

    this.exerciseFileFragments = [this.grammarFile, this.documentFile];

    this.loadOldSolutionAbstract(this.exerciseFragment, this.partId, (oldSol) => {
      this.grammarFile.content = oldSol.grammar;
      this.documentFile.content = oldSol.document;

      // do not delete or else editor does not get updated...
      this.exerciseFileFragments = [this.grammarFile, this.documentFile];
    });
  }

  // Correction

  protected getSolution(): XmlSolutionInput {
    return {
      grammar: this.grammarFile.content,
      document: this.documentFile.content
    };
  }

  protected getMutationQueryVariables(): XmlCorrectionMutationVariables {
    return {
      exId: this.exerciseFragment.exerciseId,
      collId: this.exerciseFragment.collectionId,
      solution: this.getSolution(),
      part: this.contentFragment.xmlPart,
    };
  }

  correct(): void {
    this.correctAbstract(this.exerciseFragment, this.partId);
  }

  // Results

  get correctionResult(): XmlCorrectionResultFragment | null {
    return this.resultQuery?.me.xmlExercise?.correct;
  }

  get xmlAbstractResult(): XmlAbstractResultFragment & (XmlResultFragment | XmlInternalErrorResultFragment) | null {
    return this.correctionResult?.result;
  }

  private get xmlResult(): XmlResultFragment | null {
    return this.xmlAbstractResult?.__typename === 'XmlResult' ? this.xmlAbstractResult : null;
  }

  get grammarResult(): XmlGrammarResultFragment | null {
    return this.xmlResult?.grammarResult;
  }

  get documentResult(): XmlDocumentResultFragment | null {
    return this.xmlResult?.documentResult;
  }

  // Sample solutions

  displaySampleSolutions = false;

  toggleSampleSolutions() {
    this.displaySampleSolutions = !this.displaySampleSolutions;
  }

  get sampleSolutions(): XmlSolution[] {
    return this.contentFragment.xmlSampleSolutions;
  }

}

<div class="container is-fluid">

  <div class="columns">
    <div class="column is-half-desktop">
      <it4all-exercise-files-editor
        [exerciseFiles]="exerciseFiles"
        [mode]="'xml'">
      </it4all-exercise-files-editor>
    </div>

    <div class="column is-half-desktop">
      <it4all-tabs>
        <it4all-tab [title]="'Aufgabenstellung'">

          <div class="notification is-light-grey">
            <ng-container *ngIf="part.id === 'grammar'; else documentTextBlock">
              <p class="has-text-weight-bold">Erstellen Sie eine DTD zu folgender Beschreibung:</p>
              <p>{{exerciseContent.grammarDescription}}</p>
              <p class="is-italic has-text-info">
                Hinweis: Benutzen Sie die in Klammern angegebenen Element- bzw. Attributnamen. Falls nichts anderes
                angegeben ist, sollen die Elemente nur Text enthalten.
              </p>
            </ng-container>
            <ng-template #documentTextBlock>
              TODO!
            </ng-template>
          </div>

          <div class="columns">
            <div class="column">
              <button class="button is-link is-fullwidth" [class.is-loading]="isCorrecting" (click)="correct()">
                Korrektur
              </button>
            </div>
            <div class="column">
              <button class="button is-primary is-fullwidth" (click)="showSampleSolution()" disabled>
                Musterlösung anzeigen
              </button>
            </div>
            <div class="column">
              <a [routerLink]="['../..']" class="button is-dark is-fullwidth">Bearbeiten beenden</a>
            </div>
          </div>
        </it4all-tab>
        <it4all-tab [title]="correctionTabTitle">

          <ng-container *ngIf="result">

            <it4all-solution-saved [saved]="result.solutionSaved"></it4all-solution-saved>

            <br>

            <it4all-points-notification [points]="result.points" [maxPoints]="result.maxPoints">
            </it4all-points-notification>

            <br>

            <ng-container *ngIf="result.documentResult.length > 0">
              <!-- Document correction! -->

            </ng-container>
            <ng-container *ngIf="result.grammarResult">
              <!-- Grammar correction -->

              <div *ngFor="let parseError of result.grammarResult.parseErrors">
                <div>Fehler beim Parse von &quot;<code>{{parseError.parsedLine}}</code>&quot;:</div>
                <div class="has-text-danger">{{parseError.msg}}</div>
              </div>

              <div *ngFor="let gr of result.grammarResult.results" class="content">

                <ng-container [ngSwitch]="gr.matchType">
                  <p *ngSwitchCase="'ONLY_SAMPLE'" class="has-text-danger">
                    Die Definition des Elements <code>{{gr.sampleArg.name}}</code> fehlt!
                  </p>
                  <p *ngSwitchCase="'ONLY_USER'" class="has-text-danger">
                    Die Definition des Elements <code>{{gr.userArg.name}}</code> ist falsch!
                  </p>
                  <p *ngSwitchCase="'SUCCESSFUL_MATCH'">
                    Das Element <code>{{gr.userArg.name}} ist korrekt.</code>
                  </p>
                  <div *ngSwitchDefault class="has-text-danger">
                    <p>Der Vergleich des Elements <code>{{gr.userArg.name}}</code> war nicht erfolgreich:</p>
                    <ul>
                      <li [ngClass]="gr.analysisResult.contentCorrect ? 'has-text-success': 'has-text-danger'">
                        Der Inhalt des Elements war {{gr.analysisResult.contentCorrect ? '' : 'nicht'}} korrekt.
                        <ng-container *ngIf="!gr.analysisResult.contentCorrect">
                          Erwartet wurde <code>{{gr.analysisResult.correctContent}}</code>
                        </ng-container>
                      </li>
                      <li [ngClass]="gr.analysisResult.attributesCorrect ? 'has-text-success' : 'has-text-danger'">
                        Die Attribute des Elements waren {{gr.analysisResult.attributesCorrect ? '' : 'nicht'}} korrekt.
                        <ng-container *ngIf="!gr.analysisResult.attributesCorrect">
                          Erwartet wurde <code>{{gr.analysisResult.correctAttributes}}</code>
                        </ng-container>
                      </li>
                    </ul>
                  </div>

                </ng-container>

              </div>

            </ng-container>

          </ng-container>

        </it4all-tab>
      </it4all-tabs>

    </div>
  </div>

</div>
