// react-ui/src/randomTools/NaryAddition.tsx
import React, {useState} from 'react';
import {RandomSolveButtons} from './RandomToolBase';
import classNames from 'classnames';
import {NaryNumberReadOnlyInputComponent} from './NaryNumberReadOnlyInput';
import {allNumberingSystems, BINARY_SYSTEM, maximalMax, minimalMax, NaryReadOnlyNumberInput, NumberingSystem} from './nary';
import {randomInt} from './bool/_model/bool-formula';
import {useTranslation} from 'react-i18next';

const firstSummandFieldId = 'firstSummand';
const secondSummandFieldId = 'secondSummand';

interface IState {
  system: NumberingSystem;
  target: number,
  firstSummand: NaryReadOnlyNumberInput,
  secondSummand: NaryReadOnlyNumberInput,
  checked: boolean;
  correct: boolean;
  solutionString: string,
}

function generateExercise(max: number, system: NumberingSystem = BINARY_SYSTEM): IState {
  const target = randomInt(1, max);

  const firstSummandDecimal = randomInt(1, target);

  const firstSummand: NaryReadOnlyNumberInput = {
    decimalNumber: firstSummandDecimal,
    fieldId: firstSummandFieldId,
    maxValueForDigits: max,
    labelContent: 'Summand 1',
    numberingSystem: system
  };

  const secondSummand: NaryReadOnlyNumberInput = {
    decimalNumber: target - firstSummandDecimal,
    fieldId: secondSummandFieldId,
    maxValueForDigits: max,
    labelContent: 'Summand 2',
    numberingSystem: system
  };

  return {system, target, firstSummand, secondSummand, checked: false, correct: false, solutionString: ''};
}

export function NaryAddition(): JSX.Element {

  const {t} = useTranslation('common');
  const [max, setMax] = useState(256);
  const [state, setState] = useState(generateExercise(max));

  function updateNumberingSystem(/*event: ChangeEvent<HTMLSelectElement>*/): void {
    console.info('TODO: update...');
  }

  function nextExercise(): void {
    setState((state) => generateExercise(max, state.system));
  }

  function checkSolution(): void {
    console.info('TODO');
    /*
    const reversedSolutionString: string = state.solutionString
      .replace(/\s/g, '')
      .split('')
      .reverse()
      .join('');

    const solution: number = parseInt(reversedSolutionString, state.system.radix);

    const checked = true;

    const correct = solution === state.target;
     */
  }

  return (
    <div className="container">
      <h1 className="title is-3 has-text-centered">{t('naryAddition')}</h1>

      <div className="columns">
        <div className="column">
          <div className="field">
            <label className="label has-text-centered" htmlFor="max">Maximalwert</label>
            <div className="field has-addons">
              <div className="control">
                <button className="button" onClick={() => setMax(max / 2)} disabled={max === minimalMax}>/ 2</button>
              </div>
              <div className="control is-expanded">
                <input className="input has-text-centered" type="number" id="max" value={max} readOnly/>
              </div>
              <div className="control">
                <button className="button" onClick={() => setMax(max * 2)} disabled={max === maximalMax}>* 2</button>
              </div>
            </div>
          </div>
        </div>
        <div className="column">
          <div className="field">
            <label htmlFor="numberSystem" className=" label has-text-centered">Zahlensystem</label>
            <div className=" control">
              <div className=" select is-fullwidth">
                {/*ngModel="system"*/}
                <select onChange={updateNumberingSystem} id="numberSystem">
                  {allNumberingSystems.map((ns) => <option key={ns.radix} value={ns.radix}>{ns.radix} - {ns.name}</option>)}
                </select>
              </div>
            </div>
          </div>
        </div>
      </div>

      <hr/>

      <div className="my-3">
        <NaryNumberReadOnlyInputComponent naryNumberInput={state.firstSummand}/>
      </div>

      <div className="my-3">
        <NaryNumberReadOnlyInputComponent naryNumberInput={state.secondSummand}/>
      </div>

      <hr/>

      <div className="field">
        <div className="field has-addons">
          <div className="control">
            <div className="button is-static">
              <label htmlFor="solution">Lösung:</label>
            </div>
          </div>
          <div className="control is-expanded">
            {/*ngModel="solutionString"*/}
            <input type="text" id="solution" placeholder=" Lösung" autoFocus autoComplete="off"
                   className={classNames('input', {
                     'is-success': state.checked && state.correct,
                     'is-danger': state.checked && !state.correct
                   })}/>
          </div>
          <div className=" control">
            <div className=" button is-static">
              <sub>{state.system.radix}</sub>
            </div>
          </div>
        </div>
      </div>

      {state.checked && <div className={classNames('notification', 'has-text-centered', state.correct ? 'is-success' : 'is-danger')}>
        {state.correct
          ? <span>&#10008; Die Lösung ist nicht korrekt.</span>
          : <span>&#10004; Die Lösung ist korrekt.</span>
        }
      </div>}

      <RandomSolveButtons correct={checkSolution} nextExercise={nextExercise}/>

    </div>
  );
}

// client/src/app/tools/random-tools/nary/nary-addition/nary-addition.component.ts
import {Component, HostListener, OnInit} from '@angular/core';
import {NaryAdditionToolPart, NaryTool} from '../../random-tools-list';
import {Tool, ToolPart} from '../../../../_interfaces/tool';
import {BINARY_SYSTEM, NaryReadOnlyNumberInput, NUMBERING_SYSTEMS, NumberingSystem} from '../nary';
import {randomInt} from '../../../../helpers';
import {Router} from '@angular/router';

@Component({
  templateUrl: './nary-addition.component.html',
  styles: [`
      #solution {
          direction: rtl;
          unicode-bidi: bidi-override
      }`
  ]
})
export class NaryAdditionComponent implements OnInit {

  tool: Tool = NaryTool;
  toolPart: ToolPart = NaryAdditionToolPart;

  // noinspection JSMismatchedCollectionQueryUpdate
  numberingSystems: NumberingSystem[] = NUMBERING_SYSTEMS;

  system: NumberingSystem = BINARY_SYSTEM;

  readonly minimalMax = 16;
  readonly maximalMax = Math.pow(2, 32);
  max = 256;

  target = 0;

  firstSummandInput: NaryReadOnlyNumberInput = {
    decimalNumber: 0,
    numberingSystem: this.system,
    fieldId: 'firstSummand',
    labelContent: 'Summand 1:'
  };

  secondSummandInput: NaryReadOnlyNumberInput = {
    decimalNumber: 0,
    numberingSystem: this.system,
    fieldId: 'secondSummand',
    labelContent: 'Summand 2:'
  };

  checked = false;
  correct = false;
  solutionString = '';

  constructor(private router: Router) {
  }

  ngOnInit(): void {
    this.update();
  }

  update(): void {
    this.checked = false;
    this.correct = false;
    this.solutionString = '';

    this.target = randomInt(1, this.max);

    const firstSummand = randomInt(1, this.target);

    this.firstSummandInput.decimalNumber = firstSummand;
    this.firstSummandInput.numberingSystem = this.system;
    this.firstSummandInput.maxValueForDigits = this.max;

    this.secondSummandInput.decimalNumber = this.target - firstSummand;
    this.secondSummandInput.numberingSystem = this.system;
    this.secondSummandInput.maxValueForDigits = this.max;
  }

  checkSolution(): void {
    const reversedSolutionString: string = this.solutionString
      .replace(/\s/g, '')
      .split('').reverse().join('');

    const solution: number = parseInt(reversedSolutionString, this.system.radix);

    this.checked = true;

    this.correct = solution === this.target;
  }

  end(): void {
    this.router.navigate(['/randomTools', this.tool.id]);
  }

  @HostListener('document:keypress', ['$event'])
  handleKeyboardEvent(event: KeyboardEvent): void {
    if (event.key === 'Enter') {
      if (this.correct) {
        this.update();
      } else {
        this.checkSolution();
      }
    }
  }

  halfMax(): void {
    this.max = Math.max(this.minimalMax, this.max / 2);
    this.update();
  }

  doubleMax(): void {
    this.max = Math.min(this.maximalMax, this.max * 2);
    this.update();
  }

}

<div class="container">

  <h1 class="title is-3 has-text-centered">{{toolPart.name}}</h1>

  <div class="columns">
    <div class="column is-half-desktop is-offset-one-quarter-desktop">

      <div class="field">
        <label for="numberSystem" class="label has-text-centered">Zahlensystem</label>
        <div class="control">
          <div class="select is-fullwidth">
            <select [(ngModel)]="system" (change)="update()" id="numberSystem">
              <option *ngFor="let ns of numberingSystems" [ngValue]="ns">{{ns.radix}} - {{ns.name}}</option>
            </select>
          </div>
        </div>
      </div>

      <label class="label has-text-centered" for="max">Maximalwert (Summe):</label>
      <div class="field has-addons">
        <div class="control">
          <button class="button" (click)="doubleMax()" [disabled]="max === maximalMax">* 2</button>
        </div>
        <div class="control is-expanded">
          <input class="input has-text-centered" type="number" id="max" value="{{max}}">
        </div>
        <div class="control">
          <button class="button" (click)="halfMax()" [disabled]="max === minimalMax">/ 2</button>
        </div>
      </div>

      <hr>

      <it4all-nary-number-read-only-input [naryNumberInput]="firstSummandInput"></it4all-nary-number-read-only-input>

      <br>

      <it4all-nary-number-read-only-input [naryNumberInput]="secondSummandInput"></it4all-nary-number-read-only-input>

      <hr>

      <div class="field">
        <div class="field has-addons">
          <div class="control">
            <div class="button is-static">
              <label for="solution">Lösung:</label>
            </div>
          </div>
          <div class="control is-expanded">
            <input type="text" class="input" id="solution" [(ngModel)]="solutionString"
                   [ngClass]="{'is-success': checked && correct, 'is-danger': checked && !correct}"
                   placeholder="Lösung" autofocus autocomplete="off">
          </div>
          <div class="control">
            <div class="button is-static">
              <sub>{{system.radix}}</sub>
            </div>
          </div>
        </div>
      </div>

      <div class="notification has-text-centered is-danger" *ngIf="checked && !correct">
        &#10008; Die Lösung ist nicht korrekt.
      </div>
      <div class="notification has-text-centered is-success" *ngIf="checked && correct">
        &#10004; Die Lösung ist korrekt.
      </div>

      <br>

      <it4all-random-solve-buttons (correctEmitter)="checkSolution()" (nextEmitter)="update()" (endEmitter)="end()">
      </it4all-random-solve-buttons>

    </div>
  </div>

</div>
